// =========================================================================
// questStories.js — one short story beat for every Spelling Quest level
// (20 worlds x 20 levels), shown and read aloud before the level's fight.
// The world's own intro and outro live with the world in questWorlds.js.
// =========================================================================
import { worldOf, stepOf } from "./questWorlds.js";

export const LEVEL_STORIES = [
  // World 1
  [
    "Under the reading lamp you spot a tiny red bookmark with teeth marks on it. A Dust Bunny hops out from behind the books to stop you!",
    "The bookmark leads to a shiny pool of spilled ink. Something gurgles, and an Ink Blot rises up, dripping and grumpy.",
    "Little rat footprints in the ink climb up the tall shelves. Grab the ladder and follow them, but watch out for that fluttering Paper Moth!",
    "Up in the attic, sunlight pours through a dusty window. A scrap of paper squeaks, 'Find me if you can!' A Page Mite giggles nearby.",
    "A big map hangs under a banner, and someone has scribbled a rat-shaped arrow on it. It points deeper into the library. A Dust Bunny guards the way.",
    "The card catalog has hundreds of tiny drawers. One is chewed open, and a card inside says 'Page of Letters: way down.' Ink Blots ooze out!",
    "A friendly owl named Hoot lands on the ladder beside you. 'The Rat King went that way,' he hoots, pointing past a swarm of Paper Moths.",
    "In the cozy story corner, the flowers droop because the books have no letters left. Hoot sighs. A Page Mite is nibbling the storybooks, so stop it!",
    "Shh! In the quiet room, every sound is a clue. You hear tiny squeaks behind the window curtain, and a sneaky Dust Bunny tries to hush you.",
    "A lantern glows over the bookbinder's desk, with glue and thread ready. You can fix the Great Word Book here once you find the page. An Ink Blot spills across the desk!",
    "In the poetry aisle, the poems are missing letters, so they sound silly. Hoot reads one and laughs. Paper Moths flutter out of the pages.",
    "Giant globes spin slowly on the shelves. One has a rat-sized door on it! It is locked, and a Page Mite holds the key. Win it back!",
    "Behind the globe door is a mountain of crumpled paper. You dig through it and find your red bookmark again. Dust Bunnies pop out of the pile!",
    "Lantern light flickers across a desk covered in notes. The Rat King has been writing riddles here! One says, 'Look where the old books sleep.' An Ink Blot smudges the rest.",
    "The rare books vault has tall stone columns and very old books. Hoot whispers, 'This is where the old books sleep.' A Paper Moth swoops down to guard the vault.",
    "Pull the right book and the shelf swings open! Torches light a secret passage going down. The Rat King's squeaky laugh echoes ahead, and Page Mites scurry along the floor.",
    "The Index Hall lists every word in the library. Under R, someone wrote 'Rat King, Ruler of Letters!' Cross it out after you beat these Ink Blots.",
    "Moonlight shines through a round window onto fresh rat footprints. Hoot flaps his wings. 'We are close!' A cloud of Paper Moths tries to block your path.",
    "Nobody has visited the forgotten stacks in a hundred years. From the top of the ladder, you spot a glowing page behind a banner. Dust Bunnies make one last stand!",
    "Torches light up the Riddle Rat King's den. He waves the Page of Letters under his tiny crown and squeaks, 'Spell my words, or it stays mine!' Win it back!",
  ],
  // World 2
  [
    "A little bluebird lands on the fence and opens her beak, but no song comes out. You name her Pip. A Moss Toad hops onto the path, croaking grumpily.",
    "Pip flies into a ring of red toadstools. In the middle you find a tiny boot print, just gnome sized. A Thorn Sprite zips out to chase you off.",
    "A gate made of brambles blocks the trail. More tiny boot prints lead under it. Acorn Grubs wiggle out of the bushes to guard the gate.",
    "You crawl through a hollow log with Pip riding on your shoulder. Inside, a gnome dropped a red feather from his hat. A Spell Slug slimes toward you!",
    "Fireflies blink in the glade like little lanterns. They spell a word in the air: HAT. Pip tilts her head. A Moss Toad tries to gobble the fireflies!",
    "Under the moon, a wise old owl peeks from her tree. 'The Gnome Chief hides the page under his hat,' she whispers. Thorn Sprites buzz around her branch.",
    "Juicy berries grow by the trail, and someone took big gnome bites out of them. The boot prints go on. An Acorn Grub is guarding the best berries.",
    "This brook should babble, but it only whispers. Hop across the rocks while Pip splashes in the pool. A Spell Slug blocks the last stepping stone.",
    "Giant ferns tower over you like green umbrellas. Somewhere ahead you hear grumbling, deep and cranky. Moss Toads hide under every leaf.",
    "A kind woodcutter waves from her hut. 'Gnomes marched past this morning, heading for the deep woods,' she says. Thorn Sprites are tangled in her fence!",
    "Flowers fill the sunny clearing, and for a moment Pip almost chirps! One page more and she will sing again. Acorn Grubs roll in to spoil the fun.",
    "The old wooden bridge creaks over a still pond. A note on the rail says 'Gnomes only!' in messy letters. A Spell Slug oozes across the planks.",
    "A busy squirrel chatters from her tree and drops a leaf. On it is a map to Gnome Village! But a Moss Toad snatches the leaf. Get it back!",
    "The map leads through a thicket of prickly bushes. Pip hides in your pocket. Thorn Sprites love this place, and they are not happy to see you.",
    "You toss a pebble into the wishing well and wish for the Page of Sounds. Splash! An Acorn Grub climbs up the stones, grumbling.",
    "Rows of little lanterns light a trail made for tiny feet. The gnomes hung them so they would not get lost. Follow the glow past the Spell Slugs!",
    "Gnomes sell mushroom pies in little tents here, but the stalls are empty. A sign reads 'Closed for the Chief's party.' Moss Toads have taken over the market.",
    "The trees grow so tall that the sky disappears. Pip shivers, so you hold up a lantern. The grumbling is loud now, and Thorn Sprites dart between the ferns.",
    "The biggest oak in the woods stands at the edge of Gnome Village. From its branches you see one pointy hat taller than all the rest. Acorn Grubs drop from the leaves!",
    "In Gnome Village, the Grumble Gnome Chief stands on a mushroom and pats his tall hat. 'The page stays under here!' he grumbles. Spell your best to win it back!",
  ],
  // World 3
  [
    "You light a torch at the cave mouth and shout 'Hello!' The echo calls back 'Pickle!' Something is wrong in here. A Rockling rolls out to meet you.",
    "Crystals sparkle in every color, lighting the hall like a rainbow. Something heavy scraped a path across the floor. A Crystal Bat swoops down from the shiny ceiling!",
    "Glowing mushrooms grow between the crystals. One of them wiggles, then hops! It is a Shroomp, and it bounces right at you.",
    "In the echo tunnel you say 'cat,' and it answers 'spoon.' The rhymes are all mixed up! A misty Echo Ghost floats out, giggling.",
    "A tiny glowworm floats on the glow pool, lost and blinking. You name him Glim, and he lights your way. A Rockling splashes out of the water!",
    "Stalactites hang like icicles, and hundreds of bats sleep upside down. Tiptoe past them! But one Crystal Bat wakes up and squeaks the alarm.",
    "Water drips on the slippery stone steps. Drip, drop, plop! Glim spots a footprint in a puddle, bigger than your whole body. Shroomps hop up the stairs.",
    "Old miners left a ladder going down into the gem mine. Sparkly gems poke out of the walls. Rocklings think every gem belongs to them!",
    "A rusty minecart track runs deeper into the dark, with lanterns along the fence. Hop in a cart and roll! An Echo Ghost rides in the cart behind you.",
    "Someone left a lantern on a rock, still glowing. Scratched beside it are the words 'Troll sits on rhymes, past the river.' A Crystal Bat circles the light.",
    "A dark river flows under the mountain, with a stone bridge across it. Glim glows bright to show the way. Shroomps bounce along the bridge to stop you.",
    "Crystal flowers bloom here and chime when you walk by. They should chime in rhymes, but they only clunk. A Rockling is stomping on the petals!",
    "Tall columns fill the whisper chamber. Put your ear to one and you hear a deep, grumpy voice: 'My rhymes, my seat!' Echo Ghosts swirl around the columns.",
    "Old dinosaur bones are stuck in the wall, smiling with stony teeth. Glim finds another giant footprint beside them. Crystal Bats hang from the fossils.",
    "A wobbly rope bridge stretches over a deep gap, lit by one torch. Hold on tight and do not look down! Rocklings bounce on the ropes to make it sway.",
    "You step inside a giant geode, full of purple crystal points. Your voice bounces everywhere, and it almost rhymes! Shroomps sprout from the floor to stop you.",
    "A long ladder goes down an old mine shaft, and Glim lights each rung. From below comes a rumble like a sleepy giant snoring. An Echo Ghost floats up the ladder.",
    "In the deep dark, only the crystals and Glim give any light. The troll's footprints are everywhere now. A Crystal Bat flaps out of the shadows.",
    "Warm orange lava bubbles far below, glowing on the rocks. Up ahead you see a throne made of crystal. Rocklings tumble down to guard it!",
    "The Stone Troll sits on his crystal throne, right on top of the Page of Rhymes. 'Not moving!' he rumbles. Spell your words and make him budge!",
  ],
  // World 4
  [
    "You push a little boat off the sandy shore. A seagull named Gus lands on the front and squawks hello. A Crab Clacker scuttles out from behind a rock!",
    "In the tide pools, starfish wave their arms. Gus spots purple ink swirling in the water, a clue from the Kraken! A Puffer Pest puffs up big to block you.",
    "Bright coral glows under the waves like a crystal garden. The fish swim in circles, unable to tell their stories. A Squid Scribbler squirts ink across the reef.",
    "An old shipwreck leans against the rocks. Its logbook is blank, because the stories are gone. Barnacle Blobs cling to the ship and will not let go.",
    "Whoosh! The water spins in a giant whirlpool. Row hard to stay out of it! Gus flaps and points as a Puffer Pest bobs in the swirl.",
    "Tall seaweed sways under your boat like a green forest. Purple ink drifts between the leaves, so the Kraken passed this way! A Crab Clacker snaps at your oars.",
    "The pirates in this cove should be telling tall tales, but they just stare at the sea. 'The Kraken took our stories,' one sighs. Squid Scribblers splash in the shallows.",
    "Climb the tall lighthouse and look out. Far away, a ship with a big black flag sails toward the storm. Barnacle Blobs crawl up the tower stairs.",
    "On Treasure Island you dig under a palm tree and find a chest. Inside is a note: 'The Captain sails into the storm.' A Puffer Pest guards the chest.",
    "A glass bottle washes up by the palm trees. The message inside is scribbled in purple ink: 'Catch me if you can! Captain K.' A Crab Clacker grabs the bottle.",
    "Friendly dolphins leap beside your boat and push it faster. Gus rides the waves on a dolphin's back! A Squid Scribbler tries to spoil their splashy fun.",
    "Rocky points hang from the roof of a sea cave. Inside, the walls are covered in octopus doodles. A Barnacle Blob oozes off the wall to stop you.",
    "Thick fog rolls in, and you cannot see your own hand. Gus squawks to guide you. Puffer Pests pop out of the mist one by one.",
    "Bong! A sunken bell rings from an old tower under the waves. It rings toward the storm, as if to warn you. Crab Clackers clatter on the bell.",
    "At the harbor docks, sailors give you a bigger, stronger boat for the storm ahead. 'Bring back our stories,' they say. Squid Scribblers ink the dock planks.",
    "Gus takes you to Seagull Rock, where his whole family lives. They saw the Kraken's ship just past the clouds. A Barnacle Blob is sitting on their nest!",
    "Dark clouds rumble overhead, and rain starts to fall. Pull on your raincoat and hold the wheel. Puffer Pests puff up even bigger in the storm.",
    "A giant wave rises taller than a house! Ride it to the top, and you can see the Kraken's flag. Crab Clackers surf down the wave to stop you.",
    "Lightning flashes, and the Kraken's ship is right beside you now. Gus holds on to your hat. Squid Scribblers leap aboard to slow you down!",
    "Captain Kraken Quill waves a giant feather pen in each of his eight arms. The Page of Stories flaps from his mast. 'Spell your way past me, sailor!' he bellows.",
  ],
  // World 5
  [
    "The sand is so hot it sizzles under your boots. A little desert fox peeks from behind a cactus and follows you. A Sand Scorpling pops out of the dune!",
    "Cacti stand in rows like a prickly garden. Your fox friend, Sunny, sniffs out a broken clay tablet with half a riddle on it. A Cactus Crank grumbles at you.",
    "Cool water and shady palms! Sunny drinks from the pool. At the edge you find a second tablet piece with a pyramid drawn on it. A Dust Devil spins in.",
    "Is that a lake? No, it is a mirage, a trick of the hot sun! The water fades as you walk closer. A Riddle Scarab clicks, 'What is real?'",
    "Dunes roll on and on like a sea of sand. Sunny hops from top to top. Sand Scorplings hide just under the surface, waiting to pinch.",
    "The path squeezes between tall rocks. Tiny scorpion tracks are everywhere, so step carefully. A Cactus Crank has rolled into the middle of the pass.",
    "Traders sell rugs and dates under striped tents. A kind camel named Dot offers you a ride across the sand. A Dust Devil whirls through the stalls, scattering hats!",
    "Only the tops of columns poke out of the sand here. Dot digs with her hooves and uncovers a carving of a sphinx! Riddle Scarabs crawl out of the cracks.",
    "A huge sun dial points its shadow toward the pyramids. Sunny finds a third tablet piece by the stone. It reads 'The Sphinx waits beyond the gold.' Sand Scorplings dig in.",
    "A sandstorm whips across the dunes! Cover your eyes and hold on to Dot. A Cactus Crank tumbles out of the swirling cloud.",
    "Climb the giant pyramid steps one by one. From the top you see a golden gate far away, shining in the sun. A Dust Devil spins up the stairs after you.",
    "The canyon walls are painted with old pictures of riddles and answers. Some answers are scratched out, so the Sphinx was here! A Riddle Scarab guards the paintings.",
    "This rock is shaped like a sleepy snake. Sunny curls up in its shade for a nap. Wake up! Sand Scorplings are crawling out from under the rock.",
    "Night falls, and you make camp under the moon and stars. Dot tells you the Sphinx loves riddles more than anything. A Cactus Crank rolls into camp, grumbling.",
    "Behind a pile of rocks you find a hidden well, cool and deep. You lower a bucket and pull up the last tablet piece! A Dust Devil swirls around the well.",
    "A golden gate stands between two tall columns with fluttering banners. The finished tablet tells you the password. Riddle Scarabs line up to test you!",
    "Past the gate you find a lost caravan, its tents half buried in sand. The travelers forgot every riddle they knew. Sand Scorplings have taken over their camp.",
    "Torches flicker down a long hall of columns. Sunny's ears perk up, because she hears soft purring ahead, like a giant cat. A Cactus Crank blocks the hall.",
    "Inside the hidden tomb, the walls glow with torchlight. Big paw prints lead to one last door. A Dust Devil and a swarm of Riddle Scarabs stand in your way!",
    "The Dune Sphinx rests between the pyramids with the Page of Riddles under her paw. 'Answer me with words, young speller,' she purrs. Show her what you can spell!",
  ],
  // World 6
  [
    "Your boots crunch through fresh snow under a tall pine. A Snow Puff bounces out from behind the tree, puffing cold air right at you!",
    "An ice bridge stretches over a deep, snowy gap. It creaks with every step, and two Snow Puffs roll out to block the other side.",
    "The lake is frozen like glass. Under the ice, you spot a line of poem words, stuck and still. The Yeti must have passed this way!",
    "Icicles hang from the cave roof like crystal teeth. An Ice Imp giggles and starts flicking frosty sparks at your feet.",
    "A whole field of snowmen stands in rows. One of them winks at you. That is no snowman. It is a Snow Puff in disguise!",
    "High on the ridge, snowy branches hold big round eyes. A Frost Owl hoots a frozen poem word and swoops down at you.",
    "Little igloos glow in the evening. The camp folks say they heard huge footsteps heading up the mountain last night. But first, an Ice Imp!",
    "You grab a sled and zoom down the hill past a wooden fence. At the bottom, a Yeti Cub is waiting, ready to play rough.",
    "The pine forest is quiet and thick. Snow drips from the branches, and every few trees you find another frozen word stuck to the bark.",
    "Warm steam rises from a hot spring between the rocks. You thaw your fingers, but a grumpy Ice Imp wants the warm water for itself!",
    "A tall gate made of ice blocks the path, sparkling with crystals. A Frost Owl guards it and will only let a good speller pass.",
    "The waterfall froze in the middle of falling. Inside the ice, you can read half a poem: 'The snow is deep, the Yeti's...' The rest is missing!",
    "A cozy ski lodge sits halfway up the peak. The skiers point higher and say the Yeti grumbles when anyone hums a tune. A Yeti Cub blocks the door.",
    "Penguins slide off the rocks to cheer you on. Then a Snow Puff tumbles in and scatters them. Time to clear the way!",
    "Wind howls through the pass, and snow fills the clouds. You can barely see your own hands as a Frost Owl dives out of the white.",
    "The storm clears, and green and purple lights dance across the sky. Under the moon, two Ice Imps sneak toward you on tiptoe.",
    "Giant footprints sink deep into the snow beside the rocks. They are Yeti tracks, and they lead straight up! A Yeti Cub tries to hide them.",
    "The glacier shines blue and bright, with crystals on every side. Deep inside, you see the shape of a page frozen in the ice!",
    "A banner flaps at the top of the summit path. The ground starts to rumble. Something very big is waking up just ahead.",
    "At the frozen peak, the Avalanche Yeti rises from a mountain of snow with the Page of Poems tucked under his arm. Spell your best to win it back!",
  ],
  // World 7
  [
    "You hop onto the first fluffy cloud, and it squishes like a pillow. A Thunder Puff rumbles up beside you, crackling with tiny sparks.",
    "A rainbow arches from one cloud to the next. You walk across its colors, but a Rain Wisp drips onto the bridge to make it slippery.",
    "Bright kites and banners fly all across the field. One kite has a face! It is a Kite Sprite, and it wants to tangle you in string.",
    "Raindrops tumble down into a sparkling pool. The water used to sing as it fell, but now it is silent. The Storm Roc took its song too.",
    "Dark clouds pile up around a stone tower on the hill. Boom! A Thunder Puff rolls out, grumbling louder with every step you take.",
    "Windmills spin on a floating island. The miller says a giant bird flew past, flapping so hard it bent the blades. A Breeze Griffin swoops in!",
    "Flowers bloom right on top of the clouds here. They should be humming, but they are hushed. A Rain Wisp is soaking their petals.",
    "You find a huge nest in a cloud tree, lined with feathers as long as your arm. The Storm Roc lives near here, but not in this nest.",
    "Hot air balloons are tied up by their tents at the port. A Kite Sprite has cut their ropes loose. Catch it before they float away!",
    "Sunbeams shine on white columns, and the rainbow glows across the plaza. A Breeze Griffin lands on a column and spreads its wings at you.",
    "The Cloud Castle's halls are silent. The queen of the clouds whispers that the Storm Roc took the Page of Songs to the highest tower.",
    "Night falls on the starlight deck, and the moon rises close enough to touch. A Thunder Puff tries to cover the stars with gray fluff.",
    "Tiny hummingbirds buzz between the flowers and columns. They lead you onward with their wings, since they cannot sing the way. A Rain Wisp follows close behind.",
    "Cloud walls rise on every side, and every path looks the same. Kite Sprites laugh as they float above the maze, trying to get you lost.",
    "A tall weather vane spins and spins on its tower. It stops and points one way: toward the storm clouds. That is where the Roc is!",
    "Bubbles float up from a pool under the rainbow. One bubble pops with a tiny, faraway note of song. The page must be close!",
    "Sky ships sail between the clouds at the harbor. A captain gives you a ride toward the storm, but a Breeze Griffin lands on the deck.",
    "Thundercap is a cloud as big as a mountain, flashing with light. Thunder Puffs gather here by the dozen. Stay brave and keep going!",
    "Two lightning towers crackle on either side of the path. Up top, you hear a giant squawk and the flap of enormous wings.",
    "At the top of a tower, in a nest of branches, the Storm Roc guards the Page of Songs. It spreads its stormy wings. Spell it out!",
  ],
  // World 8
  [
    "The huge city gates tick open, gear by gear. Inside, every sign is spelled wrong. A Gear Gremlin grins and swaps two more letters.",
    "Houses line Gear Street, with gears turning on every wall. A street sign says 'Gear Stret.' A Cog Crawler clatters out to stop you fixing it.",
    "Market stalls sell springs of every size. A Spring Bot bounces from tent to tent, knocking over boxes and boinging right at you!",
    "Pipes hiss and puff all over the steam factory. A Steam Imp pops out of a valve, blowing clouds of hot fog in your face.",
    "The bridge is made of giant turning cogs. Step on the right teeth to cross! A Cog Crawler rolls along the gears toward you.",
    "The bell tower rings the hour, but the bells sound jumbled and wrong. A shopkeeper says the biggest clock in the city is somewhere farther in.",
    "Pipes twist up, down, and sideways in this maze. Steam Imps whistle through the tubes, trying to trick you down the wrong path.",
    "Robots stand half-built in a workshop full of blocks and gears. One of them lights up. It is a Spring Bot, and it wants to fight!",
    "Lanterns glow along the lane outside cozy houses. On one door, someone scratched a clue: 'The Clockmaker never leaves his tower.'",
    "A steam train puffs into the station. You hop aboard and ride deeper into the city, but a Gear Gremlin is hiding in the luggage!",
    "You climb into an old inventor's attic. Through the round window you see it: a giant clock tower on the far side of the city.",
    "A copper canal flows past shiny pipes. You ride a little boat along it, while a Cog Crawler paddles after you with its legs.",
    "You run along the rooftops, jumping from house to house. Gear Gremlins chase you, trying to unscrew the shingles under your feet.",
    "Clock trees in the park tick instead of rustle. A Steam Imp hides in a hollow trunk, puffing steam to slow you down.",
    "Sparks fly in a lab full of humming pipes and lanterns. A Spring Bot charges up, glowing brighter. Spell fast before it zaps!",
    "Brass shelves hold books with every word mixed up. One book is about the Great Clockmaker, and it says the page is locked inside his biggest clock.",
    "Tall smokestacks puff gray clouds over the houses. You can barely see, but you hear a Cog Crawler clinking closer and closer.",
    "Metal flowers bloom among the gears, opening and closing like tiny clocks. A Gear Gremlin is picking them. Make it stop!",
    "In Clock Square, lanterns light up a huge tower. Its giant clock ticks loudly. The Clockmaker's door is right across the square.",
    "Inside his tower, the Great Clockmaker turns from his giant clock. The Page of Spelling is locked behind its glass. Fix his mixed-up words to win it!",
  ],
  // World 9
  [
    "Mist curls around the tall reeds at the edge of the marsh. A tiny firefly blinks at you, and then a Bog Wisp floats out of the fog.",
    "You hop across lily pads on the dark water. Each one wobbles under your feet. A Night Newt peeks up and flicks its tail at you!",
    "Fireflies line up like little lanterns in the reeds, showing you the way. A Firefly Phantom slips into the line, trying to lead you off course.",
    "The ground here is soft and squishy. Step carefully! A Mud Mauler rises out of the bog, dripping with brown, gloopy mud.",
    "Willow branches hang down like curtains. Behind them, you find a broken spoon covered in purple goo. That must belong to the witch!",
    "Hundreds of frogs sit on the lilies, croaking a song. They croak the same word over and over: 'Murkle, Murkle.' Then a Night Newt hops in.",
    "The full moon shines on a still, round pool. When you look in, you see a sleepy village with no dreams. A Bog Wisp ripples the picture away.",
    "A creaky boardwalk winds over the reeds. Some boards are missing, so jump the gaps! A Mud Mauler waits at the far end.",
    "Cattails grow tall and thick in every direction. Your firefly friend buzzes ahead, but a Firefly Phantom tries to copy its glow.",
    "Glowworms light up the mushrooms in soft green and blue. They whisper that Murkle's cauldron bubbles every night, deep in the marsh.",
    "A tall heron stands by a pool under an old tree. It points its long beak toward the deep part of the marsh. A Night Newt blocks the way.",
    "An old ferry boat waits by the reeds. You push off across the water, but a Bog Wisp swirls fog all around the boat.",
    "Fog covers the flats like a thick gray blanket. You follow the faint smell of bubbling soup. Two Mud Maulers stomp out of the mist.",
    "Giant mushrooms grow on a tiny island in the pool. In their shade, you find a strip of paper with a dream drawn on it: a flying fish!",
    "Two strange lanterns float in the air, glowing green. These are witch lights, and they mean her hut is close. A Firefly Phantom guards them.",
    "Under the moon, the trees in this hollow are all snoring softly. Shh! A Night Newt sneaks along a branch to wake them with a squeak.",
    "Reeds and bushes twist into a maze. Bog Wisps float through the walls, giggling, while you search for the right way out.",
    "Mossy stones poke out of the water like stepping stones. Jump from one to the next! A Mud Mauler splashes up to knock you in.",
    "Murkle's garden grows spotted mushrooms and flowers that sneeze. You hear her cauldron going blub, blub, blub, just past the gate.",
    "In her lantern-lit hut, Bog Witch Murkle stirs her bubbling cauldron. The Page of Dreams swirls inside! She cackles and raises her spoon. Spell to win it back!",
  ],
  // World 10
  [
    "The drawbridge groans as it lowers over the moat. The castle looms above you. A Gargoyle on the wall cracks open its stony eyes.",
    "Torn banners hang between tall columns in the great hall. It is so quiet you can hear your own heartbeat. A Shadow Knight steps forward.",
    "Candles flicker on every stair, lighting the way up. One candle floats off its step. It is a Candle Ghost, and it says 'Shhh!'",
    "Old shields and banners fill the armory. A Shadow Knight grabs one and blocks your path. Your words are your only tools here.",
    "A long table sits empty under glowing lanterns. Nobody has laughed here in years. Quill Bats flap down from the rafters, scratching ink everywhere.",
    "Wind whips across the roof between the towers. Stone Gargoyles line the edges, and one by one they start to turn their heads toward you.",
    "Tall columns cast long shadows by the torchlight. The shadows move on their own! A Shadow Knight slides out from behind a pillar.",
    "Behind a bookshelf, you find a secret library full of silent books. A note in one says, 'The Last Page is kept in my lair at the very top.'",
    "The throne room is empty. Grumblegloom is not here, but his cold footprints lead to a side door. A Gargoyle guards the throne.",
    "Torches flicker by a heavy dungeon door made of rock. Behind it, you hear whispers from words he has locked away. A Candle Ghost floats out.",
    "A narrow bridge crosses the dark moat inside the castle walls. Something ripples in the water. A Quill Bat dives down from above!",
    "A spiral stair winds up and up inside a tower. Torches light each turn. You count the steps as Candle Ghosts drift down to meet you.",
    "Rows of banners line the knight's hall. Two Shadow Knights stand at attention, then march toward you. Grumblegloom wants you stopped!",
    "Big bells hang in the chapel tower, tied tight so they can never ring. A Gargoyle sits on the biggest bell, guarding the silence.",
    "Paintings of Grumblegloom stare from every wall, each one frowning. In the last painting, he holds a glowing page. You are getting close!",
    "Piles of gold blocks fill the treasure room, but you came for something better than gold. A Quill Bat swoops out of a pile of coins.",
    "Up on the battlements, banners snap in the cold wind. You can see the whole land below. A Shadow Knight and a Gargoyle stand guard.",
    "Two towers twist up side by side. You climb from window to window as Quill Bats circle around you. Grumblegloom's grumbling echoes from above.",
    "The moon hangs huge over the highest tower. An old dragon's nest sits here, empty now. Candle Ghosts hush you one last time. Keep going!",
    "Torches flare in Grumblegloom's lair. He rises from his chair, holding the Last Page, and growls, 'No more noise!' This is it. Spell loud and proud!",
  ],
  // World 11
  [
    "A gate of giant gumdrops blocks the canyon path. A Gumdrop Goblin squeaks, \"Go away!\" It forgot how to say please. Spell your way past it!",
    "Lollipops as tall as trees line the lane. On the ground you spot a shiny pink wrapper with a crown printed on it. Queen Bonbon came this way!",
    "The path twists like stretchy taffy. A Taffy Troll stretches across the road and grumbles. Beat it, and maybe it will tell you where the Queen went.",
    "The Taffy Troll mumbled one word: river. A warm chocolate river flows by, and another pink wrapper floats past. Follow it downstream!",
    "Rainbow sprinkles cover this hill like tiny flowers. A Sprinkle Sprite zips around your head, tossing sprinkles in your eyes. Shoo it away with your spelling!",
    "A little cookie cottage sits at the bottom of the hill. The baker inside wants to thank you, but she can't find one kind word. The Queen took them all.",
    "The baker points to the striped peppermint mountains and whispers, \"Palace.\" Cold minty wind blows as you climb the rocky pass.",
    "At the top of the pass, fluffy cotton candy clouds float low. You hop from cloud to cloud and spot a far-off palace with lollipop towers.",
    "You slide down into a field of jellybeans as big as blocks. A Gumdrop Goblin pops out from behind a green one. It wants a rematch!",
    "Golden caramel pours over the rocks in a slow, sticky waterfall. Behind it you find a torn scrap of page with one sweet word still on it: thanks.",
    "A wobbly fudge bridge crosses the canyon. A Licorice Lurker hides underneath, waiting to tug at your boots. Spell fast and keep walking!",
    "Soft marshmallows bounce under your feet like pillows. A Sprinkle Sprite giggles and points toward a factory with puffing pipes. Could the chapter be there?",
    "Pipes hiss and candy rolls along moving belts. The workers here make treats all day but can't say \"great job\" to each other. Search the factory for clues!",
    "No chapter in the factory, but a worker drew you a map in icing. It leads down Gingerbread Row, where Taffy Trolls guard every door.",
    "Black licorice trees twist overhead, and the path gets darker. Licorice Lurkers drop from the branches. Stay brave and spell your way through the woods.",
    "Fizzy soda bubbles up from bright pools. Pop! A bubble bursts, and out floats a wrapper with a tiny crown. You are getting close to the Queen.",
    "Sparkly rock candy crystals hang from the cave roof. Deep inside, an echo drifts back to you: Queen Bonbon, humming as she reads your sweet words.",
    "Sugar plum trees glow outside the cave. The Gumdrop Goblin from the gate shows up again, and this time it brought friends. One more push!",
    "A striped tent sells every candy you can think of. The shopkeeper slips you a key shaped like a lollipop. \"For the palace door,\" she whispers.",
    "The lollipop key opens the palace door. Queen Bonbon sits on a candy throne, hugging the Chapter of Sweet Words. Spell your best to win it back!",
  ],
  // World 12
  [
    "Palm trees and vines wall off the jungle. A Vine Snapper wriggles out of the leaves and snaps at your feet. Spell hard to clear a path!",
    "The only way forward is through the treetops, so grab a vine and swing! On a tree trunk you spot a carving: a curly hook with a dot. A question mark!",
    "A bright parrot named Pip lands on your shoulder. Pip wants to ask your name but can't. Instead, Pip flaps toward the old ruins to show you the way.",
    "A rope bridge sways over a deep valley. Mischief Monkeys swing onto it, grabbing at your snacks and laughing. Spell them back into the trees!",
    "A cool waterfall splashes into a clear pool. Behind the falling water you find another carved question mark, pointing deeper into the jungle.",
    "Stone steps climb past tall tiki posts. Wait, one post just blinked! A Tiki Totem hops down and blocks the stairs. Show it what you can spell.",
    "Pip is hungry, so you rest in a grove of banana palms. A Mischief Monkey swipes Pip's banana and runs. Time to win it back!",
    "A mossy statue stands in the ferns, holding a stone tablet. The tablet shows a temple with a locked door. The chapter must be inside!",
    "Lily pads float across a quiet pond. Tiny Dart Frogs hop from pad to pad, puffing up and croaking. Hop across and spell your way past them.",
    "Vines hide a stone pyramid, half buried in the jungle. This is the temple! But the door has no handle, only a big carved question mark.",
    "Pip finds a rock shaped like a curled-up snake. Vine Snappers coil all around it. Maybe the snake rock knows how to open the temple.",
    "Huts sit high in the trees. The villagers can't ask what you need, so you tell them. An old woman smiles and points to a garden.",
    "Purple orchids bloom between the ferns. In the middle sits a golden petal with words on it: Find the totems. Count them all.",
    "Whoosh! The trail turns into a slippery mud slide. You zoom down into a muddy pool, and Dart Frogs splash all around you.",
    "Tall Tiki Totems stand in a ring. You count them: seven. Then every Tiki Totem wakes up at once, so spell carefully!",
    "Big paw prints lead through the ferns. Pip squawks seven times, like a secret code. The trail heads toward an old flooded plaza.",
    "Stone columns poke out of shallow water. Pip spots seven bumps on one column. You press them all, and a rope ladder drops from above!",
    "You climb the rope ladder up the vines. Mischief Monkeys swing by and try to shake it. Hold on tight and keep spelling!",
    "The ladder leads into the temple through a secret window. Torches light a hall of golden blocks. Heavy stone footsteps thump in the room ahead.",
    "In the heart of the temple, the stone Temple Guardian stands over the Chapter of Questions. It rumbles awake. Spell your best to unlock the chapter!",
  ],
  // World 13
  [
    "You land on a beach of soft black sand. Waves hiss on the warm rocks. A Lava Blob bubbles up from the sand and wobbles your way!",
    "A smoky trail winds up from the beach. A little lizard named Flicker peeks from behind a rock. Flicker is too scared to say hi, but follows you anyway.",
    "A river of glowing lava blocks the way. A stone bridge crosses it, but Ember Imps dance along the rails. Spell them out of your way!",
    "Tiny embers twinkle like fireflies across this field. You spot huge claw marks in the rock. Something big walked up the mountain.",
    "Shiny black crystal covers the cave walls. Flicker squeaks and points: a giant red scale lies on the floor. Cinderjaw must have passed by!",
    "You rest your feet in a warm spring. A Magma Crab scuttles out and pinches at your toes. Spell quickly and send it sideways!",
    "Gray trees stand in a cloud of ash. Ash Bats flutter out of the branches, squeaking and flapping. Wave them away with your spelling.",
    "Steam whistles out of pipes in the ground. Flicker finds a note stuck to one: Cinderjaw naps at the very top, right after lunch.",
    "A narrow bridge stretches over bubbling lava. Lava Blobs bob below, trying to splash you. Walk carefully and spell even more carefully.",
    "You reach the rim of an old crater. Far above, the real peak puffs smoke. You're halfway there! Ember Imps giggle and try to block the path.",
    "Orange magma bubbles in a wide pool. Magma Crabs ride the bubbles like little boats. Hop across the cool stones to the other side.",
    "Old burned columns stand around flickering torches. On one wall, a painting shows a drake hiding a golden book in its rocky nest.",
    "Tall stone columns rise like giant stairs. Flicker finally squeaks a tiny word: \"Up!\" Brave words are already coming back. Climb!",
    "Yellow pools bubble and smell like rotten eggs. Hold your nose! Ash Bats swoop low over the water, so spell fast.",
    "Whoosh! A tall plume of fire shoots out of the mountain. Lava Blobs come bouncing down the slope toward you. Stand strong and spell!",
    "Big old bones lie among the rocks, left from long, long ago. Flicker finds a path between the giant ribs that leads even higher.",
    "Lava glows in cracks along this tunnel, lighting up the stone icicles. Loud snoring echoes down from the top of the volcano.",
    "You step out onto a smoky cone near the very top. Ember Imps and Ash Bats team up for one last try to stop you.",
    "Lava pours over the rocks like a glowing waterfall. Behind it, you spy a nest of rocks and the corner of a golden book!",
    "Cinderjaw the Drake wakes up and huffs a big cloud of smoke. Flicker shouts, \"You can do it!\" Spell bravely to win back the Chapter of Brave Words!",
  ],
  // World 14
  [
    "The ticket booth speaker crackles the same tired joke: \"Knock knock. Who's there? Banana.\" Over and over. A Ticket Taker snatches your ticket. Spell to get it back!",
    "From the top of the Ferris wheel, you see the whole carnival. A giant striped tent stands in the middle, with a lock on its flap.",
    "The carousel horses spin round and round, but nobody smiles. A Carousel Critter jumps off its pole and gallops at you. Spell it back onto the ride!",
    "Popcorn pops, but nobody laughs. A Popcorn Ghost floats out of the machine, puffing buttery clouds. Spell it away before it hides your path!",
    "Balloons bob along the alley. Balloon Bugs nibble the strings so the balloons float off. One balloon has a note tied to it: Fortune Tent.",
    "Inside the funhouse, wavy mirrors make you tall, then short, then wiggly. It should be funny, but everyone is so quiet. Find the way out!",
    "Bump! Bump! Carousel Critters drive the bumper cars straight at you, honking their horns. Spell fast to steer clear of the crash.",
    "You toss a ring and win a prize: a tiny paper joke, torn in half. It's a piece of the missing chapter! The Ticket Takers want it back.",
    "Lanterns glow inside the fortune tent. The fortune teller peers into her crystal ball. \"The Ringmaster hides the laughs near the Big Top,\" she says.",
    "A juggler named Juno keeps dropping her pins. She can't think of a single joke for her show. She promises to help if you bring the laughs back.",
    "Every sound repeats in this hall. You say hello, and the walls say hello, hello, hello. Juno says the Ringmaster practices his speeches here.",
    "You reach the Big Top, but it's empty! There's only a note on the floor: \"Gone for a ride. Banana.\" The Ringmaster is somewhere in the park.",
    "Pink cotton candy swirls at the cart. Popcorn Ghosts drift over for a sweet snack. Spell them away, then grab a fluffy bite.",
    "Click, click, click, up the roller coaster track! From the top, you spot a tall top hat bobbing toward the prize booth. Hang on!",
    "Giant teddy bears line the prize booth. Behind them sits the other half of the torn joke. Put the two halves together. It's almost funny!",
    "Lanterns light the midway as night falls. Balloon Bugs swarm around the lights. Juno juggles to keep them busy while you spell.",
    "Ding! You ring the strongman bell so hard the whole carnival hears it. Ticket Takers come running. Spell your way through!",
    "The circus train toots past the fence. The Ringmaster's top hat pokes out of the last car's window. Jump on board!",
    "The train stops at the night parade under the moon. Floats roll by, glowing with lanterns, and the parade leads right to the center ring.",
    "Ringmaster Grin twirls his cane of streamers and tells his tired joke one more time. Spell your best and win back the Chapter of Jokes!",
  ],
  // World 15
  [
    "Your rocket roars off the launch pad and up past the tower. Out the window, a Star Sprite zooms right beside you, sticking out its tongue!",
    "You land at a quiet moon base. The people here just stare at the stars and shrug. Nobody wonders anymore. A Moon Mite hops out of a moon rock!",
    "Craters cover the ground like giant bowls. In one, you find nibble marks and sparkly crumbs. The Nebula Nibbler was snacking here!",
    "You hitch a ride on a comet's glowing tail. A Comet Kid surfs up next to you and wants to race. Spell fast to win!",
    "Rocks tumble all around you in the asteroid belt. More sparkly crumbs float between them, making a trail toward a faraway pink glow.",
    "Space flowers grow in tiny bubble domes. A gardener robot named Bolt can't even wonder how to fix his wobbly leg. You fix it, and he joins you!",
    "Bolt tunes a giant satellite dish. Crunch, munch, burp! The dish hears the Nibbler chewing somewhere deep inside a big pink cloud.",
    "Two planets glow overhead, one with shiny rings. Star Sprites zip around the rings like race cars. Spell them to a stop.",
    "Baby stars twinkle inside soft clouds and crystals. This is where new stars are born, but Moon Mites are nibbling the crystals. Shoo them away!",
    "Aliens sell space snacks from colorful tents. Zorb the Visitor says, \"Maybe I know where the pink cloud is. Beat me at spelling first!\"",
    "Whee! There's no gravity in this hall, so you float upside down. Zorb flips beside you and points the way: the Nebula Core.",
    "Meteors streak past like shooting stars. Bolt holds up a shield while Comet Kids zoom through the shower. Spell quickly and stay safe!",
    "You board a ship with big shiny sails that catch the sunlight. It glides past planets toward the pink cloud Bolt heard on the dish.",
    "The ship drops you on a small moon, and you hop into a bouncy rover. Moon Mites chase your wheels across the bumpy rocks.",
    "A bridge of starlight stretches between two planets. Zorb the Visitor waits in the middle for a rematch. Win, and Zorb lets you pass.",
    "Glowing crystals light a cave on the far planet. On the wall, someone scratched a map of the Nebula Core, with a big X in the middle.",
    "Rockets refuel at the robot docks. Bolt borrows a speedy ship, but Star Sprites jam the pipes. Spell them loose and climb aboard!",
    "Careful! You fly past the edge of a black hole, swirling like a bathtub drain. Bolt steers steady while Comet Kids try to bump your ship.",
    "The tall Starlight Tower beams light into the pink cloud. From the top, you can see the Nibbler's shadow, still chewing away inside.",
    "Inside the glowing nebula, the Nebula Nibbler munches on the Chapter of Wonders. Spell your best to make it give the chapter back!",
  ],
  // World 16
  [
    "The toy shop door creaks open with a jingle. On the floor lies a shiny wind-up key, dropped by Gizmo Rex. A Wind-Up Mouse zips out to grab it first!",
    "A wobbly block tower stands in your way. From the top you spot more wind-up keys leading deeper into town. A Box Jumper pops up, ready to knock it down!",
    "A toy train chugs in circles around a block fence, but it has forgotten how to pretend to go anywhere. Follow the train tracks and the trail of keys!",
    "The dollhouse family sits still, unable to play house without the Chapter of Make-Believe. A Rag Pup tumbles out the front door, wagging and nipping at your shoes.",
    "Marbles roll down a twisty run and across a little bridge. One marble has a key stuck to it, rolling the way Gizmo Rex went. Chase it!",
    "Puzzle Plaza is full of pieces that do not fit. Snap a few together, and they show a picture of a giant toybox. A Block Bot clanks over to stop you.",
    "Kites flap and tangle in Kite Corner, unable to pretend they are birds. High in the clouds, one kite string points toward the toybox. Wind-Up Mice scurry nearby!",
    "Spinning tops whirl so fast you feel dizzy. Every top spins toward the same spot, as if Gizmo Rex is pulling them. Hop over and keep going!",
    "Pots of bright paint bubble like little pools. Gizmo Rex stepped in one, and now his green footprints march right down the road. A Box Jumper springs out to block them!",
    "The teddy bears sit at an empty picnic, too sad to pretend to have tea. One bear points a fuzzy paw: Gizmo Rex stomped through here an hour ago.",
    "Robots stand in a long row, their gears stuck still. A Block Bot blinks awake and beeps loudly, trying to warn its master that you are coming.",
    "Rocking horses creak back and forth behind a ranch fence. Ride one past the tents, and you see green paint prints and a pile of wind-up keys ahead!",
    "Crayon Castle is drawn in every color, but its flags have no pictures left. A Rag Pup chews a crayon by the gate. Draw your way inside!",
    "Sticker Street is covered in stickers, and they all point one way, to the biggest toybox on the shelf. Grab a lollipop and follow them!",
    "Balloons tug at a toy ship at the dock. Climb aboard and float up over the town, and you spot Gizmo Rex's toybox glowing with the stolen chapter!",
    "A tall music box plays a slow, sleepy song. Gizmo Rex wound it up to make you yawn. Stay awake and spell to stop the music!",
    "Toy soldiers guard their fort, but they have forgotten how to march and play. A whole squad of Block Bots stands at the gate. Clank, clank, here they come!",
    "Bubbles float over a soapy bay like little clouds. Pop them all, and inside the last bubble you find a wind-up key bigger than you are. Gizmo Rex is close!",
    "The bedtime shelf is dim and quiet under a paper moon. You hear loud clicking and whirring from the toybox right next door. Tiptoe closer, Word Hero.",
    "The lid of the toybox flies open, and Gizmo Rex stomps out with the Chapter of Make-Believe in his metal claws! Wind him down with your best spelling!",
  ],
  // World 17
  [
    "Past the front door, a thousand of you wave back from the mirrors. One reflection points left, so you go right, because here, backwards is the way forward.",
    "The Shiny Hall sparkles so bright you have to squint. A Mirror Imp hops out of the glass, pulls a silly face, and dares you to catch it!",
    "In the Backwards Room, the signs read from right to left. Spell them the right way around, and one sign says: THRONE THIS WAY.",
    "Light bends through glass on the Prism Path and splits into colors. A Prism Bug buzzes in rainbow circles, trying to make you lose your way.",
    "Say hello in Echo Corner, and two voices say it back. That is an Echo Twin, copying everything you do! Do something it cannot copy: spell!",
    "The glass stairs go down when you climb up. Keep climbing anyway, and you reach a landing where a crown is painted on every mirror. The Looking-Glass Lord is near.",
    "Crystals spin around you like a giant kaleidoscope. When they stop, they make a picture of a book with one missing chapter. You are on the right track!",
    "In the Upside-Down Garden, the flowers grow down from the ceiling. A Mirror Imp swings from a stem, giggling. Keep your feet on the floor and your eyes on the words!",
    "The Silver Pool is smooth as glass. Your reflection in the water is holding the Chapter of Opposites! Then it ripples away. Was it a clue?",
    "Funny mirrors make you tall, then short, then wide as a door. Laugh it off! A Glass Golem stomps out, and it is not laughing.",
    "A bridge of sharp glass shards crosses a deep gap. Walk carefully. Prism Bugs flicker under it, flashing light in your eyes.",
    "The Rainbow Room glows red, orange, yellow, green and blue. In the purple corner, a mirror shows the Looking-Glass Lord turning the pages of your chapter!",
    "Two towers stand side by side, exactly the same. One is real and one is a reflection. Echo Twins guard both. Spell well to find the real way up!",
    "Trees made of glass chime in the breeze. Every leaf reflects the throne room, a little closer each time. A Glass Golem blocks the path.",
    "A beam of light shoots from a lantern and bounces off mirror after mirror. Follow the beam, and it leads straight toward the heart of the maze.",
    "The Crystal Lake is so still you can see the sky in it, upside down. Cross on the stepping crystals while a Mirror Imp splashes behind you.",
    "Fog covers the mirrors, and you cannot see a thing. Wipe the glass with your sleeve, and words appear: Only opposites may pass. Spell them out!",
    "This hall is full of lost reflections, people who looked away and left their mirror selves behind. They whisper that the Looking-Glass Lord is just ahead.",
    "Banners hang in the Hall of Kings, and mirrors show every king who ever ruled the maze. The last mirror shows an empty throne, waiting for you.",
    "The Looking-Glass Lord sits on his throne of mirrors and crystals, holding the Chapter of Opposites. He smiles backwards. Show him the right way to spell!",
  ],
  // World 18
  [
    "The garden gate is taller than a house, but you slip right under it. A flower stem as thick as a tree trunk sways overhead.",
    "Giant daisies tower over you like umbrellas. A ladybug the size of a car lands nearby and blinks at you. She seems friendly, and she wants to follow you.",
    "A dewdrop as big as a pool wobbles on a leaf. Peek inside and you see the Weed King's leafy crown far away. A Buzz Bee zooms down to chase you!",
    "A shiny snail trail stretches across the leaves. At the end of it is a Snail Tank, slow but very, very hard to move. Spell to push past it!",
    "A long leaf makes a bridge over a stream. A Beetle Brute stands in the middle, clacking its big jaws. Your ladybug friend buzzes to cheer you on.",
    "Tulips rise like tall towers. From the top of one, you see weeds growing thick in the far corner of the garden. That must be where the Weed King lives!",
    "The ground shakes, and dirt piles up into hills. A Mole Muncher pops up, sniffing the air. Hop from hill to hill before it digs under you!",
    "The bee hive hums like a busy town. Buzz Bees zip in and out with honey. One of them carries a torn scrap of paper. It smells like weeds!",
    "A watering can as big as a barn drips water into a pond below. Climb up the spout and ride the drips down to the next part of the garden.",
    "Pumpkins as big as houses fill the patch. Weeds have wrapped around them all, squeezing tight. The Weed King has been here. A Snail Tank creeps out from behind a vine!",
    "Sunflowers grow so tall they make a forest. Their big faces all turn away from the sun, toward the weedy corner. Even the flowers know where to go!",
    "A spider web stretches between two fence posts, shining with dew. Don't get stuck! Climb across the strands while a Buzz Bee zooms around you.",
    "Neat rows of carrots and beans line the path. A Mole Muncher has been nibbling the roots. Your ladybug friend points to a weed with a page scrap stuck on it!",
    "The seed shed door is open just a crack. Inside, bags of seeds are spilled everywhere. A Beetle Brute guards a pile labeled: For the Weed King.",
    "Clover leaves stretch out like soft green rugs. Find a four-leaf clover for luck. You will need it, because the weeds ahead are getting thicker.",
    "After the rain, a puddle has turned into a big lake. Hop across on lily pads while a Snail Tank slides slowly behind you.",
    "The rose bushes are full of sharp thorns, and the Weed King made them grow even sharper. Spell carefully to find a safe path through the petals.",
    "Compost Hill is a big, squishy pile with mushrooms on top. From up here you can see it: a bed of weeds with a leafy banner. The Weed King is home!",
    "Inside the warm greenhouse, plants press their leaves against the windows. They are scared of the Weed King. Your ladybug friend lands on your shoulder. Time to be brave!",
    "The Weed King rises from his bed of leaves, vines curling everywhere, holding the Chapter of Big Ideas. He is huge, but your big ideas are bigger!",
  ],
  // World 19
  [
    "Past the valley gate, huge ferns sway over your head. In the soft mud is a footprint as big as a bathtub. Rex Thunderfoot came this way!",
    "The Fern Forest is thick and green. Something rustles, and a Dino Pup bounces out, wagging its tail. It wants to play, so spell to calm it down!",
    "Big nests sit on Nest Hill, but the mama dinos look confused. Without the Chapter of Long Ago, they have forgotten their own stories. Let's help them remember.",
    "The tar pits bubble and pop, sticky and black. Step only on the rocks! Across the pits, more giant footprints head toward the smoky mountain.",
    "Old bones are piled high in the Bone Yard. A Raptor Runt darts between them, quick and sneaky. Can you spell faster than it can run?",
    "A clutch of eggs sits warm among the rocks. One egg cracks, and a baby dino peeks out and follows you like a little shadow. Now you have a buddy!",
    "From Volcano View, you can see the whole valley. Smoke puffs from the volcano, and on the rock at its base is a big, tall shape. That is Rex Thunderfoot!",
    "Dinos line up at a fence, waiting to cross. A Fern Stomper stomps in front of the gate and will not move. Show it how to share the road!",
    "Swamp Lake is foggy and full of tall reeds. Your baby dino buddy splashes happily. Something flaps overhead, a Pterror, swooping low over the water!",
    "High cliffs rise to the sky, and Pterrors circle the tops. Climb carefully. From the highest ledge, you spot a torn page caught on a branch!",
    "At the fossil dig, a ladder leads down into the dirt. Brush away the dust, and you find a fossil shaped like a book. The valley really did have a story!",
    "Gentle giant dinos munch flowers in Herd Meadow. They hum an old song, and the words say: Rex Thunderfoot sleeps on the Roar Rock. Thank you, herd!",
    "Raptor Runts run along the ridge in a pack, chirping and hopping. They want to stop you from getting any closer. Your dino buddy chirps right back!",
    "The footprints here are so big that rainwater fills them like little pools. Rex Thunderfoot must be close. Each step shakes the ground. Boom. Boom.",
    "Inside the Amber Cave, golden stones glow. Frozen in one is a tiny bug from long, long ago. The valley's past is coming back, one clue at a time.",
    "Torches light up old paintings on the cave walls. They show a giant dino stomping on a book. Rex Thunderfoot has the chapter under his foot!",
    "Long-necked dinos stretch over the lake to sip water. One lowers its neck like a bridge. Climb on and walk across to the other side!",
    "Thunder rumbles over the plains, but it is not the sky, it is a herd of Fern Stompers running your way! Spell fast to stop the stampede.",
    "The Stomping Grounds are flat and cracked from big, heavy feet. Your dino buddy hides behind you. Just ahead, the volcano glows and a mighty roar shakes the air.",
    "Rex Thunderfoot stands on Roar Rock, with the Chapter of Long Ago squashed under one giant foot. He lets out a huge ROAR! Spell your loudest words back!",
  ],
  // World 20
  [
    "The bottom step of the Silent Spire is cold and still. You carry nine Lost Chapters in your bag, and they glow softly, as if cheering you on.",
    "The Hush Gate is lit by torches with no crackle at all. A Hush Wraith floats out and whispers, Shhh. Spell a word and say it out loud!",
    "The Whisper Stairs wind up and up. Every step you take makes no sound. A Shush Hound sniffs at your heels, trying to sniff out your words.",
    "A whole library sits here, but every book is closed and silent. When you open one, the words have faded away. Grumblegloom is hungry for words!",
    "Shout into the Echo Pit, and nothing comes back. Grumblegloom has stolen even the echoes. A Mute Golem climbs out of the dark, slow and heavy.",
    "In the Gloom Garden, the flowers are gray under a pale moon. Gloom Moths flutter between the petals. Spell a bright word, and color blooms back!",
    "A bridge made of shadows stretches across the gap. The torches flicker. Your nine chapters glow brighter, lighting the way step by step.",
    "Thick banners hang in this hall, soaking up every sound. A Mute Golem guards the far door. Up above, you hear one faint sound: a grumble.",
    "Lanterns hang in the Moth Loft, and Gloom Moths crowd around them, eating the light. Shoo them away with your words so you can see the window!",
    "Hundreds of clocks fill this tower, but none of them tick. Grumblegloom has stopped time from making noise. Spell to start the gears turning again!",
    "Two bell towers stand side by side with bells that cannot ring. Hush Wraiths circle around them. Spell well, and the first bell goes DONG!",
    "Every lantern here is dim, about to go out. Light them one by one with your words. Each lantern shows a picture of a lost chapter you have won back.",
    "Ice covers this room, and inside the ice are frozen voices, words that were stolen long ago. Spell each one to melt it free!",
    "Mirrors and columns make a twisty maze, and the walls mumble mixed-up words. Shush Hounds hide around every corner. Spell clearly to find the way out!",
    "Out on the stormy balcony, wind whips the banners. Far below, you can see every world you have saved. Up above, a deep grumble rumbles in the clouds.",
    "The Grumble Vault is full of stolen sounds, locked in stone blocks. Break them open with your spelling, and laughter and songs spill out!",
    "The Lost Words Room is piled with books and glowing crystals. These are all the words Grumblegloom ever took. Gather them up; you will need them!",
    "The last staircase climbs toward the top of the tower. Hush Wraiths, Shush Hounds, Mute Golems and Gloom Moths all rush at you at once. This is it, Word Hero!",
    "The Silent Throne is empty, and the torch beside it has gone cold. A note on the seat says: Come to the top. Grumblegloom is waiting for you at the peak.",
    "At the Spire's Peak, under the moon, Grumblegloom Unbound rises huge and dark, holding the Last Chapter. Every word you have ever learned glows with you. Spell your best and win it back!",
  ],
];

export const levelStory = n => (LEVEL_STORIES[worldOf(n)] || [])[stepOf(n) - 1] || "";
