// =========================================================================
// Licenses.jsx
// =========================================================================
// Per-person CE + license + certification tracker.
//   - Admins (owner / manager) see everyone's licenses + full CRUD
//   - Team members see only their own rows and can mark-complete themselves
// Data lives in public.team_licenses; alerts get generated by the daily
// license-reminder-runner edge function. See migrations dated 2026-07-01.
// =========================================================================

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, AGENCY_ID } from "../lib/supabase.js";
import { T } from "../lib/theme.js";

// ─── constants ───────────────────────────────────────────

const ADMIN_ROLES = ["owner", "manager"];

const LICENSE_TYPES = [
  { value: "insurance_ce",                label: "Insurance CE" },
  { value: "annuities_ce",                label: "Annuities CE" },
  { value: "medicare_ce",                 label: "Medicare CE" },
  { value: "insurance_license",           label: "State Insurance License" },
  { value: "long_term_care",              label: "Long-Term Care Cert" },
  { value: "series_6_annual_compliance",  label: "Series 6 Annual Compliance" },
  { value: "series_6_regulatory_element", label: "Series 6 Regulatory Element" },
  { value: "chfc_ce",                     label: "ChFC/CLU CE" },
  { value: "chfc_recert_payment",         label: "ChFC/CLU Recert Payment" },
  { value: "mortgage_ce",                 label: "Mortgage NMLS CE" },
  { value: "mortgage_license",            label: "Mortgage NMLS License" },
  { value: "humana_recert",               label: "Humana Recertification" },
  { value: "us_bank_personal",            label: "US Bank Personal Compliance" },
  { value: "jackson_training",            label: "Jackson Product Training" },
  { value: "bcbs_cert",                   label: "BCBS Certification" },
  { value: "trupanion_cert",              label: "Trupanion Certification" },
  { value: "gainsco_cert",                label: "GAINSCO Training" },
];

const STATUS_OPTIONS = [
  { value: "active",           label: "Active" },
  { value: "complete_onetime", label: "Complete (one-time)" },
  { value: "lapsed",           label: "Lapsed" },
  { value: "not_applicable",   label: "Not Applicable" },
];

const CE_ROW_TYPES = new Set([
  "insurance_ce",
  "annuities_ce",
  "medicare_ce",
  "chfc_ce",
  "series_6_annual_compliance",
  "series_6_regulatory_element",
]);

// ─── date helpers (all in America/Chicago) ──────────────────────

function todayInCT() {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Chicago",
    year: "numeric", month: "2-digit", day: "2-digit",
  }).formatToParts(new Date());
  const y = parts.find(p => p.type === "year").value;
  const m = parts.find(p => p.type === "month").value;
  const d = parts.find(p => p.type === "day").value;
  return `${y}-${m}-${d}`;
}

function daysBetween(aISO, bISO) {
  const a = new Date(aISO + "T00:00:00Z").getTime();
  const b = new Date(bISO + "T00:00:00Z").getTime();
  return Math.round((b - a) / 86400000);
}

function humanDate(iso) {
  if (!iso) return "—";
  const [y, m, d] = iso.split("-").map(n => parseInt(n, 10));
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    year: "numeric", month: "short", day: "numeric", timeZone: "UTC",
  });
}

function typeLabel(v) {
  return LICENSE_TYPES.find(t => t.value === v)?.label || v;
}

// ─── status badge ──────────────────────────────────────────

function StatusBadge({ dueDate, status, ceRequired, isCeRow }) {
  if (status === "complete_onetime") {
    return <Pill bg={T.greenLt} color={T.slate800} text="Complete" />;
  }
  if (status === "not_applicable") {
    return <Pill bg={T.slate100} color={T.slate600} text="N/A" />;
  }
  if (status === "lapsed") {
    return <Pill bg={T.redLt} color="#991B1B" text="Lapsed" />;
  }
  if (isCeRow && ceRequired === false) {
    return <Pill bg={T.slate100} color={T.slate600} text="CE not required" />;
  }
  const today = todayInCT();
  const daysOut = daysBetween(today, dueDate);
  if (daysOut < 0) {
    return <Pill bg={T.redLt} color="#991B1B" text={`Past due ${Math.abs(daysOut)}d`} />;
  }
  if (daysOut === 0)  return <Pill bg={T.redLt}   color="#991B1B" text="Due today" />;
  if (daysOut <= 7)   return <Pill bg={T.redLt}   color="#991B1B" text={`${daysOut}d out`} />;
  if (daysOut <= 30)  return <Pill bg={T.amberLt} color="#92400E" text={`${daysOut}d out`} />;
  if (daysOut <= 90)  return <Pill bg={T.amberLt} color="#92400E" text={`${daysOut}d out`} />;
  return <Pill bg={T.slate100} color={T.slate700} text={`${daysOut}d out`} />;
}

function Pill({ bg, color, text }) {
  return (
    <span style={{
      display: "inline-block",
      padding: "3px 9px",
      borderRadius: 999,
      background: bg,
      color,
      fontSize: 11,
      fontWeight: 700,
      letterSpacing: "0.02em",
      whiteSpace: "nowrap",
    }}>{text}</span>
  );
}

// ─── main component ────────────────────────────────────────

export default function Licensing({ userRole, userId }) {
  const isAdmin = ADMIN_ROLES.includes(userRole);

  const [teamRows, setTeamRows]           = useState([]);
  const [licenses, setLicenses]           = useState([]);
  const [loading, setLoading]             = useState(true);
  const [error, setError]                 = useState("");
  const [myTeamMemberId, setMyTeamMemberId] = useState(null);

  const [filterPerson, setFilterPerson]   = useState("all");
  const [filterType, setFilterType]       = useState("all");
  const [filterStatus, setFilterStatus]   = useState("active");

  const [editingRow, setEditingRow]       = useState(null);
  const [completingRow, setCompletingRow] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const [teamRes, licensesRes] = await Promise.all([
        supabase
          .from("team")
          .select("id, first_name, last_name, is_active, user_id, email_personal, email_sf")
          .eq("agency_id", AGENCY_ID)
          .eq("is_active", true)
          .order("first_name"),
        supabase
          .from("team_licenses")
          .select("*")
          .eq("agency_id", AGENCY_ID)
          .order("due_date", { ascending: true }),
      ]);

      if (teamRes.error) throw teamRes.error;
      if (licensesRes.error) throw licensesRes.error;

      setTeamRows(teamRes.data || []);
      setLicenses(licensesRes.data || []);

      if (userId) {
        const mine = (teamRes.data || []).find(t => t.user_id === userId);
        setMyTeamMemberId(mine?.id || null);
      }
    } catch (e) {
      setError(e.message || "Failed to load licenses.");
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => { load(); }, [load]);

  const scoped = useMemo(() => {
    let out = licenses;
    if (!isAdmin) {
      out = out.filter(r => r.team_member_id === myTeamMemberId);
    }
    if (isAdmin && filterPerson !== "all") {
      out = out.filter(r => r.team_member_id === filterPerson);
    }
    if (filterType   !== "all") out = out.filter(r => r.license_type === filterType);
    if (filterStatus !== "all") out = out.filter(r => r.status === filterStatus);
    return out;
  }, [licenses, isAdmin, myTeamMemberId, filterPerson, filterType, filterStatus]);

  const memberById = useMemo(() => {
    const m = new Map();
    for (const t of teamRows) m.set(t.id, t);
    return m;
  }, [teamRows]);

  async function handleMarkComplete(rowId, completedOn) {
    setError("");
    try {
      const { error: rpcErr } = await supabase.rpc("mark_license_complete", {
        p_license_id:  rowId,
        p_completed_on: completedOn,
      });
      if (rpcErr) throw rpcErr;
      setCompletingRow(null);
      await load();
    } catch (e) {
      setError(e.message || "Failed to mark complete.");
    }
  }

  async function handleDelete(rowId) {
    if (!confirm("Delete this license? This cannot be undone.")) return;
    setError("");
    try {
      const { error: delErr } = await supabase
        .from("team_licenses")
        .delete()
        .eq("id", rowId);
      if (delErr) throw delErr;
      await load();
    } catch (e) {
      setError(e.message || "Failed to delete.");
    }
  }

  return (
    <div style={{ padding: 20, maxWidth: 1200, margin: "0 auto" }}>
      <div style={{ marginBottom: 18 }}>
        <div style={{ fontSize: 22, fontWeight: 800, color: T.slate900, letterSpacing: "-0.02em" }}>
          {isAdmin ? "CE & Licenses" : "My Licenses"}
        </div>
        <div style={{ fontSize: 13, color: T.slate500, marginTop: 4, lineHeight: 1.5 }}>
          {isAdmin
            ? "Continuing education, license licenses, and one-time certifications for the whole team. Reminders auto-send at 90 / 60 / 30 / 14 / 7 / 1 days out and daily past due."
            : "Your continuing education, license licenses, and certifications. Mark them complete here once you finish."}
        </div>
      </div>

      {error && (
        <div style={{
          padding: "10px 14px",
          background: T.redLt,
          border: `1px solid #FECACA`,
          borderRadius: 8,
          color: "#991B1B",
          fontSize: 13,
          marginBottom: 14,
        }}>{error}</div>
      )}

      <div style={{
        display: "flex",
        flexWrap: "wrap",
        gap: 10,
        alignItems: "center",
        marginBottom: 16,
      }}>
        {isAdmin && (
          <Select
            value={filterPerson}
            onChange={setFilterPerson}
            options={[
              { value: "all", label: "Everyone" },
              ...teamRows.map(t => ({
                value: t.id,
                label: `${t.first_name} ${t.last_name}`,
              })),
            ]}
          />
        )}
        <Select
          value={filterType}
          onChange={setFilterType}
          options={[{ value: "all", label: "All types" }, ...LICENSE_TYPES]}
        />
        <Select
          value={filterStatus}
          onChange={setFilterStatus}
          options={[{ value: "all", label: "All statuses" }, ...STATUS_OPTIONS]}
        />
        <div style={{ flex: 1 }} />
        {isAdmin && (
          <button
            onClick={() => setEditingRow({ __new: true })}
            style={btnPrimary}
          >
            + New License
          </button>
        )}
      </div>

      {loading ? (
        <div style={{ padding: 40, textAlign: "center", color: T.slate500, fontSize: 13 }}>
          Loading…
        </div>
      ) : scoped.length === 0 ? (
        <div style={{
          padding: 40, textAlign: "center", color: T.slate500,
          background: T.white, border: `1px solid ${T.slate200}`, borderRadius: 12,
          fontSize: 14,
        }}>
          No licenses match these filters.
          {isAdmin && filterStatus === "active" && (
            <div style={{ fontSize: 12, marginTop: 8, color: T.slate400 }}>
              Add a new license with the button above.
            </div>
          )}
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {scoped.map(r => (
            <LicenseCard
              key={r.id}
              row={r}
              member={memberById.get(r.team_member_id)}
              isAdmin={isAdmin}
              showPersonName={isAdmin}
              onMarkComplete={() => setCompletingRow(r)}
              onEdit={() => setEditingRow(r)}
              onDelete={() => handleDelete(r.id)}
            />
          ))}
        </div>
      )}

      {editingRow && (
        <EditLicenseModal
          row={editingRow}
          teamRows={teamRows}
          isAdmin={isAdmin}
          myTeamMemberId={myTeamMemberId}
          onClose={() => setEditingRow(null)}
          onSaved={async () => { setEditingRow(null); await load(); }}
        />
      )}
      {completingRow && (
        <MarkCompleteModal
          row={completingRow}
          member={memberById.get(completingRow.team_member_id)}
          onClose={() => setCompletingRow(null)}
          onConfirm={(dateStr) => handleMarkComplete(completingRow.id, dateStr)}
        />
      )}
    </div>
  );
}

function LicenseCard({ row, member, isAdmin, showPersonName, onMarkComplete, onEdit, onDelete }) {
  const isCeRow = CE_ROW_TYPES.has(row.license_type);
  const statesStr = (row.states && row.states.length > 0) ? row.states.join(", ") : null;
  const isOneTime = row.cycle_months === null || row.cycle_months === undefined;
  const canEdit = isAdmin || row.status === "active";
  const canMarkComplete = row.status === "active";

  return (
    <div style={{
      background: T.white,
      border: `1px solid ${T.slate200}`,
      borderRadius: 12,
      padding: "14px 16px",
      display: "flex",
      alignItems: "flex-start",
      gap: 14,
    }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "baseline", marginBottom: 6 }}>
          <div style={{ fontSize: 15, fontWeight: 700, color: T.slate900, letterSpacing: "-0.01em" }}>
            {typeLabel(row.license_type)}
          </div>
          {statesStr && (
            <span style={{ fontSize: 12, color: T.slate500 }}>
              ({statesStr})
            </span>
          )}
          {row.authority && (
            <span style={{ fontSize: 12, color: T.slate500 }}>
              · {row.authority}
            </span>
          )}
        </div>

        {showPersonName && member && (
          <div style={{ fontSize: 13, color: T.slate700, fontWeight: 600, marginBottom: 6 }}>
            {member.first_name} {member.last_name}
          </div>
        )}

        <div style={{ display: "flex", flexWrap: "wrap", gap: 14, alignItems: "center", fontSize: 12, color: T.slate600 }}>
          <span>
            <strong style={{ color: T.slate800 }}>Due:</strong> {humanDate(row.due_date)}
          </span>
          {row.hours_required != null && (
            <span>
              <strong style={{ color: T.slate800 }}>Hours:</strong> {row.hours_required}
            </span>
          )}
          {!isOneTime && (
            <span>
              <strong style={{ color: T.slate800 }}>Cycle:</strong> {row.cycle_months} mo
            </span>
          )}
          {row.last_completed_at && (
            <span>
              <strong style={{ color: T.slate800 }}>Last done:</strong> {humanDate(row.last_completed_at)}
            </span>
          )}
          {row.initial_issue_date && (
            <span>
              <strong style={{ color: T.slate800 }}>Issued:</strong> {humanDate(row.initial_issue_date)}
            </span>
          )}
        </div>

        {row.notes && (
          <div style={{
            marginTop: 8,
            fontSize: 12,
            color: T.slate600,
            lineHeight: 1.5,
            paddingLeft: 10,
            borderLeft: `3px solid ${T.slate200}`,
          }}>
            {row.notes}
          </div>
        )}

        {row.ce_breakdown && Object.keys(row.ce_breakdown).length > 0 && (
          <div style={{ fontSize: 11, color: T.slate500, marginTop: 6 }}>
            {Object.entries(row.ce_breakdown).map(([k, v]) => `${k.replace(/_/g, " ")}: ${v}h`).join(" · ")}
          </div>
        )}
      </div>

      <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8, flexShrink: 0 }}>
        <StatusBadge dueDate={row.due_date} status={row.status} ceRequired={row.ce_required} isCeRow={isCeRow} />
        <div style={{ display: "flex", gap: 6 }}>
          {canMarkComplete && (
            <button onClick={onMarkComplete} style={btnSuccess}>Mark Complete</button>
          )}
          {canEdit && (
            <button onClick={onEdit} style={btnGhost}>Edit</button>
          )}
          {isAdmin && (
            <button onClick={onDelete} style={btnGhostDanger}>Delete</button>
          )}
        </div>
      </div>
    </div>
  );
}

function MarkCompleteModal({ row, member, onClose, onConfirm }) {
  const [completedOn, setCompletedOn] = useState(todayInCT());
  const [saving, setSaving] = useState(false);
  const isOneTime = row.cycle_months === null || row.cycle_months === undefined;

  async function save() {
    setSaving(true);
    await onConfirm(completedOn);
    setSaving(false);
  }

  return (
    <ModalShell onClose={onClose} title="Mark License Complete">
      <div style={{ marginBottom: 12, fontSize: 13, color: T.slate700, lineHeight: 1.5 }}>
        <div style={{ marginBottom: 4 }}>
          <strong>{typeLabel(row.license_type)}</strong>
          {row.states && row.states.length > 0 && (
            <span style={{ color: T.slate500 }}> ({row.states.join(", ")})</span>
          )}
        </div>
        {member && (
          <div style={{ fontSize: 12, color: T.slate500 }}>
            {member.first_name} {member.last_name} · Was due {humanDate(row.due_date)}
          </div>
        )}
      </div>

      <label style={fieldLabel}>Date Completed</label>
      <input
        type="date"
        value={completedOn}
        onChange={(e) => setCompletedOn(e.target.value)}
        style={input}
      />

      <div style={{
        marginTop: 12,
        padding: "10px 12px",
        background: T.slate50,
        borderRadius: 8,
        fontSize: 12,
        color: T.slate600,
        lineHeight: 1.5,
      }}>
        {isOneTime ? (
          <>This is a one-time certification. Marking complete will archive it (no next cycle).</>
        ) : (
          <>Next due date will be automatically set to <strong>
            {row.cycle_months} months</strong> after {humanDate(completedOn)}.
          </>
        )}
      </div>

      <ModalActions
        onCancel={onClose}
        onConfirm={save}
        confirmLabel={saving ? "Saving…" : "Mark Complete"}
        disabled={saving}
      />
    </ModalShell>
  );
}

function EditLicenseModal({ row, teamRows, isAdmin, myTeamMemberId, onClose, onSaved }) {
  const isNew = !!row.__new;
  const [form, setForm] = useState(() => ({
    team_member_id:     isNew ? (isAdmin ? (teamRows[0]?.id || "") : (myTeamMemberId || "")) : row.team_member_id,
    license_type:       isNew ? "insurance_ce" : row.license_type,
    authority:          isNew ? "" : (row.authority || ""),
    states:             isNew ? "" : (row.states || []).join(", "),
    due_date:           isNew ? todayInCT() : row.due_date,
    cycle_months:       isNew ? 24 : (row.cycle_months ?? ""),
    initial_issue_date: isNew ? "" : (row.initial_issue_date || ""),
    status:             isNew ? "active" : row.status,
    ce_required:        isNew ? true : (row.ce_required !== false),
    hours_required:     isNew ? "" : (row.hours_required ?? ""),
    notes:              isNew ? "" : (row.notes || ""),
    source_url:         isNew ? "" : (row.source_url || ""),
  }));
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState("");

  const update = (k) => (e) => setForm(s => ({ ...s, [k]: e.target.value }));
  const updateBool = (k) => (e) => setForm(s => ({ ...s, [k]: e.target.checked }));

  async function save() {
    setSaving(true);
    setErr("");
    try {
      const payload = {
        team_member_id:     form.team_member_id,
        license_type:       form.license_type,
        authority:          form.authority || null,
        states:             form.states
                              ? form.states.split(",").map(s => s.trim().toUpperCase()).filter(Boolean)
                              : [],
        due_date:           form.due_date,
        cycle_months:       form.cycle_months === "" ? null : parseInt(form.cycle_months, 10),
        initial_issue_date: form.initial_issue_date || null,
        status:             form.status,
        ce_required:        form.ce_required,
        hours_required:     form.hours_required === "" ? null : parseInt(form.hours_required, 10),
        notes:              form.notes || null,
        source_url:         form.source_url || null,
      };

      if (!isAdmin) {
        payload.team_member_id = myTeamMemberId;
      }

      let result;
      if (isNew) {
        result = await supabase.from("team_licenses").insert({
          agency_id: AGENCY_ID,
          ...payload,
        });
      } else {
        result = await supabase.from("team_licenses").update(payload).eq("id", row.id);
      }
      if (result.error) throw result.error;
      await onSaved();
    } catch (e) {
      setErr(e.message || "Save failed.");
      setSaving(false);
    }
  }

  const isCeRow = CE_ROW_TYPES.has(form.license_type);

  return (
    <ModalShell onClose={onClose} title={isNew ? "New License" : "Edit License"}>
      {err && (
        <div style={{
          padding: "8px 12px", background: T.redLt, border: `1px solid #FECACA`,
          borderRadius: 6, color: "#991B1B", fontSize: 12, marginBottom: 10,
        }}>{err}</div>
      )}

      <div style={twoCol}>
        <div>
          <label style={fieldLabel}>Team Member</label>
          <select
            value={form.team_member_id}
            onChange={update("team_member_id")}
            style={input}
            disabled={!isAdmin}
          >
            {teamRows.map(t => (
              <option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>
            ))}
          </select>
        </div>

        <div>
          <label style={fieldLabel}>License Type</label>
          <select value={form.license_type} onChange={update("license_type")} style={input}>
            {LICENSE_TYPES.map(t => (
              <option key={t.value} value={t.value}>{t.label}</option>
            ))}
          </select>
        </div>

        <div>
          <label style={fieldLabel}>Authority</label>
          <input
            type="text"
            value={form.authority}
            onChange={update("authority")}
            placeholder="e.g. TDI, FINRA, Humana"
            style={input}
          />
        </div>

        <div>
          <label style={fieldLabel}>States (comma-separated)</label>
          <input
            type="text"
            value={form.states}
            onChange={update("states")}
            placeholder="TX, LA, OK"
            style={input}
          />
        </div>

        <div>
          <label style={fieldLabel}>Due Date</label>
          <input type="date" value={form.due_date} onChange={update("due_date")} style={input} />
        </div>

        <div>
          <label style={fieldLabel}>Cycle (months, blank for one-time)</label>
          <input
            type="number"
            value={form.cycle_months}
            onChange={update("cycle_months")}
            placeholder="24"
            style={input}
          />
        </div>

        <div>
          <label style={fieldLabel}>Initial Issue Date</label>
          <input
            type="date"
            value={form.initial_issue_date}
            onChange={update("initial_issue_date")}
            style={input}
          />
        </div>

        <div>
          <label style={fieldLabel}>Status</label>
          <select value={form.status} onChange={update("status")} style={input} disabled={!isAdmin}>
            {STATUS_OPTIONS.map(s => (
              <option key={s.value} value={s.value}>{s.label}</option>
            ))}
          </select>
        </div>

        {isCeRow && (
          <>
            <div>
              <label style={fieldLabel}>Hours Required</label>
              <input
                type="number"
                value={form.hours_required}
                onChange={update("hours_required")}
                placeholder="24"
                style={input}
              />
            </div>

            <div>
              <label style={fieldLabel}>&nbsp;</label>
              <label style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 13, color: T.slate700, padding: "8px 0" }}>
                <input
                  type="checkbox"
                  checked={form.ce_required}
                  onChange={updateBool("ce_required")}
                />
                CE required this cycle
              </label>
            </div>
          </>
        )}

        <div style={{ gridColumn: "1 / -1" }}>
          <label style={fieldLabel}>Source URL</label>
          <input
            type="url"
            value={form.source_url}
            onChange={update("source_url")}
            placeholder="https://…"
            style={input}
          />
        </div>

        <div style={{ gridColumn: "1 / -1" }}>
          <label style={fieldLabel}>Notes</label>
          <textarea
            value={form.notes}
            onChange={update("notes")}
            rows={3}
            style={{ ...input, resize: "vertical", minHeight: 60 }}
          />
        </div>
      </div>

      <ModalActions
        onCancel={onClose}
        onConfirm={save}
        confirmLabel={saving ? "Saving…" : (isNew ? "Create" : "Save")}
        disabled={saving}
      />
    </ModalShell>
  );
}

function ModalShell({ title, onClose, children }) {
  return (
    <div
      onClick={onClose}
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.5)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
        padding: 20,
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: T.white,
          borderRadius: 14,
          padding: 22,
          width: "100%",
          maxWidth: 640,
          maxHeight: "90vh",
          overflowY: "auto",
          boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
        }}
      >
        <div style={{
          fontSize: 18, fontWeight: 800, color: T.slate900,
          marginBottom: 14, letterSpacing: "-0.01em",
        }}>
          {title}
        </div>
        {children}
      </div>
    </div>
  );
}

function ModalActions({ onCancel, onConfirm, confirmLabel, disabled }) {
  return (
    <div style={{ marginTop: 16, display: "flex", justifyContent: "flex-end", gap: 8 }}>
      <button onClick={onCancel} style={btnGhost}>Cancel</button>
      <button onClick={onConfirm} disabled={disabled} style={btnPrimary}>{confirmLabel}</button>
    </div>
  );
}

function Select({ value, onChange, options }) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      style={{
        padding: "7px 10px",
        border: `1px solid ${T.slate200}`,
        borderRadius: 8,
        fontSize: 13,
        color: T.slate900,
        background: T.white,
        outline: "none",
      }}
    >
      {options.map(o => (
        <option key={o.value} value={o.value}>{o.label}</option>
      ))}
    </select>
  );
}

const btnBase = {
  padding: "7px 12px",
  fontSize: 12,
  fontWeight: 700,
  borderRadius: 8,
  border: "1px solid transparent",
  cursor: "pointer",
  letterSpacing: "0.01em",
};

const btnPrimary = {
  ...btnBase,
  background: T.blue,
  color: T.white,
};

const btnSuccess = {
  ...btnBase,
  background: T.green,
  color: T.white,
};

const btnGhost = {
  ...btnBase,
  background: T.white,
  color: T.slate700,
  border: `1px solid ${T.slate200}`,
};

const btnGhostDanger = {
  ...btnBase,
  background: T.white,
  color: "#991B1B",
  border: `1px solid ${T.slate200}`,
};

const input = {
  width: "100%",
  boxSizing: "border-box",
  padding: "8px 10px",
  fontSize: 13,
  color: T.slate900,
  border: `1px solid ${T.slate200}`,
  borderRadius: 8,
  outline: "none",
  background: T.white,
};

const fieldLabel = {
  display: "block",
  fontSize: 11,
  fontWeight: 600,
  color: T.slate700,
  marginBottom: 4,
  letterSpacing: "0.01em",
};

const twoCol = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: "12px 14px",
};
