-- 8 custom archetypes formalized into hiregauge_rules
INSERT INTO public.hiregauge_rules (
  agency_id, rule_type, rule_name, short_label,
  trait_signature_readable, description,
  verdict_impact, calibration_status, supporting_candidates, n_count,
  real_world_validated, is_active
) VALUES
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Unconscious Self-Promoter', 'UnconsciousSP',
 'DM 70+ AND RD 80+ + IS floor (<25) + Analytical floor (<25) + Reliability moderate-or-lower',
 'Recognition-hungry deadline-driven producer with no analytical governor and no self-directed persistence. Chargeback risk.',
 'soft_decline', 'emerging_n1', '["Bob Williams"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Externally-Fed Optimist', 'ExtFed-Opt',
 'RD 85+ AND SP 85+ AND OP 85+ + BO floor OR AS floor + Analytical low-moderate + Reliability high',
 'Recognition-hungry optimist needs external feed. Best in warm-inbound seats with constant recognition.',
 'soft_hire', 'emerging_n1', '["Braden King"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Bright Insubordinate', 'BrightInsub',
 'Analytical 90+ AND (2+ of SP/BO/OP at 90+) + IS floor (<25) + AS moderate-high',
 'Bright warm surface, chafes at authority-deference. Won''t sustain sustained deference.',
 'soft_decline', 'emerging_n1', '["William Shue"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Trusting-Autonomous', 'Trusting-Auto',
 'IS ceiling (90+) AND BO ceiling (90+) AND OP ceiling (90+) + Compassion floor (<25) + Analytical floor + RD floor',
 'Self-directed, trusts customers, optimistic — not warm. Fits retention_escalation.',
 'soft_hire', 'emerging_n1', '["John Kostov"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Quietly-Competitive Analyst-adjacent', 'QC-Analyst',
 'Analytical 80+ AND DM 60+ AND AS 60+ AND IS 60+ + RD floor (<25) + SP floor (<25) + Compassion floor (<25)',
 'Analytical closer with quiet-competitive money+win motivator. Fits outbound and cross-sell with scripts.',
 'soft_hire', 'emerging_n1', '["Thomas Lynch"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Balanced Rockstar', 'BalRockstar',
 'No trait floors + majority of traits 50+ + BO 75+ + OP 75+ + IS moderate-low (25-50)',
 'Solid across-the-board profile with team-environment needs. Fits sales_inbound or sales_in_book team seats.',
 'soft_hire', 'emerging_n1', '["Christian Kallas"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'Loud-Warm with Trust Floor', 'LoudWarm-TF',
 'AS 90+ AND IS 80+ AND RD 80+ AND Compassion 80+ + BO floor (<40) + DM moderate-low',
 'Rockstar-shape but trust floor makes them transactional. Fits acquisition with structure.',
 'soft_hire', 'emerging_n1', '["Anthony Vela"]'::jsonb, 1, true, true),
('126794dd-25ff-47d2-a436-724499733365', 'archetype', 'High-Distortion Producer', 'HighDist-Prod',
 'DM 90+ AND AS 90+ AND IS 90+ + BO floor OR SP floor + Response Distortion moderate-or-elevated',
 'Extreme producer with concerning distortion elevation. High output + elevated chargeback risk.',
 'soft_hire', 'emerging_n1', '["Aziel Rubero"]'::jsonb, 1, true, true);
