-- Mirrored 2026-08-13 during the un-mirrored-migration audit.
-- This migration was applied live on 2026-08-01 01:11:40 UTC (ledger name: v2_assessment_trait_documentation) but was never
-- committed to this repo at the time. Content below is copied verbatim
-- from supabase_migrations.schema_migrations.statements for version 20260801011140.
-- No live change is made by adding this file — it only brings the repo
-- mirror into sync with what is already running in production, so a
-- fresh `supabase db reset` from this repo reproduces live state.
-- v2 assessment: hiregauge_trait_documentation rows for the 21 new v2 facets
-- Assertiveness + Compassion already documented under v1 (same label/construct — reused)

INSERT INTO public.hiregauge_trait_documentation
  (agency_id, trait_name, strategic_label, psychometric_construct, ipip_facet, interpretation_warning, construct_notes, match_status)
VALUES
  ('126794dd-25ff-47d2-a436-724499733365', 'achievement_striving', 'Achievement Striving',
   'Achievement Striving', 'Conscientiousness / Achievement Striving',
   '',
   'IPIP Achievement Striving facet, 10 items. v2 only. Drives goal-directed persistence and ambition.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'self_discipline', 'Self-Discipline',
   'Self-Discipline', 'Conscientiousness / Self-Discipline',
   '',
   'IPIP Self-Discipline facet, 10 items. v2 only. Persistence with tedious or difficult tasks.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'emotional_stability', 'Emotional Stability',
   'Emotional Stability / low Neuroticism', 'Neuroticism (reversed)',
   'Under Path A rename doctrine, this label directly describes what its 12 items measure. Existing v1 "optimism" column continues to hold v1-scored Neuroticism-reversed values under the prior label.',
   'IPIP Neuroticism (reversed), 12 items. v2 only. Higher = more stable/less prone to negative affect. Peter renamed from "optimism" during 2026-07-31 Path A audit.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'perseverance', 'Perseverance',
   'Perseverance / Grit-analog', 'IPIP Perseverance',
   'Chosen instead of Duckworth Grit Scale which is explicitly rejected for hiring use (see operational_rule "Grit Scale (Duckworth) — REJECTED for hiring use").',
   'IPIP Perseverance, 10 items. v2 only. Public-domain research-clean analog to grit.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'dutifulness', 'Dutifulness',
   'Dutifulness / Conscientious rule-following', 'Conscientiousness / Dutifulness',
   '',
   'IPIP Dutifulness facet, 10 items. v2 only. Adherence to obligations, promises, expectations.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'customer_orientation', 'Customer Orientation',
   'Customer Orientation', 'Non-IPIP / Brown, Mowen, Donavan & Licata 2002',
   '',
   'Customer Orientation Scale (Brown et al. 2002), 12 items = 6 Needs-focused subscale + 6 Enjoyment-focused subscale. v2 only. Scored as unit-weighted composite for hiring (subscale reporting kept as diagnostic).',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'self_efficacy', 'Self-Efficacy',
   'General Self-Efficacy', 'Non-IPIP / Schwarzer & Jerusalem GSE 1995',
   '',
   'General Self-Efficacy Scale (Schwarzer & Jerusalem 1995), 10 items. v2 only. Perceived competence to handle novel or challenging situations.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'proactive_personality', 'Proactive Personality',
   'Proactive Personality', 'Non-IPIP / Seibert, Kraimer & Crant 2001',
   '',
   'Proactive Personality Scale (Seibert et al. 2001), 10 items. v2 only. Disposition toward identifying opportunities and taking action.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'cautiousness', 'Cautiousness',
   'Cautiousness / Deliberation', 'Conscientiousness / Cautiousness',
   '',
   'IPIP Cautiousness facet, 10 items. v2 only. Think-before-act tendency, risk-averse deliberation.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'anxiety', 'Anxiety',
   'Anxiety', 'Neuroticism / Anxiety',
   'This facet is scored as-measured (higher = more anxious). NOT reverse-scored into "calm." Used as diagnostic AND in expansion triggers.',
   'IPIP Anxiety facet, 10 items. v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'friendliness', 'Friendliness',
   'Friendliness / Warmth', 'Extraversion / Friendliness',
   '',
   'IPIP Friendliness facet, 10 items. v2 only. Warmth toward others, ease in social interaction.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'anger', 'Anger',
   'Anger / Frustration reactivity', 'Neuroticism / Anger',
   'Scored as-measured (higher = more anger-reactive). NOT reverse-scored.',
   'IPIP Anger facet, 10 items. v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'cooperation', 'Cooperation',
   'Cooperation', 'Agreeableness / Cooperation',
   '',
   'IPIP Cooperation facet, 10 items. v2 only. Preference for collaborative over adversarial responses.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'trust', 'Trust',
   'Trust', 'Agreeableness / Trust',
   'Under Path A rename doctrine, this label directly describes what its 11 items measure. Existing v1 "belief_in_others" column continues to hold v1-scored Trust values under the prior label.',
   'IPIP Trust facet, 11 items. v2 only. Peter renamed from "belief_in_others" during 2026-07-31 Path A audit.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'assured_dominance', 'Assured Dominance',
   'Assured Dominance / Social Confidence', 'Extraversion / Assured Dominance',
   'Distinct from "assertiveness" (broader) — assured dominance is confidence in leadership positioning specifically.',
   'IPIP Assured Dominance facet, 10 items. v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'dispositional_optimism', 'Dispositional Optimism',
   'Dispositional Optimism', 'Non-IPIP / Scheier, Carver & Bridges 1994 LOT-R',
   'Distinct from Emotional Stability. LOT-R measures generalized positive expectancy about the future, not neuroticism-reversed. Published LOT-R has 6 scored items + 4 filler items that are NOT scored.',
   'LOT-R (Scheier, Carver & Bridges 1994), 6 scored items. v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'political_skill_networking', 'Political Skill (Networking)',
   'Political Skill / Networking Ability', 'Non-IPIP / Ferris PSI 2005 Networking subscale',
   'Only the Networking Ability subscale is used, not full PSI (18 items across 4 subscales).',
   'Political Skill Inventory Networking Ability subscale (Ferris et al. 2005), 6 items. v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'enterprising', 'Enterprising',
   'Enterprising Interest', 'Non-IPIP / Holland RIASEC / O*NET Interest Profiler',
   'Interest measure, not personality. Distinct from Achievement Striving (personality) in that Enterprising captures preference for leadership/persuasion/business activities specifically.',
   'Holland RIASEC Enterprising type, sourced from O*NET Interest Profiler public bank. 8 items. v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'sincerity', 'Sincerity',
   'Sincerity (Honesty-Humility)', 'IPIP-HEXACO Sincerity',
   'One of three Honesty-Humility facets used as integrity floor gate in Stint 1 exit. Composite of Sincerity + Fairness + Greed-Avoidance below role threshold = integrity floor fail.',
   'IPIP-HEXACO Sincerity facet (Ashton, Lee & Goldberg 2007 Table 3, 8 highest-loading items). v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'fairness', 'Fairness',
   'Fairness (Honesty-Humility)', 'IPIP-HEXACO Fairness',
   'Second of three Honesty-Humility facets used as integrity floor gate.',
   'IPIP-HEXACO Fairness facet (Ashton, Lee & Goldberg 2007 Table 3, 8 highest-loading items). v2 only.',
   'match'),
  ('126794dd-25ff-47d2-a436-724499733365', 'greed_avoidance', 'Greed-Avoidance',
   'Greed-Avoidance (Honesty-Humility)', 'IPIP-HEXACO Greed-Avoidance',
   'Third of three Honesty-Humility facets used as integrity floor gate.',
   'IPIP-HEXACO Greed-Avoidance facet (Ashton, Lee & Goldberg 2007 Table 3, 8 highest-loading items). v2 only.',
   'match');
