INSERT INTO public.hiregauge_instrument_items
  (section, item_number, item_text, choices, answer_key, is_nonsense, retest_of_item_number, hypothesized_trait, reverse_coded, notes, scale_max, stint, is_active)
VALUES
  ('newtworks_v2_personality', 376, 'I am willing to select a challenging work assignment that I can learn a lot from.', NULL, NULL, false, NULL, 'learning_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Learning goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 377, 'I often look for opportunities to develop new skills and knowledge.', NULL, NULL, false, NULL, 'learning_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Learning goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 378, 'I enjoy challenging and difficult tasks at work where I''ll learn new skills.', NULL, NULL, false, NULL, 'learning_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Learning goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 379, 'For me, development of my work ability is important enough to take risks.', NULL, NULL, false, NULL, 'learning_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Learning goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 380, 'I prefer to work in situations that require a high level of ability and talent.', NULL, NULL, false, NULL, 'learning_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Learning goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 381, 'I''m concerned with showing that I can perform better than my coworkers.', NULL, NULL, false, NULL, 'prove_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Prove (performance-prove) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 382, 'I try to figure out what it takes to prove my ability to others at work.', NULL, NULL, false, NULL, 'prove_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Prove (performance-prove) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 383, 'I enjoy it when others at work are aware of how well I''m doing.', NULL, NULL, false, NULL, 'prove_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Prove (performance-prove) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 384, 'I prefer to work on projects where I can prove my ability to others.', NULL, NULL, false, NULL, 'prove_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Prove (performance-prove) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 385, 'I would avoid taking on a new task if there was a chance that I would appear rather incompetent to others.', NULL, NULL, false, NULL, 'avoid_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Avoid (performance-avoid) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 386, 'Avoiding a show of low ability is more important to me than learning a new skill.', NULL, NULL, false, NULL, 'avoid_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Avoid (performance-avoid) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 387, 'I''m concerned about taking on a task at work if my performance would reveal that I had low ability.', NULL, NULL, false, NULL, 'avoid_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Avoid (performance-avoid) goal orientation subscale, published item.', 6, 2, true),
  ('newtworks_v2_personality', 388, 'I prefer to avoid situations at work where I might perform poorly.', NULL, NULL, false, NULL, 'avoid_goal_orientation', false, 'VandeWalle 1997, Educational and Psychological Measurement 57(6) 995-1015. Avoid (performance-avoid) goal orientation subscale, published item.', 6, 2, true);
