-- v2 assessment: Customer Orientation (SOCO scale) 24-item ingest into newtworks_v2_personality
-- SOURCE SUBSTITUTION: Brown, Mowen, Donavan & Licata (2002) JMR 39(1):110-119 has no publicly
--   verifiable item text (paywalled, not reproduced in any accessible secondary source found).
--   Replaced with the original, canonical, most-cited instrument in this construct area:
-- Saxe, R., & Weitz, B. A. (1982). The SOCO scale: A measure of the customer orientation of
--   salespeople. Journal of Marketing Research, 19(3), 343-351.
-- Item text verified verbatim via full-text reprint in:
-- Michaels, R. E., & Day, R. L. (1985). Measuring customer orientation of salespeople: A
--   replication with industrial buyers. Journal of Marketing Research, 22(4), 443-446.
--   (Appendix reproduces all 24 original SOCO items in full, with reverse-coding notation.)
-- ADAPTATION: Michaels & Day's appendix rephrases each item from the original 1982 self-report
--   ("I" statements) into buyer-report third person ("salespeople...") for their replication.
--   Items below are converted BACK to first-person self-report phrasing to match the original
--   Saxe & Weitz self-administration format and this assessment's self-report design. Content
--   and reverse-keying are unchanged from the verified source; only grammatical person differs.
-- Response format: original 9-point proportion scale (1=True for NONE of my customers,
--   9=True for ALL of my customers) — preserved per source rather than converted to a 5-point
--   agreement scale, per op-rule "never prefer simpler over more accurate."
-- 13 items customer-oriented (+keyed), 11 items sales-pressure (reverse-scored).
-- Original scale factors into two dimensions (CO ~13 items, SO ~11 items) per Michaels & Day
--   factor loading table — noted for future subscale-display work (see OQ 113ab4a3, applicable
--   pattern even though original OQ referenced the now-superseded Brown 2002 source).
-- v2 item numbers 85-108, Stint 2, scale_max=9 (fourth distinct scale value in this section).

INSERT INTO public.hiregauge_instrument_items (
  section, item_number, hypothesized_trait, item_text, reverse_coded, scale_max, stint, choices, notes
) VALUES
('newtworks_v2_personality', 85, 'customer_orientation', 'I give an accurate representation of what my product will do for the customer.',                        false, 9, 2, NULL, 'SOCO item 1. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 86, 'customer_orientation', 'I try to get the customer to discuss their needs with me.',                                            false, 9, 2, NULL, 'SOCO item 2. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 87, 'customer_orientation', 'I apply selling pressure even when I know the product isn''t right for the customer.',                  true,  9, 2, NULL, 'SOCO item 3 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 88, 'customer_orientation', 'I imply that things are beyond my control when they really are not.',                                   true,  9, 2, NULL, 'SOCO item 4 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 89, 'customer_orientation', 'I try to influence a customer through information rather than pressure.',                              false, 9, 2, NULL, 'SOCO item 5. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 90, 'customer_orientation', 'I am a customer-oriented salesperson.',                                                                  false, 9, 2, NULL, 'SOCO item 6 (global self-rating item, part of original 24). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 91, 'customer_orientation', 'I spend more time trying to persuade a customer than I do trying to discover their needs.',             true,  9, 2, NULL, 'SOCO item 7 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 92, 'customer_orientation', 'I try to help customers achieve their goals.',                                                           false, 9, 2, NULL, 'SOCO item 8. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 93, 'customer_orientation', 'I answer customers'' questions about my products as honestly as I can.',                                false, 9, 2, NULL, 'SOCO item 9. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 94, 'customer_orientation', 'I agree with a customer just to please them.',                                                           true,  9, 2, NULL, 'SOCO item 10 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 95, 'customer_orientation', 'I treat a customer as an opponent.',                                                                     true,  9, 2, NULL, 'SOCO item 11 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 96, 'customer_orientation', 'I try to figure out what a customer''s needs are.',                                                     false, 9, 2, NULL, 'SOCO item 12. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 97, 'customer_orientation', 'I have the customer''s best interests in mind.',                                                       false, 9, 2, NULL, 'SOCO item 13. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 98, 'customer_orientation', 'I take a problem-solving approach in selling to a customer.',                                          false, 9, 2, NULL, 'SOCO item 14. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 99, 'customer_orientation', 'I am willing to disagree with a customer to help them make a better purchase decision.',                false, 9, 2, NULL, 'SOCO item 15. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 100, 'customer_orientation', 'I recommend the product best suited to solving a customer''s problem.',                                false, 9, 2, NULL, 'SOCO item 16. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 101, 'customer_orientation', 'I stretch the truth when describing my products.',                                                     true,  9, 2, NULL, 'SOCO item 17 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 102, 'customer_orientation', 'I talk first and listen to a customer''s needs later.',                                                true,  9, 2, NULL, 'SOCO item 18 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 103, 'customer_orientation', 'I try to convince a customer to buy more than they need.',                                             true,  9, 2, NULL, 'SOCO item 19 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 104, 'customer_orientation', 'I paint an overly rosy picture of my products to make them sound as good as possible.',                true,  9, 2, NULL, 'SOCO item 20 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 105, 'customer_orientation', 'I try to provide for the customer''s satisfaction.',                                                   false, 9, 2, NULL, 'SOCO item 21. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 106, 'customer_orientation', 'I make recommendations based on what I think I can sell, not on the customer''s long-term satisfaction.', true, 9, 2, NULL, 'SOCO item 22 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.'),
('newtworks_v2_personality', 107, 'customer_orientation', 'I try to find out which products would be most helpful to a customer.',                               false, 9, 2, NULL, 'SOCO item 23. Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, +keyed.'),
('newtworks_v2_personality', 108, 'customer_orientation', 'I am always looking for ways to apply pressure to make a customer buy.',                               true,  9, 2, NULL, 'SOCO item 24 (source-marked reverse). Saxe & Weitz 1982 JMR 19:343-351. Text verified via Michaels & Day 1985 JMR replication appendix; converted from buyer-report to self-report phrasing. 9-pt proportion scale, reverse-scored.');
