-- Migration: morning_recap_carry_forward_any_checkin_type
-- Version: 20260702134330
-- Applied via Supabase MCP apply_migration
-- NOTE: History stub. Final body in functions_2026-07-02.sql.
-- Change: Extended carry-forward to include midday check-in type
--         (not just eod), with type marker in parentheses.
