-- Batch 5 -- scenario distractor length rewrite (with addendum: item 31 added)
-- 12 items updated (choices column only). item_text, answer_key,
-- reverse_coded, hypothesized_trait, stint, scale_max, item_number,
-- retest_of_item_number all untouched. Items 3/5/32 confirmed untouched.
-- Item 31 was initially excluded per R2, then added via planning-thread
-- addendum after live verification showed R2's premise was wrong for it
-- (answer_key was the strict length outlier -- the exact leak this batch
-- exists to fix).

UPDATE public.hiregauge_instrument_items SET choices = '["Give them a preliminary quote based on similar policies you''ve seen recently, and make sure to let them know clearly that it''s just an estimate.", "Let them know you can gather their information now, but a licensed teammate will need to complete the actual quote before anything is official.", "Tell them you''ll have a licensed teammate give them a call back sometime later this week once their schedule opens up, most likely by Friday.", "Let them know you''re not licensed yet, and suggest they go ahead and reach out to a different agency in the meantime, so they aren''t left waiting."]'::jsonb WHERE id = 'dad2fd45-7f44-4a11-9e03-a28e5685b7e7' AND item_number = 1;

UPDATE public.hiregauge_instrument_items SET choices = '["Tell them it looks like a pretty standard claim from what you''ve seen, so it should probably be fine in the end, without checking further.", "Explain that the claims adjuster makes the coverage decision, and offer to help them get updates and escalate if anything stalls.", "Suggest they go ahead and contact claims directly for updates going forward, since that''s really not something you''re able to handle.", "Reach out to the adjuster to see if there''s anything that can be done to speed things up given the circumstances, even if unprompted."]'::jsonb WHERE id = '81ce0f92-b574-42e0-9ddc-11d405d30e38' AND item_number = 2;

UPDATE public.hiregauge_instrument_items SET choices = '["Do some digging on your end first, and loop in the right person only if you can''t figure it out.", "Explain what you can help with, and bring in the right person for the part you can''t resolve.", "Let them know that someone from the right team will reach out once it''s all sorted out on the back end.", "Walk them through how the general billing process usually works so they have a better understanding of it."]'::jsonb WHERE id = 'aafd752d-86f0-4c51-84ce-997b8c2f5a5a' AND item_number = 6;

UPDATE public.hiregauge_instrument_items SET choices = '["Share what you generally understand about how investing works, just to give them a starting point, nothing more formal.", "Let them know that''s outside what you''re able to advise on, and connect them with someone who is registered to help.", "Let them know it''s probably best to be cautious and take some time before making that kind of decision, especially with this.", "Suggest they take some time to look into it on their own and decide what feels best for them, without asking anyone else."]'::jsonb WHERE id = 'fbdeddd8-1a32-47c1-8cee-b50edc4a3a96' AND item_number = 9;

UPDATE public.hiregauge_instrument_items SET choices = '["Let them share everything on their mind before addressing any of it, even if it takes a while, no matter how far behind that puts you.", "Acknowledge their concern, handle the core of the issue efficiently, and offer to schedule a follow-up call if it needs more time.", "Handle their issue as quickly as you reasonably can so you''re able to get to the next call on time, same as any other call.", "Let them know that someone will give them a call back later today to go through everything, once today''s calls wrap up."]'::jsonb WHERE id = 'a4a7ce5f-e25b-493c-8106-94b7f84b3237' AND item_number = 10;

UPDATE public.hiregauge_instrument_items SET choices = '["Explain the coverage details as best you understand them, since it''s just an informal conversation, nothing official yet.", "Give them general information about the agency, and have them talk with a licensed teammate to go over actual coverage details.", "Tell them you''re not able to discuss any of the insurance details right now and step away from the conversation, not right now.", "Take down their contact information and have someone from the team reach out to them sometime next week, once things settle down."]'::jsonb WHERE id = '0a0c2c7b-1174-4cfb-9c76-aaecf60f4e91' AND item_number = 12;

UPDATE public.hiregauge_instrument_items SET choices = '["Go ahead and make the call yourself, since someone really needs to give them an answer today.", "Let them know you''re getting the right person involved, and follow up once you hear back.", "Tell them there''s really nothing you''re able to do until the supervisor gets back.", "Give them your best guess at what you think the supervisor would probably end up deciding."]'::jsonb WHERE id = '34a3d9a2-1716-47e6-9483-614c94323611' AND item_number = 14;

UPDATE public.hiregauge_instrument_items SET choices = '["Go ahead and send it, since they were customers of yours before at some point, most likely.", "Check whether they''re still within the window where outreach is allowed before sending anything.", "Only send it to the ones who called in fairly recently for other, unrelated reasons.", "Add them to a general newsletter list instead, rather than texting them directly."]'::jsonb WHERE id = '62ef9d1e-9d91-4077-ada7-2f5e1bb18b4b' AND item_number = 15;

UPDATE public.hiregauge_instrument_items SET choices = '["Stop texting them going forward, but continue with calls since they only specifically mentioned texts.", "Update their contact preferences right away, making sure it applies across every channel you use to reach them.", "Wait until the next campaign cycle comes around to go ahead and update the list, handled all at once.", "Let them know you''ll go ahead and pass the message along to the marketing team, for them to take from there."]'::jsonb WHERE id = '02d88078-c46e-4c31-8536-f1aa5f8ed551' AND item_number = 17;

UPDATE public.hiregauge_instrument_items SET choices = '["Fix it quietly on your own, since it''s already handled and no real harm was done.", "Fix it and let your manager know what happened, even though no one would''ve caught it.", "Wait to see if it actually becomes a problem for anyone before saying something.", "Mention it to a coworker you trust instead of bringing it to your manager."]'::jsonb WHERE id = 'a7db3005-303e-46be-8307-3f7ab26a3cf6' AND item_number = 21;

UPDATE public.hiregauge_instrument_items SET choices = '["Go ahead and accept the review, and quietly take care of the favor since it''s a pretty small thing.", "Thank them for the kind offer, but let them know the review isn''t something you''d trade for a favor.", "Tell them to go ahead and leave the review first before you decide on anything about the favor.", "Decline the review entirely, and ask them not to go ahead and leave one at all, even later on."]'::jsonb WHERE id = '8949b139-8259-4132-b811-1f3ff9962998' AND item_number = 22;

UPDATE public.hiregauge_instrument_items SET choices = '["Let them know it wasn''t really your fault before doing anything else about it.", "Stay calm, acknowledge their frustration, and keep working toward a solution.", "Stay quiet and just let them vent for a while without responding to any of it.", "End the call for now and let them cool down for a bit before continuing on."]'::jsonb WHERE id = 'cb7c2a1e-34b1-4da9-a8f2-783742f359a6' AND item_number = 31;
