-- Migration: extract_compute_team_health_weekly_hits_with_cap
-- Version: 20260702154712
-- Applied via Supabase MCP apply_migration
-- NOTE: History stub. Full CREATE OR REPLACE bodies in functions_2026-07-02.sql.
-- Change: Extracted compute_team_health_weekly_hits(agency_id, as_of_date)
--         with mid-week reality cap (LEAST(override, days_elapsed)).
--         Rewired team_health_checkin_compile and compute_weekly_pay to call it.
