-- Assessment length trim (OQ 6993f32f, approved 2026-08-02) -- completing the
-- integrity leg. SJT (40->20, 5 topics deactivated) and vocabulary (16->8,
-- fake/real rebalance to fix the all-fakes-in-stint-1 bug) were already
-- executed correctly by a prior/concurrent session. Integrity was left at
-- the STALE 33->18 number (5 baseline items/facet) instead of the corrected
-- 33->21 (6 baseline items/facet, per Peter's 2026-08-02 follow-up: 5 items
-- risks sincerity's internal consistency dropping below the .70 employment-
-- testing floor under Spearman-Brown, and integrity is the only score behind
-- a hard exit gate so it cannot be measured with fewer items than the
-- low-stakes personality facets).
--
-- No published item-total correlations exist for these (public-domain IPIP
-- Ashton/Lee/Goldberg 2007 items, not the HEXACO-100 itself), so selection
-- balances forward/reverse wording and spreads content coverage per Peter's
-- instruction, rather than taking items in original order:
--   fairness (item 19,21,23,24,25 active = 2 fwd/3 rev) + item 18
--     "Would never cheat on my taxes" (fwd) -> 3 fwd/3 rev, adds a concrete
--     cheating scenario distinct from the existing rule-following/stealing items.
--   greed_avoidance (27,29,31,32,36 active = 1 fwd/4 rev) + item 28
--     "Don't strive for elegance in my appearance" (fwd) -> 2 fwd/4 rev, only
--     forward-worded item left in the bank; adds appearance-materialism, a
--     content domain distinct from the existing status/money/power items.
--   sincerity (7,9,11,13,15 active = 1 fwd/4 rev) -- ALL 5 remaining inactive
--     items are reverse-coded (only 1 forward item exists in the whole bank),
--     so this one is picked for content spread only: item 14 "Act like
--     different people in different situations" -- situational inauthenticity/
--     chameleon behavior, distinct from the existing loyalty-switching (11),
--     manipulation (9), fake-concern (13), and power-pleasing (15) items.
UPDATE public.hiregauge_instrument_items SET is_active = true, updated_at = now()
WHERE item_number IN (18, 28, 14);
