
-- Weekly cash snapshot — one row per account per week
-- Generated by automation, used for the weekly pulse email and BCC dashboard
CREATE TABLE IF NOT EXISTS bank_register_weekly_snapshot (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id             uuid NOT NULL REFERENCES agency(id),
  
  -- Week identity
  week_ending           date NOT NULL,  -- always a Sunday
  account_last4         text NOT NULL,
  account_label         text NOT NULL,
  account_type          text NOT NULL,  -- checking / credit_card
  
  -- Opening / closing
  opening_balance       numeric NOT NULL DEFAULT 0,
  closing_balance       numeric NOT NULL DEFAULT 0,
  
  -- Week activity
  total_credits         numeric NOT NULL DEFAULT 0,
  total_debits          numeric NOT NULL DEFAULT 0,
  net_change            numeric GENERATED ALWAYS AS (total_credits - total_debits) STORED,
  
  -- Transaction counts
  txn_count             integer NOT NULL DEFAULT 0,
  coded_count           integer NOT NULL DEFAULT 0,
  uncoded_count         integer NOT NULL DEFAULT 0,  -- needs_peter + unclassified
  
  -- Top merchants this week (JSON array of {merchant, amount})
  top_merchants         jsonb,
  
  -- Narrative written by automation (plain English summary)
  week_narrative        text,
  
  -- Status
  snapshot_generated_at timestamptz NOT NULL DEFAULT now(),
  emailed_at            timestamptz,
  
  UNIQUE (agency_id, week_ending, account_last4)
);

CREATE INDEX IF NOT EXISTS idx_weekly_snapshot_agency_week ON bank_register_weekly_snapshot(agency_id, week_ending DESC);

