-- Adds GMA pattern-matching items 11-30 (20 new items), extending the
-- locked v3 pilot bank (items 1-10, migration 20260801201530) without
-- touching them. Generated + verified via
-- /home/claude/gma/generate_v4.py (rule-derived grids, verification pass,
-- duplicate-option gate -- per operational_rule "GMA matrix items -- build
-- via code generator on CJS(1990) taxonomy, never hand-author JSON").
--
-- Tier distribution added: tier1=3 (11-13), tier2=5 (14-18), tier3=5 (19-23),
-- tier4=7 (24-30). Combined with items 1-10, full bank is now 30 items.
-- is_active=false, stint=0 -- same as items 1-10, not yet wired into the
-- v1-assessment edge function's serve routing (Peter directive 2026-08-02:
-- build content now, decide sequencing/wiring later).

INSERT INTO hiregauge_instrument_items
  (section, item_number, item_text, choices, answer_key, cognitive_domain, stint, is_active)
VALUES
(
  'newtworks_v2_cognitive_gma', 11, 'Fill steps solid->outline->striped left to right; same order in every row.',
  '{"grid": [{"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "square", "fill": "striped", "size": "s", "count": 1, "rotation": 0}, "C": {"shape": "square", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, "D": {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "hexagon", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, "F": {"shape": "square", "fill": "striped", "size": "m", "count": 2, "rotation": 0}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 12, 'Size steps small->medium->large left to right; same order in every row.',
  '{"grid": [{"shape": "circle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "circle", "fill": "outline", "size": "l", "count": 1, "rotation": 0}, "B": {"shape": "rightTriangle", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, "C": {"shape": "circle", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, "D": {"shape": "circle", "fill": "solid", "size": "l", "count": 2, "rotation": 0}, "E": {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "F": {"shape": "hexagon", "fill": "solid", "size": "l", "count": 1, "rotation": 0}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 13, 'Right-triangle rotates 0deg->90deg->180deg left to right; same order in every row.',
  '{"grid": [{"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, null], "options": {"A": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 2, "rotation": 180}, "B": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 270}, "C": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, "D": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, "E": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, "F": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}}}'::jsonb, 'D', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 14, 'Circle, square, triangle -- each appears once per row and once per column.',
  '{"grid": [{"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "D": {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "F": {"shape": "square", "fill": "solid", "size": "m", "count": 2, "rotation": 0}}}'::jsonb, 'B', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 15, 'Solid, outline, striped fill -- each appears once per row and once per column.',
  '{"grid": [{"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "triangle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "hexagon", "fill": "outline", "size": "s", "count": 1, "rotation": 0}, "D": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "hexagon", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, "F": {"shape": "hexagon", "fill": "outline", "size": "m", "count": 1, "rotation": 0}}}'::jsonb, 'F', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 16, 'Small, medium, large size -- each appears once per row and once per column.',
  '{"grid": [{"shape": "square", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "D": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "square", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, "F": {"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}}}'::jsonb, 'A', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 17, '0deg, 90deg, 180deg rotation -- each appears once per row and once per column.',
  '{"grid": [{"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, "C": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, "D": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "arrow", "fill": "solid", "size": "m", "count": 2, "rotation": 90}, "F": {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 18, 'Right-triangle, arrow, triangle -- each appears once per row and once per column.',
  '{"grid": [{"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, "D": {"shape": "arrow", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, "E": {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "F": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}}}'::jsonb, 'A', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 19, 'Shape (circle/square/triangle) AND fill (solid/outline/striped) each distribute once per row and once per column, independently.',
  '{"grid": [{"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "hexagon", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "square", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, "C": {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "D": {"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "rightTriangle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "F": {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 20, 'Shape steps triangle->right-triangle->arrow left to right (same every row); rotation (0/90/180deg) distributes once per row and once per column.',
  '{"grid": [{"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "arrow", "fill": "solid", "size": "m", "count": 2, "rotation": 90}, "B": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, "C": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "D": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, "E": {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, "F": {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}}}'::jsonb, 'B', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 21, 'Size (s/m/l) AND fill (solid/outline/striped) each distribute once per row and once per column, independently.',
  '{"grid": [{"shape": "circle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "l", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "l", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "l", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "circle", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, "D": {"shape": "hexagon", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "circle", "fill": "outline", "size": "l", "count": 1, "rotation": 0}, "F": {"shape": "circle", "fill": "outline", "size": "m", "count": 3, "rotation": 0}}}'::jsonb, 'A', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 22, 'Shape distributes once per row/column; the count in the third column equals the count in the first column plus the count in the second column, in every row.',
  '{"grid": [{"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 3, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 3, "rotation": 0}, "B": {"shape": "square", "fill": "solid", "size": "s", "count": 3, "rotation": 0}, "C": {"shape": "square", "fill": "solid", "size": "m", "count": 3, "rotation": 0}, "D": {"shape": "square", "fill": "striped", "size": "m", "count": 3, "rotation": 0}, "E": {"shape": "square", "fill": "outline", "size": "m", "count": 3, "rotation": 0}, "F": {"shape": "square", "fill": "solid", "size": "m", "count": 4, "rotation": 0}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 23, 'Fill distributes once per row/column; the count in the third column equals the count in the first column minus the count in the second column, in every row.',
  '{"grid": [{"shape": "square", "fill": "solid", "size": "m", "count": 3, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "striped", "size": "m", "count": 2, "rotation": 0}, {"shape": "square", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, {"shape": "square", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "striped", "size": "m", "count": 4, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, null], "options": {"A": {"shape": "square", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, "B": {"shape": "arrow", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, "C": {"shape": "square", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, "D": {"shape": "hexagon", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, "E": {"shape": "square", "fill": "striped", "size": "m", "count": 2, "rotation": 0}, "F": {"shape": "square", "fill": "outline", "size": "m", "count": 3, "rotation": 0}}}'::jsonb, 'A', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 24, 'Fill is solid except for one striped shape per row; the striped one shifts position each row (0,1,2 -- distribution-of-two).',
  '{"grid": [{"shape": "circle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, "B": {"shape": "rightTriangle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "D": {"shape": "hexagon", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, "E": {"shape": "circle", "fill": "striped", "size": "m", "count": 2, "rotation": 0}, "F": {"shape": "circle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}}}'::jsonb, 'F', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 25, 'Size is medium except for one large shape per row; the large one shifts position each row (distribution-of-two).',
  '{"grid": [{"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "hexagon", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, "B": {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "C": {"shape": "triangle", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, "D": {"shape": "square", "fill": "solid", "size": "l", "count": 2, "rotation": 0}, "E": {"shape": "square", "fill": "striped", "size": "l", "count": 1, "rotation": 0}, "F": {"shape": "square", "fill": "solid", "size": "l", "count": 1, "rotation": 0}}}'::jsonb, 'F', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 26, 'Rotation is 0deg except for one shape at 180deg per row; the rotated one shifts position each row (distribution-of-two).',
  '{"grid": [{"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, "B": {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 270}, "C": {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, "D": {"shape": "triangle", "fill": "outline", "size": "m", "count": 1, "rotation": 180}, "E": {"shape": "hexagon", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, "F": {"shape": "triangle", "fill": "solid", "size": "m", "count": 2, "rotation": 180}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 27, 'Shape distributes once per row/column; fill is solid except one outline per row (position shifts); count in column 3 = column 1 + column 2. Three rules stacked -- true ceiling.',
  '{"grid": [{"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, {"shape": "square", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "outline", "size": "m", "count": 2, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 3, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "square", "fill": "outline", "size": "m", "count": 4, "rotation": 0}, "B": {"shape": "arrow", "fill": "outline", "size": "m", "count": 3, "rotation": 0}, "C": {"shape": "circle", "fill": "outline", "size": "m", "count": 3, "rotation": 0}, "D": {"shape": "hexagon", "fill": "outline", "size": "m", "count": 3, "rotation": 0}, "E": {"shape": "square", "fill": "outline", "size": "m", "count": 3, "rotation": 0}, "F": {"shape": "square", "fill": "solid", "size": "m", "count": 3, "rotation": 0}}}'::jsonb, 'E', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 28, 'Shape steps right-triangle->arrow->triangle left to right (same every row); rotation distributes once per row/column; size is medium except one small per row (position shifts). Three rules stacked.',
  '{"grid": [{"shape": "rightTriangle", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "arrow", "fill": "solid", "size": "s", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "rightTriangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "triangle", "fill": "solid", "size": "s", "count": 2, "rotation": 90}, "B": {"shape": "triangle", "fill": "solid", "size": "s", "count": 1, "rotation": 180}, "C": {"shape": "triangle", "fill": "solid", "size": "s", "count": 1, "rotation": 270}, "D": {"shape": "hexagon", "fill": "solid", "size": "s", "count": 1, "rotation": 0}, "E": {"shape": "rightTriangle", "fill": "solid", "size": "s", "count": 1, "rotation": 90}, "F": {"shape": "triangle", "fill": "solid", "size": "s", "count": 1, "rotation": 90}}}'::jsonb, 'F', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 29, 'Fill distributes once per row/column; size steps small->medium->large left to right (same every row); count in column 3 = column 1 minus column 2. Three rules stacked.',
  '{"grid": [{"shape": "circle", "fill": "solid", "size": "s", "count": 3, "rotation": 0}, {"shape": "circle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "l", "count": 2, "rotation": 0}, {"shape": "circle", "fill": "outline", "size": "s", "count": 2, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "l", "count": 1, "rotation": 0}, {"shape": "circle", "fill": "striped", "size": "s", "count": 4, "rotation": 0}, {"shape": "circle", "fill": "solid", "size": "m", "count": 2, "rotation": 0}, null], "options": {"A": {"shape": "arrow", "fill": "outline", "size": "l", "count": 2, "rotation": 0}, "B": {"shape": "hexagon", "fill": "outline", "size": "l", "count": 2, "rotation": 0}, "C": {"shape": "circle", "fill": "outline", "size": "l", "count": 2, "rotation": 0}, "D": {"shape": "circle", "fill": "outline", "size": "l", "count": 3, "rotation": 0}, "E": {"shape": "circle", "fill": "solid", "size": "l", "count": 2, "rotation": 0}, "F": {"shape": "circle", "fill": "outline", "size": "s", "count": 2, "rotation": 0}}}'::jsonb, 'C', 'gma_pattern', 0, false
),
(
  'newtworks_v2_cognitive_gma', 30, 'Shape is triangle except one arrow per row (position shifts); rotation distributes once per row/column; fill steps solid->outline->striped left to right. Three rules stacked -- ceiling.',
  '{"grid": [{"shape": "arrow", "fill": "solid", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "outline", "size": "m", "count": 1, "rotation": 90}, {"shape": "triangle", "fill": "striped", "size": "m", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 90}, {"shape": "arrow", "fill": "outline", "size": "m", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "striped", "size": "m", "count": 1, "rotation": 0}, {"shape": "triangle", "fill": "solid", "size": "m", "count": 1, "rotation": 180}, {"shape": "triangle", "fill": "outline", "size": "m", "count": 1, "rotation": 0}, null], "options": {"A": {"shape": "circle", "fill": "striped", "size": "m", "count": 1, "rotation": 90}, "B": {"shape": "arrow", "fill": "striped", "size": "m", "count": 1, "rotation": 90}, "C": {"shape": "arrow", "fill": "striped", "size": "m", "count": 1, "rotation": 270}, "D": {"shape": "arrow", "fill": "striped", "size": "m", "count": 2, "rotation": 90}, "E": {"shape": "arrow", "fill": "striped", "size": "m", "count": 1, "rotation": 180}, "F": {"shape": "hexagon", "fill": "striped", "size": "m", "count": 1, "rotation": 0}}}'::jsonb, 'B', 'gma_pattern', 0, false
);

