-- Selling-judgement situational items, draft 1, keyed 2026-09-04.
-- Staging table: NOT served, NOT scored. Items move into
-- hiregauge_instrument_items only after the most/least response format,
-- scoring function, norm row and role weight exist, and only the items that
-- survive a pilot on real applicants (retire anything with p > .85 first).
--
-- Keying method: hybrid. A literature-based key (Claude) reviewed and
-- overruled item by item by the agency owner as subject-matter expert
-- (Peter, 2026-09-04). Bergman, Drasgow, Donovan, Henning & Juraska 2006
-- (Int J Selection & Assessment 14:223-235) found hybrid rational+expert
-- keys perform comparably to multi-rater expert keys; the pilot's item
-- statistics are the check on the key, not a second rater.
-- Candidate instruction when live: "pick the one you would MOST likely do
-- and the one you would LEAST likely do" -- behavioural-tendency wording
-- (McDaniel, Hartman, Whetzel & Grubb 2007), most/least format for
-- variance (Ployhart & Ehrhart 2003).
-- Owner edits over the first draft: item 2 least C->A (C was not high
-- pressure); item 3 option A shortened so its length no longer gave it away;
-- item 4 option A reworded to be distinct from C; item 5 least B->C; item 6
-- life-insurance framing removed from situation and options, B rewritten
-- needs-based and keyed best, A keyed worst; item 7 best A->D (the agency
-- targets younger clients, text out-pulls a call); item 8 best A->C; item
-- 15 best A->D.

CREATE TABLE IF NOT EXISTS public.hiregauge_sjt_draft_items (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id      uuid NOT NULL,
  item_number    integer NOT NULL,
  title          text NOT NULL,
  situation      text NOT NULL,
  options        jsonb NOT NULL,
  key_most       text,
  key_least      text,
  key_rationale  text,
  keyed_by       text,
  keyed_at       timestamptz,
  status         text NOT NULL DEFAULT 'keyed'
                 CHECK (status IN ('draft','keyed','piloting','retired','live')),
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (agency_id, item_number)
);
COMMENT ON TABLE public.hiregauge_sjt_draft_items IS
  'Staging bank for the selling-judgement situational section. options = {"A":..,"B":..,"C":..,"D":..}; key_most / key_least = the keyed best and worst letters. Not served or scored until promoted to hiregauge_instrument_items after the pilot.';
ALTER TABLE public.hiregauge_sjt_draft_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS authenticated_select_hiregauge_sjt_draft_items ON public.hiregauge_sjt_draft_items;
CREATE POLICY authenticated_select_hiregauge_sjt_draft_items ON public.hiregauge_sjt_draft_items
  FOR SELECT TO authenticated USING (true);

INSERT INTO public.hiregauge_sjt_draft_items
  (agency_id, item_number, title, situation, options, key_most, key_least, key_rationale)
VALUES
('126794dd-25ff-47d2-a436-724499733365', 1, 'The quote-only caller', 'A caller says: "I just need a price on my two cars, I''m in a hurry. Same coverage I have now." You have enough to run a quote in two minutes.', '{"A": "Run the quote exactly as asked and give the number; offer a coverage review another time if they want one.", "B": "Tell them you need ten minutes to ask a few questions first, because you can''t quote responsibly without knowing what they have.", "C": "Ask two or three quick questions about what they have and why they''re shopping, run the quote, and mention any gap you spotted.", "D": "Run the quote as asked, then add a second quote with the coverage you''d recommend and explain the difference."}'::jsonb, 'C', 'B', 'Quick discovery, then the quote. B stonewalls someone in a hurry.'),
('126794dd-25ff-47d2-a436-724499733365', 2, '"I''m happy where I am"', 'You call a lead who requested an auto quote online. They say: "Honestly, I''m fine with my current company. I was just curious."', '{"A": "Thank them, ask if it''s okay to check back at their renewal, and note the date.", "B": "Ask what they like about their current company, then whether there''s anything they wish were different.", "C": "Point out that most people who are \"just curious\" end up saving money, and offer to run the numbers while you have them.", "D": "Email the quote anyway so they have it, and move to the next lead."}'::jsonb, 'B', 'A', 'B opens a need without pressure. A gives up on the contact. (Peter: C is not high pressure; least moved from C to A.)'),
('126794dd-25ff-47d2-a436-724499733365', 3, 'The 22% renewal', 'An eight-year customer calls upset: their home premium rose 22% at renewal. "I''ve never filed a claim. Why am I paying for everyone else''s roof?"', '{"A": "Explain what drove the increase, then look for savings that don''t cut their protection.", "B": "Apologize, acknowledge it''s a lot, and offer to raise their deductible to bring the premium down.", "C": "Acknowledge the frustration, then show what the same coverage costs elsewhere so they see it isn''t unique to us.", "D": "Tell them you''ll escalate it to see if anything can be done, and call them back tomorrow."}'::jsonb, 'A', 'D', 'Explain, then hunt savings that keep protection. D is a hollow stall. B leads with cutting protection. (Peter: A shortened so its length no longer gives it away.)'),
('126794dd-25ff-47d2-a436-724499733365', 4, 'The lead you can''t write well', 'A prospect wants auto coverage. Two at-fault accidents and a DUI in three years. Our rate will be high and underwriting may decline it. You have a stack of warmer leads waiting.', '{"A": "Work it like any other lead, full quote and follow-up. Every prospect deserves the same effort.", "B": "Tell them honestly we''re unlikely to be competitive right now, say what would change that, and ask if they''d like a call in a year.", "C": "Quote it, and if we can''t write it, point them to a carrier that can so they leave with something.", "D": "Politely say we can''t help and get back to the warmer leads."}'::jsonb, 'B', 'A', 'Honest, sets expectations, books a future call. A spends the afternoon on a long shot while warm leads wait. (Peter: A reworded to be distinct from C.)'),
('126794dd-25ff-47d2-a436-724499733365', 5, 'The referral moment', 'You''ve just bound auto and renters for a new customer. They''re pleased: the process was easy and they saved money.', '{"A": "Ask directly: \"Who else do you know who should be getting this kind of service? I''d love an introduction.\"", "B": "Mention that most of your business comes from customers like them, and leave a couple of cards in case anyone asks.", "C": "Wait until the policy has been in force a few months and they''ve had a good service experience before asking.", "D": "Ask about the one or two people they mentioned during the conversation (the roommate, the sister who just moved)."}'::jsonb, 'D', 'C', 'A specific name converts. C waits months and misses the moment of delight. (Peter: least moved from B to C.)'),
('126794dd-25ff-47d2-a436-724499733365', 6, 'Coverage they want to drop', 'A customer asks to remove rental reimbursement and roadside assistance to lower their premium. It saves $11 a month.', '{"A": "Remove the coverages as asked and confirm the new premium.", "B": "Remove them, then ask what prompted it. If money''s tight, go through the whole account with them for savings that don''t cost them protection.", "C": "Explain what they''d be giving up in a breakdown, and if they still want them removed, remove them.", "D": "Suggest they keep those coverages and look at other ways to save first."}'::jsonb, 'B', 'A', 'Honor the request, then ask what is driving it and look at the whole account. A just processes it. (Peter: life-insurance framing removed from the situation and options; B made needs-based and keyed best; A keyed worst.)'),
('126794dd-25ff-47d2-a436-724499733365', 7, 'The quote that went quiet', 'You emailed a home and auto quote eight days ago to a prospect who seemed interested. No reply to your one follow-up email.', '{"A": "Call, and if there''s no answer, leave a short voicemail asking if the timing changed.", "B": "Send one more email with a deadline: the quoted rate is good for 30 days.", "C": "Assume they went elsewhere and put them on the six-month check-in list.", "D": "Text a one-line question: \"Did the quote land okay, or did something not make sense?\""}'::jsonb, 'D', 'C', 'A one-line text gets the reply with the younger clients this agency targets. C quits after one email. (Peter: best moved from A to D.)'),
('126794dd-25ff-47d2-a436-724499733365', 8, 'The new house', 'During a routine auto question, a customer mentions in passing that they closed on a house last month.', '{"A": "Congratulate them and ask who they insured the house with and whether they''d like you to run a comparison.", "B": "Congratulate them, finish the auto question, and schedule a separate call about the home.", "C": "Congratulate them and mention that bundling the home with their auto would discount both, if they''re interested.", "D": "Congratulate them and note it in their file to raise at the next renewal."}'::jsonb, 'C', 'D', 'Mention the bundle discount while it is natural. D waits a year on a house already insured elsewhere. (Peter: best moved from A to C.)'),
('126794dd-25ff-47d2-a436-724499733365', 9, 'Fifteen dollars a month', 'A prospect likes you and likes the coverage, but a competitor quoted $15 a month less for what looks like similar coverage.', '{"A": "Walk through the two quotes line by line to find what''s actually different.", "B": "Explain the value of a local agent and claims service, and ask if $15 a month is worth giving that up.", "C": "Look for additional discounts or a slightly higher deductible to close the gap.", "D": "Tell them the competitor''s quote is probably fair and let them decide; you don''t want to win on pressure."}'::jsonb, 'A', 'D', 'The $15 is almost always a coverage difference. D concedes without looking.'),
('126794dd-25ff-47d2-a436-724499733365', 10, 'The new parent', 'A customer calls to add their newborn to their file. When you mention life insurance, they say: "We''re not there yet. It''s kind of a morbid thing to think about."', '{"A": "Say you understand, and ask if you can revisit it in six months.", "B": "Reframe it gently, as being about the baby''s future rather than death, and ask what they''d want to happen for the child if something happened.", "C": "Ask if they''d be open to seeing what a basic policy costs, no commitment, since the number is usually smaller than people expect.", "D": "Drop it entirely; pushing life insurance on a new parent feels like exploiting the moment."}'::jsonb, 'B', 'D', 'Reframe to the child''s future and ask. D walks away from the best life-insurance moment there is.'),
('126794dd-25ff-47d2-a436-724499733365', 11, '"I need to talk to my spouse"', 'After a strong quote presentation, the prospect says they need to check with their spouse before deciding.', '{"A": "Ask if the spouse could join a quick call now or tomorrow so you can answer their questions directly.", "B": "Say that''s completely reasonable, ask what questions the spouse is likely to have, and arm them with the answers.", "C": "Ask what specifically the spouse would want to know, then set a firm time to follow up.", "D": "Agree, send a summary they can share, and follow up in a few days."}'::jsonb, 'A', 'D', 'Get the decision-maker on the call. D hands over a summary and waits.'),
('126794dd-25ff-47d2-a436-724499733365', 12, 'State minimum', 'A young prospect on a tight budget wants only state-minimum liability on a car they still owe money on. "Just the cheapest legal option."', '{"A": "Explain that the lender will require comprehensive and collision on a financed car, and quote what they''ll actually need.", "B": "Quote the minimum as asked, and add a second quote with the liability limits you''d recommend so they can see the difference.", "C": "Quote what they asked for; it''s their decision and their budget.", "D": "Walk through what happens to them financially if they cause an accident at minimum limits, then let them choose."}'::jsonb, 'A', 'C', 'A financed car needs comprehensive and collision; the minimum is not available to them. C quotes something they cannot hold.'),
('126794dd-25ff-47d2-a436-724499733365', 13, 'The favor', 'A good customer calls about a small claim. Half-joking, they say that if you "date the policy change from last week" it would be covered. It wasn''t in force then.', '{"A": "Say you can''t do that, explain why, and help them understand what the claim process will actually look like.", "B": "Laugh it off, change the subject, and process the claim as it actually happened.", "C": "Tell them firmly that what they''re describing is fraud and that you''re surprised they asked.", "D": "Say you''ll look into what options exist and call them back."}'::jsonb, 'A', 'D', 'Decline, explain, help with the real process. D leaves the door open. C is right on substance, wrong on tone.'),
('126794dd-25ff-47d2-a436-724499733365', 14, 'End of day', 'It''s 4:30. You have: a quote to finish for a warm lead expecting it today, two renewal-review calls that were scheduled, a voicemail from an existing customer about a billing question, and a new online lead that just came in.', '{"A": "Finish the warm quote, then the scheduled calls, then the billing voicemail; the new lead gets tomorrow morning.", "B": "Call the new lead immediately while they''re hot, then the warm quote, then the rest.", "C": "Return the billing voicemail first because existing customers come first, then the quote, then the calls.", "D": "Do the two scheduled calls because you committed to them, then the quote, then the voicemail and the new lead."}'::jsonb, 'B', 'A', 'Two minutes on the new lead now, then the quote, then keep every commitment. A leaves the lead to tomorrow.'),
('126794dd-25ff-47d2-a436-724499733365', 15, 'The forgotten driver', 'While quoting, a prospect says there are no other drivers in the household. Later they mention their 17-year-old "sometimes borrows the car."', '{"A": "Explain that the teen needs to be listed and re-run the quote with them added, including any discounts that soften it.", "B": "Note it, quote as they originally stated, and let underwriting sort it out.", "C": "Ask whether the teen has their own coverage or car; if not, add them and show the difference.", "D": "Explain the risk of a claim being denied if the teen isn''t listed, then add them to the quote."}'::jsonb, 'D', 'B', 'Explain the denial risk, then add the teen. B is a material misstatement that can void a claim. (Peter: best moved from A to D.)'),
('126794dd-25ff-47d2-a436-724499733365', 16, 'The customer leaving', 'A twelve-year customer calls to cancel: a competitor bundled their home and auto for $60 a month less, and they''ve already signed.', '{"A": "Thank them for twelve years, ask if anything would have changed their mind, and leave the door open.", "B": "Ask them to hold off canceling for one day so you can rework their coverage and discounts, then call back.", "C": "Point out what they may be giving up (claims history here, accident forgiveness, agent access) and ask if they compared coverage, not just price.", "D": "Process the cancelation courteously and put them on a win-back list for eleven months out."}'::jsonb, 'B', 'D', 'Ask for a day and rework it; the coverage comparison is what you bring to that callback. D just lets them go.')
ON CONFLICT (agency_id, item_number) DO UPDATE
  SET title = EXCLUDED.title, situation = EXCLUDED.situation, options = EXCLUDED.options,
      key_most = EXCLUDED.key_most, key_least = EXCLUDED.key_least, key_rationale = EXCLUDED.key_rationale,
      updated_at = now();

UPDATE public.hiregauge_sjt_draft_items
SET keyed_by = 'Peter Story (subject-matter expert) over a literature-based first key, 2026-09-04',
    keyed_at = now(), status = 'keyed'
WHERE agency_id = '126794dd-25ff-47d2-a436-724499733365';
