ALTER TABLE public.team ADD COLUMN IF NOT EXISTS authorized boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN public.team.authorized IS 'Peter 2026-10-05: checked = authorized for every license checked off on this record (license_pc, license_lh, license_ips).';
CREATE OR REPLACE VIEW public.team_directory AS
 SELECT id,
    agency_id,
    first_name,
    last_name,
    nickname,
    role,
    role_category,
    role_level,
    category,
    employment_type,
    is_active,
    archived_at,
    hire_date,
    start_date,
    work_location,
    four_day_off_day,
    phone_extension,
    phone_personal,
    email_personal,
    email_sf,
    sf_alias,
    account_alpha,
    license_states,
    license_pc,
    license_lh,
    license_ips,
    primary_function,
    secondary_function,
    user_id,
    is_admin_backoffice,
    is_test_user,
    photo_storage_path,
    end_date,
    authorized
   FROM ( SELECT team.id,
            team.agency_id,
            team.first_name,
            team.last_name,
            team.nickname,
            team.role,
            team.role_category,
            team.role_level,
            team.category,
            team.employment_type,
            team.is_active,
            team.archived_at,
            team.hire_date,
            team.start_date,
            team.work_location,
            team.four_day_off_day,
            team.phone_extension,
            team.phone_personal,
            team.email_personal,
            team.email_sf,
            team.sf_alias,
            team.account_alpha,
            team.license_states,
            team.license_pc,
            team.license_lh,
            team.license_ips,
            team.primary_function,
            team.secondary_function,
            team.user_id,
            team.is_admin_backoffice,
            team.is_test_user,
            team.photo_storage_path,
            team.end_date,
            team.authorized
           FROM team) family_block
  WHERE NOT auth_is_family();
