INSERT INTO public.alerts (agency_id, alert_type, severity, title, module_reference, is_resolved, message)
VALUES
  ('126794dd-25ff-47d2-a436-724499733365', 'hiregauge_norm_missing', 'warning',
   'HireGauge norm missing: dispositional_optimism',
   'hiring_assessment', false,
   'HireGauge norms seed: no row inserted for facet "dispositional_optimism". Source confirmed as LOT-R, Scheier, Carver & Bridges (1994), J. Personality and Social Psychology 67(6):1063-1078, 6 scored items, matches item bank and catalog. Could not pull the original paper''s own Study 1 combined-sample mean/SD (Table 10 per secondary sources) from search in this pass — only found later cross-national replication samples (German, Norwegian, UK, Colombian) with divergent means (13.9-17.2), none of which is "the" combined-adult reference for the original scale. Needs a direct fetch of the original 1994 paper''s descriptive table.'),
  ('126794dd-25ff-47d2-a436-724499733365', 'hiregauge_norm_missing', 'warning',
   'HireGauge norm missing: political_skill_networking',
   'hiring_assessment', false,
   'HireGauge norms seed: no row inserted for facet "political_skill_networking". Source confirmed as PSI Networking Ability subscale (6 items), Ferris et al. 2005, J. Management 31:126-152, matches item bank and catalog. Found reliability (alpha=.87) but not subscale-level mean/SD in this pass. Needs a direct fetch of Ferris et al. 2005 Table 3/4 (descriptive statistics), which several secondary sources reference but do not reproduce.'),
  ('126794dd-25ff-47d2-a436-724499733365', 'hiregauge_norm_missing', 'warning',
   'HireGauge norm missing: enterprising',
   'hiring_assessment', false,
   'HireGauge norms seed: no row inserted for facet "enterprising". Source confirmed as O*NET Interest Profiler Short Form (IPSF), Enterprising scale, 10 items, public domain, matches item bank and catalog. Found one candidate figure (M=4.20, SD=2.70) from a National Center for O*NET Development paper-and-pencil validation study, but that study''s response format (appears to be a 3-point Dislike/Unsure/Like scale, count-scored) does not clearly match our item bank''s 5-point computerized Likert format (per item notes: "response scale matches O*NET computerized 5-pt format") — converting across a possible format mismatch risked a bad norm rather than a missing one, so it was not used. Needs the O*NET computerized/digital-format psychometric summary (not the paper-and-pencil study) with matching response scale.'),
  ('126794dd-25ff-47d2-a436-724499733365', 'hiregauge_norm_missing', 'warning',
   'HireGauge norm missing: competitiveness',
   'hiring_assessment', false,
   'HireGauge norms seed: no row inserted for facet "competitiveness". Source confirmed as WOFO (Work and Family Orientation Questionnaire) competitiveness factor, Helmreich & Spence 1978, 5-item version, popularized in sales context by Brown, Cron & Slocum 1998 (J. Marketing 62(4):88-98) — matches item bank (unusual attribution chain: items transcribed from a published newspaper reproduction attributed to Helmreich, cross-checked against Triandis INDCOL embedded items) and catalog. Did not attempt a source search for descriptive statistics in this pass (batch time budget); the Brown Cron Slocum 1998 sales-context paper is the most likely place to find a usable applied-population mean/SD given the WOFO original norms are for a general/academic population and this facet feeds a sales-heavy role-fit weight matrix.'),
  ('126794dd-25ff-47d2-a436-724499733365', 'hiregauge_norm_missing', 'warning',
   'HireGauge norm missing: learning_goal_orientation',
   'hiring_assessment', false,
   'HireGauge norms seed: no row inserted for facet "learning_goal_orientation". Source confirmed as VandeWalle 1997, Educational and Psychological Measurement 57(6):995-1015, Learning Goal Orientation subscale, matches item bank and catalog (distinct from VW99/VandeWalle-Brown-Cron-Slocum-1999 used elsewhere in the weight matrix — that is a different, later paper by an overlapping author set). Did not attempt a source search for descriptive statistics in this pass (batch time budget). Needs the original 1997 scale-development paper''s Study 2/3 descriptive table.');
