-- Migration: morning_recap_carry_forward_last_eod
-- Version: 20260702133928
-- Applied via Supabase MCP apply_migration
-- NOTE: This is a history stub. Full SQL body for the intermediate state
--       existed at apply time; final function body is in
--       supabase/schema_snapshots/functions_2026-07-02.sql
--       (team_checkin_send_reminder).
-- Change: Added last-EOD carry-forward to morning reminder message.
