-- Forced-choice personality pairs, rounds 1-2 of 4 (items 501-550). Authored and
-- AUTHORIZED by the planning thread 2026-08-14 (Peter directive: item content is a
-- decision, planning-level). Design per SPEC Grunt 1: pairs of statements from two
-- DIFFERENT facets (multidimensional pick, Cao & Drasgow 2019 JAP 104:1347-1368),
-- quasi-ipsative structure (Salgado & Tauriz 2014; Salgado, Anderson & Tauriz 2015).
-- Pairing = circulant schedule r=1..4 over the facets ordered by native desirability,
-- so partners sit in the same desirability neighborhood; both statements of a pair are
-- WRITTEN TO the pair's target band (desirability matched by construction, delta 0).
-- Desirability values are author-assigned targets on a 1-9 scale; empirical check
-- later: a statement chosen far above 50% against matched partners is under-matched
-- (future calibration signal from choice rates). Choosing a statement = more of that
-- facet, for every facet including negatively-weighted ones (anger, anxiety,
-- avoid_goal_orientation) -- downstream sign handling is unchanged (negative fit
-- weights; 100-p in commitment). is_active=false: dormant until FC delivery ships.
-- Section + response_format CHECKs widened in migration fc_items_widen_section_and_format_checks.
INSERT INTO public.hiregauge_instrument_items
  (section, item_number, item_text, choices, stint, is_active, response_format, is_nonsense, score_excluded, notes)
VALUES
('newtworks_v2_personality_fc',501,'Which sounds more like you at work?','{"A":{"facet":"sincerity","text":"I say what I actually think, even in tense rooms.","desirability":6.5},"B":{"facet":"fairness","text":"I apply the same rules to friends and strangers.","desirability":6.5}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.5; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',502,'Which sounds more like you at work?','{"A":{"facet":"fairness","text":"I split credit exactly as it was earned.","desirability":6.4},"B":{"facet":"compassion","text":"I check on people who seem to be struggling.","desirability":6.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',503,'Which sounds more like you at work?','{"A":{"facet":"compassion","text":"Someone else''s bad day changes how I treat them.","desirability":6.3},"B":{"facet":"cooperation","text":"I bend my approach so the group can move.","desirability":6.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',504,'Which sounds more like you at work?','{"A":{"facet":"cooperation","text":"I would rather adjust my plan than argue it.","desirability":6.2},"B":{"facet":"trust","text":"I assume coworkers mean well until shown otherwise.","desirability":6.2}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.2; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',505,'Which sounds more like you at work?','{"A":{"facet":"trust","text":"I hand off work without checking behind people.","desirability":6.1},"B":{"facet":"friendliness","text":"I strike up conversation with people I barely know.","desirability":6.1}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.1; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',506,'Which sounds more like you at work?','{"A":{"facet":"friendliness","text":"I greet everyone by name when I walk in.","desirability":6.0},"B":{"facet":"customer_orientation","text":"I stay on a customer issue until it''s settled.","desirability":6.0}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.0; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',507,'Which sounds more like you at work?','{"A":{"facet":"customer_orientation","text":"I rearrange my day when a customer needs me.","desirability":5.9},"B":{"facet":"dutifulness","text":"I keep small promises even when nobody would notice.","desirability":5.9}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.9; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',508,'Which sounds more like you at work?','{"A":{"facet":"dutifulness","text":"I follow the procedure even when shortcuts would pass.","desirability":5.8},"B":{"facet":"self_discipline","text":"I finish the boring parts before touching anything fun.","desirability":5.8}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.8; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',509,'Which sounds more like you at work?','{"A":{"facet":"self_discipline","text":"I work the plan even on days I don''t feel it.","desirability":5.7},"B":{"facet":"achievement_striving","text":"I raise my own target once I''m on pace.","desirability":5.7}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.7; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',510,'Which sounds more like you at work?','{"A":{"facet":"achievement_striving","text":"I keep score on myself weekly, win or lose.","desirability":5.6},"B":{"facet":"self_efficacy","text":"Hand me something unfamiliar and I''ll figure it out.","desirability":5.6}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.6; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',511,'Which sounds more like you at work?','{"A":{"facet":"self_efficacy","text":"I take the hard case others pass on.","desirability":5.5},"B":{"facet":"emotional_stability","text":"Bad news doesn''t change my tone for the day.","desirability":5.5}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.5; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',512,'Which sounds more like you at work?','{"A":{"facet":"emotional_stability","text":"I reset quickly after a call goes badly.","desirability":5.4},"B":{"facet":"dispositional_optimism","text":"I expect next month to beat this one.","desirability":5.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',513,'Which sounds more like you at work?','{"A":{"facet":"dispositional_optimism","text":"I assume a rough quarter will turn around.","desirability":5.3},"B":{"facet":"learning_goal_orientation","text":"I pick tasks that stretch me over easy wins.","desirability":5.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',514,'Which sounds more like you at work?','{"A":{"facet":"learning_goal_orientation","text":"I''d take training over a small bonus.","desirability":5.2},"B":{"facet":"proactive_personality","text":"I fix broken processes without being asked.","desirability":5.2}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.2; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',515,'Which sounds more like you at work?','{"A":{"facet":"proactive_personality","text":"I start the change and explain it after.","desirability":5.1},"B":{"facet":"enterprising","text":"I look for something to pitch in every conversation.","desirability":5.1}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.1; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',516,'Which sounds more like you at work?','{"A":{"facet":"enterprising","text":"Selling an idea energizes me more than executing it.","desirability":5.0},"B":{"facet":"assertiveness","text":"I take charge when a meeting starts drifting.","desirability":5.0}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.0; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',517,'Which sounds more like you at work?','{"A":{"facet":"assertiveness","text":"I interrupt politely rather than wait my turn forever.","desirability":4.9},"B":{"facet":"competitiveness","text":"I track how I rank against the team.","desirability":4.9}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.9; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',518,'Which sounds more like you at work?','{"A":{"facet":"competitiveness","text":"Losing a friendly contest bugs me for days.","desirability":4.8},"B":{"facet":"political_skill_networking","text":"I keep in touch with people who open doors.","desirability":4.8}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.8; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',519,'Which sounds more like you at work?','{"A":{"facet":"political_skill_networking","text":"I plan who to know before I need them.","desirability":4.7},"B":{"facet":"greed_avoidance","text":"Titles and corner offices do little for me.","desirability":4.7}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.7; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',520,'Which sounds more like you at work?','{"A":{"facet":"greed_avoidance","text":"I''d skip a raise to keep work I like.","desirability":4.6},"B":{"facet":"prove_goal_orientation","text":"I want the numbers to show I''m the best.","desirability":4.6}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.6; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',521,'Which sounds more like you at work?','{"A":{"facet":"prove_goal_orientation","text":"I pick tasks where my results get seen.","desirability":4.5},"B":{"facet":"cautiousness","text":"I sleep on big decisions even under time pressure.","desirability":4.5}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.5; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',522,'Which sounds more like you at work?','{"A":{"facet":"cautiousness","text":"I re-read messages twice before sending anything important.","desirability":4.4},"B":{"facet":"avoid_goal_orientation","text":"I steer toward work I already do well.","desirability":4.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',523,'Which sounds more like you at work?','{"A":{"facet":"avoid_goal_orientation","text":"I skip volunteering when I might look unskilled.","desirability":4.3},"B":{"facet":"anxiety","text":"I keep replaying a task until it''s truly done.","desirability":4.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',524,'Which sounds more like you at work?','{"A":{"facet":"anxiety","text":"Loose ends sit in my head after hours.","desirability":4.2},"B":{"facet":"anger","text":"Repeated sloppiness gets a sharp word from me.","desirability":4.2}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.2; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',525,'Which sounds more like you at work?','{"A":{"facet":"anger","text":"I push back hard when someone wastes my time.","desirability":5.3},"B":{"facet":"sincerity","text":"I give my real opinion even when it costs me.","desirability":5.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',526,'Which sounds more like you at work?','{"A":{"facet":"sincerity","text":"I skip flattery even when it would help me.","desirability":6.4},"B":{"facet":"compassion","text":"I notice quickly when a teammate is overloaded.","desirability":6.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',527,'Which sounds more like you at work?','{"A":{"facet":"fairness","text":"I''d return an advantage I didn''t earn.","desirability":6.3},"B":{"facet":"cooperation","text":"I let the group''s call stand over my preference.","desirability":6.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',528,'Which sounds more like you at work?','{"A":{"facet":"compassion","text":"I make time for someone upset, deadline or not.","desirability":6.2},"B":{"facet":"trust","text":"I take people''s word without asking for proof.","desirability":6.2}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.2; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',529,'Which sounds more like you at work?','{"A":{"facet":"cooperation","text":"Keeping the peace matters more than winning the point.","desirability":6.1},"B":{"facet":"friendliness","text":"New people at work hear from me first.","desirability":6.1}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.1; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',530,'Which sounds more like you at work?','{"A":{"facet":"trust","text":"I share early drafts without fearing they''ll be misused.","desirability":6.0},"B":{"facet":"customer_orientation","text":"I call customers back before they have to chase me.","desirability":6.0}}',1,false,'forced_choice_pair',false,false,'FC pair band 6.0; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',531,'Which sounds more like you at work?','{"A":{"facet":"friendliness","text":"I remember small personal details people mention once.","desirability":5.9},"B":{"facet":"dutifulness","text":"I''m the one who actually reads the policy updates.","desirability":5.9}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.9; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',532,'Which sounds more like you at work?','{"A":{"facet":"customer_orientation","text":"I''ll eat a small loss to keep a customer whole.","desirability":5.8},"B":{"facet":"self_discipline","text":"My task list is done in order, not by mood.","desirability":5.8}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.8; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',533,'Which sounds more like you at work?','{"A":{"facet":"dutifulness","text":"Deadlines I agree to are commitments, not estimates.","desirability":5.7},"B":{"facet":"achievement_striving","text":"Coasting at quota would bore me fast.","desirability":5.7}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.7; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',534,'Which sounds more like you at work?','{"A":{"facet":"self_discipline","text":"I prep tomorrow''s work before leaving today.","desirability":5.6},"B":{"facet":"self_efficacy","text":"I rarely need the manual twice.","desirability":5.6}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.6; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',535,'Which sounds more like you at work?','{"A":{"facet":"achievement_striving","text":"I chase the stretch goal, not the safe one.","desirability":5.5},"B":{"facet":"emotional_stability","text":"Pressure sharpens me instead of rattling me.","desirability":5.5}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.5; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',536,'Which sounds more like you at work?','{"A":{"facet":"self_efficacy","text":"Thrown in the deep end, I swim.","desirability":5.4},"B":{"facet":"dispositional_optimism","text":"I read setbacks as delays, not verdicts.","desirability":5.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',537,'Which sounds more like you at work?','{"A":{"facet":"emotional_stability","text":"An angry caller doesn''t follow me into the next call.","desirability":5.3},"B":{"facet":"learning_goal_orientation","text":"Feedback that stings is still feedback I want.","desirability":5.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',538,'Which sounds more like you at work?','{"A":{"facet":"dispositional_optimism","text":"I bet on the upside when odds are unclear.","desirability":5.2},"B":{"facet":"proactive_personality","text":"I raise the problem nobody wants to name.","desirability":5.2}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.2; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',539,'Which sounds more like you at work?','{"A":{"facet":"learning_goal_orientation","text":"I''d rather struggle and learn than delegate and not.","desirability":5.1},"B":{"facet":"enterprising","text":"I spot the sales angle in routine service calls.","desirability":5.1}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.1; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',540,'Which sounds more like you at work?','{"A":{"facet":"proactive_personality","text":"I act on gaps before they become assignments.","desirability":5.0},"B":{"facet":"assertiveness","text":"My position is the first one the room hears.","desirability":5.0}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.0; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',541,'Which sounds more like you at work?','{"A":{"facet":"enterprising","text":"I''d cold-call strangers over organizing files any day.","desirability":4.9},"B":{"facet":"competitiveness","text":"A leaderboard makes any task more interesting to me.","desirability":4.9}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.9; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',542,'Which sounds more like you at work?','{"A":{"facet":"assertiveness","text":"I''ll say the unpopular thing the room is avoiding.","desirability":4.8},"B":{"facet":"political_skill_networking","text":"I map who really decides before I ask.","desirability":4.8}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.8; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',543,'Which sounds more like you at work?','{"A":{"facet":"competitiveness","text":"Second place is just first loser to me.","desirability":4.7},"B":{"facet":"greed_avoidance","text":"Money is a scoreboard I mostly ignore.","desirability":4.7}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.7; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',544,'Which sounds more like you at work?','{"A":{"facet":"political_skill_networking","text":"I trade favors deliberately to build goodwill.","desirability":4.6},"B":{"facet":"prove_goal_orientation","text":"Being seen outperforming matters to me.","desirability":4.6}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.6; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',545,'Which sounds more like you at work?','{"A":{"facet":"greed_avoidance","text":"Modest pay in the right job beats chasing top dollar.","desirability":4.5},"B":{"facet":"cautiousness","text":"I hold decisions open longer than most people would.","desirability":4.5}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.5; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',546,'Which sounds more like you at work?','{"A":{"facet":"prove_goal_orientation","text":"I choose the audience-facing task over the quiet one.","desirability":4.4},"B":{"facet":"avoid_goal_orientation","text":"I let others go first on unfamiliar tasks.","desirability":4.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',547,'Which sounds more like you at work?','{"A":{"facet":"cautiousness","text":"I ask one more question than the situation demands.","desirability":4.3},"B":{"facet":"anxiety","text":"I check my work again even after sign-off.","desirability":4.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.3; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',548,'Which sounds more like you at work?','{"A":{"facet":"avoid_goal_orientation","text":"I''d pass on a stage role to dodge public mistakes.","desirability":4.2},"B":{"facet":"anger","text":"My irritation shows before I can park it.","desirability":4.2}}',1,false,'forced_choice_pair',false,false,'FC pair band 4.2; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',549,'Which sounds more like you at work?','{"A":{"facet":"anxiety","text":"Big meetings sit in my stomach the night before.","desirability":5.4},"B":{"facet":"sincerity","text":"I''d rather be blunt than smooth.","desirability":5.4}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.4; planning-authored 2026-08-14'),
('newtworks_v2_personality_fc',550,'Which sounds more like you at work?','{"A":{"facet":"anger","text":"People learn quickly which buttons not to press.","desirability":5.3},"B":{"facet":"fairness","text":"I''d flag an error in my own favor.","desirability":5.3}}',1,false,'forced_choice_pair',false,false,'FC pair band 5.3; planning-authored 2026-08-14');
