-- ============================================================================
-- 2026-07-06 legacy source-naming removal — historical record
-- ============================================================================
-- Full-DB scrub of a legacy accounting source-system's naming from every
-- machine-consumed field. Applied 2026-07-06 across 7 sub-migrations:
--   removal_01_drops_data_updates_column_renames
--   removal_02_view_rebuilds
--   removal_03_rewrite_gl_writer_functions
--   removal_04_drop_legacy_staging_fn
--   removal_05_final_gaps
--   removal_06_final_sweep_and_core_principle
--   removal_07_defaults_and_comments
--
-- Post-scrub naming scheme (locked; see operational_rule "BCC chart-and-source
-- naming scheme (locked 2026-07-06)" for the prescriptive rules going forward):
--   Account codes: COA-###, COA-SUB-###, COA-SUSP
--   je.source label for pre-cutover imports: books_historical_import_YYYY
--   chart_of_accounts.chart_namespace: books_historical
--   v_trial_balance.source_bucket: books_historical
--   comp_category_map / comp_deduction_map cols: source_account_name,
--     source_parent_account_name
--   Variance view: v_variance_books_historical_vs_bcc (col: books_historical_balance)
--   Settings: drive_YYYY_prior_books_reports_folder_id
--   je.created_by for imported rows: books_historical_loader
--   documents.file_type for imported statements: prior_books_balance_sheet,
--     prior_books_general_ledger, prior_books_pnl
--   documents.upload_source: manual_prior_books_archive_session_N
--   opening_balances.source default: books_historical_balance_sheet_2026ytd_pdf
--
-- Preserved (transaction data, not system labels): ~34 journal_entries
-- description/memo rows + journal_lines description rows containing literal
-- CC-statement merchant text naming a specific vendor payee (Peter's recurring
-- accounting-software subscription).
--
-- No-op if re-run against a DB where the migration already applied.
-- ============================================================================
