-- Screen layer backfill, tier 3: the 8 candidates at status='assessed'.
-- Planning-thread scoring against hiregauge_rules rule_type='screen_score_rubric'.
-- Signals + narrative + scored_at + scored_model only.

BEGIN;

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 88, 'accountability', 80,
    'role_interest_specificity', 80, 'challenge_realism', 85),
  'narrative', 'Highest screen in the backlog, and the only candidate strong on all four signals. Item 1 is the most verifiable history received: Double E Fit-Testing closed in 2018 as the region declined with the oil industry; he left Team Chevrolet Buick and GMC on moving to San Antonio because the company had no location here; his position was cut at Airgas in a company-wide reduction of the Account Management Program mandated by parent company Air Liquide that left only the most senior members, and he volunteers that he remained eligible for unemployment because he was not fired. Named employers, named parent company, dates consistent with the resume (Airgas April 2023 to March 2026), and an unprompted clarification on the one exit that could look bad. Item 3 is the best challenge answer this layer has scored from anyone: he names insurance regulation and compliance first and states that every conversation has rules to follow - which is exactly right and something almost nobody outside the industry knows going in - then product depth, then agency-specific process. He does not name rejection, and he reframes each difficulty as something he is excited about, which is the only reason this is not scored higher. Item 2 ties the interest to years of consultative, value-based sales backed by the resume (20-plus key accounts, 30 percent annual revenue growth, upselling and cross-selling) and describes the work the way this agency actually describes it - helping people understand their options, building trust, guiding them to the right solution. His resume is explicitly tailored to a State Farm agent team environment, consistent with a targeted rather than scattershot application. Item 5 is a real decision with a real cost and a sharp self-criticism: a customer trialing a new product asked to switch the order the day before training, and only samples were on hand, so he drove several hours to the nearest warehouse and spent an afternoon and evening fixing it. The stated correction is operationally specific - gauge that individual contact for receptiveness and pre-order stock, since unused product could be returned. Held just below the top band because the framing leans on the heroic recovery and the root cause was partly the contact never confirming. Item 7 is checkable and points at the Airgas exit he explained: named person, employer, number. Interview note: he chose the lower base with higher upside, consistent with everything else in his file.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = 'f6a08bf6-0d7f-44ed-8957-62a310b54904';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 44, 'accountability', 60,
    'role_interest_specificity', 58, 'challenge_realism', 38),
  'narrative', 'Consistent middle across the board with no red flags and no standout. Item 1 gives no specifics on prior moves (each left for a better opportunity, no employer named) but the current reason is honest and coherent - he wants out of restaurant and hospitality work to build broader experience, and the resume backs a single long tenure as bar manager at Toro Kitchen and Bar since March 2025. Item 2 names insurance sales directly and ties to verifiable history on the resume (led the team in sales, upselling, closing), which puts it above the generic band; the phrase about skills being easily transferable is a confidence tell worth probing, because hospitality upselling to a seated guest and outbound insurance sales to a stranger are not the same motion. Item 3 names the real domain difficulty - learning the ins and outs of selling and advising on insurance - and then dismisses it as not a problem with correct training; no rejection, licensing or pace. Item 5 is fully owned and cleanly handled: he forgot to enter a main dish that takes 30 to 40 minutes, went to the kitchen the moment he realized, then told the table plainly, talked them through it and offered an alternative. Real ownership and a real recovery, held in the middle band because the consequence was small and he never answers the third part of the question - what he should have done differently. Item 7 gives employer and a named person with no number.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = '1d9c2175-f3d6-4fc6-9f20-781f09fd1222';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 30, 'accountability', 66,
    'role_interest_specificity', 20, 'challenge_realism', 78),
  'narrative', 'Sharply uneven. Item 3 is genuinely good and names the hard part squarely - handling rejection and staying motivated with people who are not initially interested, understood as part of sales rather than a surprise - and she has actual sales experience behind it. Item 5 is complete on all three parts: she took a task on alone believing she would be faster, misunderstood part of the process, created extra work for the team, then owned it, told people, and fixed it with a coworker, with a clear correction about confirming the process before starting rather than assuming. The other two answers undercut all of it. Item 1 explains nothing - better opportunities, more growth, better long-term fit, with no employer named and no reason given for leaving the current job. Item 2 is boilerplate that would paste into any application anywhere: matches my skills and career goals, enjoy learning new things, helping others, being part of a team, drawn to the company reputation. THE NOTABLE MISS: her resume shows her currently working as an Insurance Sales Agent at Global Life Insurance since January 2026. She is selling insurance right now and did not mention it in either the question about why she is interested in this job or the question about why she is leaving her current one. That omission is the single most important thing to ask her about - it is the most relevant fact in her file and she left it out of both places it belonged. Item 7 gives a company and a location with a phone number but no person.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = '2e07ffa4-f1f3-4c8c-a662-e97a7828ce22';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 76, 'accountability', 58,
    'role_interest_specificity', 22, 'challenge_realism', 35),
  'narrative', 'Strong on history, weak on wanting this particular job. Item 1 is the second-best covered history in this tier: three positions each with a specific reason - Attain is growing in Texas but does not yet have the client volume to staff the behavior technicians it has hired, and the mentorship role he holds only partly offsets that; Perfect Shift went through management, ownership and finance changes and could no longer offer stability; he left Action Behavior Centers for a better compensation package on good terms. Resume confirms both Attain and Action Behavior Centers. Concrete, checkable, and honest about money being a motive. Item 5 is a real operational decision with real stakes, and it is the interesting one: clients choosing their own therapy hours created unstable hours for his technicians, so he moved to fixed selectable timeslots, which some clients could not accommodate, and the committee then carved out a pool of more flexible staff. He describes a decision, its unintended cost, and a remedy - but he never frames it as his mistake, offers no statement of what he should have done differently, and attributes the fix to the committee. That missing third part is what holds this in the middle band rather than the top. Item 2 is generic - exercise people and problem-solving skills, want consistency, love working with others - with no mention of insurance. Item 3 gestures at the volume of learning in a new field and then closes it off with a slogan about not shying away from a challenge. Item 7 gives an employer and a location with no person and no number.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = 'ca287b87-0c53-42f0-90e3-016d842ca99f';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 32, 'accountability', 52,
    'role_interest_specificity', 28, 'challenge_realism', 22),
  'narrative', 'A 15-plus year executive operations resume producing four answers with almost no content in them. Item 1 explains no individual move - each career move was based on professional growth and increased responsibility - and the most recent departure is given as organizational circumstances, which is a euphemism rather than a reason; no employer is named anywhere despite a long multi-sector history across higher education, government, nonprofit and corporate work. Item 2 describes being the first point of contact and creating a welcoming professional experience, plus the chance to learn and take on more responsibility. That is a front-desk seat, and it is the second candidate in this backfill to describe the job that way; every position in this agency participates in selling, so the role as she understands it is not the role. Insurance is never mentioned. Item 3 is the low anchor with a self-reassurance attached - learning the agency processes quickly while providing excellent service, and she is a fast learner open to coaching. Item 5 has all three structural parts and no substance: she moved too quickly on a scheduling decision without confirming details, created a conflict, took responsibility, communicated immediately, resolved it with everyone involved, and now double-checks. Nothing is named - not the decision, not who was affected, not the consequence - so it reads as the shape of a good answer rather than an actual one. Worth noting the contrast that makes this file hard to read: item 7 is by far the best reference set in the entire backlog - three people with titles, organizations, emails and phone numbers - so she is thorough and professional on the checkable credential item and empty on every item that asks her to say something specific about herself. That gap is the interview question.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = '9082b901-0aaa-4a7f-8cf8-f7faa1287dce';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 22, 'accountability', 50,
    'role_interest_specificity', 38, 'challenge_realism', 12),
  'narrative', 'Item 1 does not answer the question - relocating often and moving to a different state for the last job explains geography, not why any position ended, and no employer or reason appears. Item 3 is three words, learning something new, which is the softball low anchor at minimum length. Item 2 does name State Farm and is warmer than most - being the calm, reliable person when things feel stressful is a real read on service work - but the substance is generic helping-people plus what the job offers her in steady hours and consistency, with nothing tied to her own history; it also carries a copy-paste artifact at the start where the sentence begins twice, which suggests the answer was assembled rather than written. Item 5 is the strongest of her four and is genuinely reflective: she put more money down on a car than she needed to believing it would help her credit, did not think through the effect on savings and budget, then adjusted her spending, got deliberate about budgeting, and now examines large financial decisions before committing. Real ownership and a real lesson, held to the middle band because it is a personal financial choice rather than a decision at work that went wrong for other people, which is what the item asks for. One fit note: her resume is built entirely around remote work - the headline states availability for remote work and the summary is about providing efficient virtual support - and this seat is not remote. That needs to be settled before anything else. Item 7 is checkable in outline: employer, a first name, and a number.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = 'fa8a1c03-fc73-4559-a168-92f20c92d2c2';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 42, 'accountability', 8,
    'role_interest_specificity', 40, 'challenge_realism', 10),
  'narrative', 'THE MOST IMPORTANT FILE IN THIS BACKFILL, because the paper and the answers point opposite directions. On paper she is the most qualified candidate in the set: licensed in General Lines for Property and Casualty and in Life and Health, with over two decades in insurance. On the written probes she scores second lowest of nineteen. Item 3 is a direct instance of the low anchor - she welcomes challenges and does not foresee any. From a twenty-year licensed agent joining an unfamiliar agency with an unfamiliar book, systems and expectations, that is not modesty about difficulty, it is an absence of curiosity about it. Item 5 is worse: she thinks before deciding and tends not to make incorrect ones when it comes to insureds. That declines the question and asserts she does not make mistakes, which is the clearest zero-credit pattern this rubric names. Item 2 asserts that insurance is her passion and she wants to learn more, and she does have the industry behind her, but she offers not one specific from twenty years of it and never connects the interest to anything she has actually done. Item 1 gives one clean, verifiable reason - the last position was in Boerne and she lives in San Antonio - which is credible, but it covers one job out of a two-decade history, and the resume shows that last role at Yates and Associates ran only March to May 2026. A two-month tenure is the thing that most needs explaining, and distance does not explain it, because the commute existed on the day she accepted it. Recommendation: this file cannot be read from the resume alone. If she advances, items 3 and 5 must be re-asked live and answered concretely, and the two-month tenure and the reason for leaving it verified with the employer, before any offer conversation. Item 7 names an organization only, USAA, with no person and no number.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = '264d0b79-ada3-4a98-b698-79b0ff577b4f';

UPDATE public.hiring_candidates SET screen_analysis = jsonb_build_object(
  'signals', jsonb_build_object(
    'job_history_candor', 18, 'accountability', 12,
    'role_interest_specificity', 30, 'challenge_realism', 15),
  'narrative', 'Lowest screen in the backfill. All four answers decline the question asked, and the shortfall is substance rather than length or polish. Item 1 opens by complimenting the question and then never answers it - looking for growth, learning something new, expanding knowledge, seeking stability with good owners and communicators and benefits. Not one employer, departure or date, against a resume carrying more than fifteen years across customer service, technical support, insurance restoration and operations management, most recently as Operations Manager at Restopros. Item 3 is five words - adapting to the different systems - the shortest and most exact instance of the low anchor in the set. Item 5 is a non-answer that asserts competence in place of a mistake: she processes every decision and considers how it affects others, everyone can make mistakes but she learns from hers and aims not to repeat them, she always owns up and communicates. No mistake is named, no correction described, no lesson stated, and the answer then drifts into a general observation about field teams needing documentation for the adjuster. Item 2 is the only one with any signal - insurance is in her field and knowledge base - and that is fair, since her restoration background with IICRC certification and Xactimate proficiency is genuinely adjacent to this industry. But she never articulates the connection, so it scores as an assertion rather than a specific. That adjacency is the reason to ask rather than assume: the raw material for a strong answer exists in her history and none of it reached the page. Item 7 names an organization only, Restopros, with no person and no number.',
  'scored_at', '2026-08-13T22:10:00Z', 'scored_model', 'claude-opus-5')
WHERE id = 'dbf4c255-d2c4-4085-a7ce-0605836ed14a';

COMMIT;
