-- Backfill resume_analysis.signals.effort for all 21 candidates with existing resume_analysis.
-- Scored 2026-07-24 based on the "Drivers: Effort" rubric in hiregauge_rules.
-- Also recomputes resume_analysis.avg as mean of all 12 signals.
-- Prior: resume_extracted_text for 5 canonicals (Allan/Katie/Maximus/Carla/Jason) was overwritten
-- with real Google Drive PDF extractions (previous stored value was Claude-authored summary notes,
-- backed up to resume_analysis._prior_summary_text before overwrite).

WITH effort_scores AS (
  SELECT * FROM (VALUES
    ('Allan Piedrabuena', 58, 'Length appropriate for 8-year career. Clean professional formatting, no typos. Real institutions verifiable (Farmers, Chase, Wells Fargo, HEB, Sam''s, Oregon State, eCornell). One insurance-relevant credential (TX P&C License 2026). One quantified metric (35% wireless sales increase). BUT zero SF-specific tailoring — objective is generic corporate-boilerplate ("Seeking to leverage analytical skills"), most experience bullets are unquantified verb phrases. Reads as a general-purpose insurance/banking resume, not tailored to a State Farm agency role. Middle effort.'),
    ('Katie Barraco', 78, 'Massively SF-tailored — every job entry is a State Farm agency, names 7 SF agents specifically (Trey Vavra, Kathy Scott, Stephanie Lempesis, Nick Wagner, Jared Dean, Nahoku Ahlo, Skip Barraco), mentions specific SF systems (ECRM, Necho). Specific quantified claims ($25K/month premium, $250K annual, 15+ years). Warm personal tone with smileys and "my customers" — unconventional but signals genuine care and fit. Real institutions everywhere. Clean formatting. High effort, distinctively hers.'),
    ('Maximus Moody', 32, 'Length appropriate for 2-year career. Real employers (San Antonio Aquarium, Mother Earth Labs, Subway, O''Connor HS). BUT zero SF/insurance tailoring, generic Indeed-template "Dynamic professional" opener, zero quantified claims (all generic verb phrases like "Delivered excellent customer service"). Certifications section lists "Driver''s License" twice — actual carelessness error. Buzzword-only skills grid. Low-mid effort, template-generated.'),
    ('Carla Sanders', 38, 'Indeed-generated resume — "Indeed Resume — Page 1" header at top signals candidate didn''t polish the download. "Less than 1 year" auto-tag on 8 of 9 skills = Indeed skeleton showing. Bachelor''s degree entry has no field, no institution, no year (Indeed blank fields not filled in). Zero SF/insurance tailoring, pitched generically at "Sales Consultant or Sales Representative." Some quantified claims (100% sales growth, 15% annual, $1M+ deals). Real employers. Low effort — accepted Indeed''s auto-format without adding personal styling.'),
    ('Jason Villa', 42, 'Length short for 6-year career (2,184 chars). Zero SF/insurance tailoring. Corporate-vague phrasing including odd construction "Championed Microsoft Office products". Some questionable claims ("Maintained 100% customer satisfaction" is ambiguous). Buzzword-heavy skills list. Real employers (Ernst & Young, Wells Fargo, Spectrum, UTSA). Statistics degree not aligned with insurance role. Minimal education section, no polish beyond default formatting. Middle-low effort.'),
    ('Alyssa Sapp', 82, 'Massively SF-tailored — SF systems named specifically (MOD, SF Billing, SFPP, ECRM, NECHO), TASP designation mentioned, agency name (Central Louisiana). Specific quantified claims (30% technician efficiency, uninsured under 1%, 39 months at SF, 22 months in senior role). Real employers verifiable. Multiple "built from scratch" specific claims. Clean formatting, no typos. Only weakness is no formal degree stated. Highest effort of the pool, distinctively SF-tailored.'),
    ('Anthony Papini', 25, 'Very short (~1,573 chars for 5+ year career). Zero SF/insurance tailoring — Amazon delivery, Uber Eats, U.S. Silica sand loading. Generic objective "Energetic and driven young man" — casual and unprofessional. Skills section reads as manual labor ("Long hour shifts | Withstand extreme heat environments") — applied for insurance role but resume tone is warehouse/delivery. No quantified metrics. Real employers but wrong-industry entirely. Low effort.'),
    ('Anthony Vela', 45, 'Severe formatting problems — half the text is ALL CAPS (bullets), header shows "A V NTHONY ELA" spacing artifact. But content has some insurance tailoring ("HIGH-NET-WORTH INDIVIDUALS... LIFE INSURANCE PROTECTION"). Real metrics (call-to-appointment ratios, conversion percentages). 14 years sales experience genuine. Tony Robbins training listed 4 times (excessive). Real employers. Content is decent tailored but presentation is problematic — the ALL CAPS is a real readability issue.'),
    ('April Varian', 40, 'Length appropriate. Zero SF/insurance tailoring — all warehouse/logistics/inventory management. Grove City OH location, not TX (not commutable). Generic "Results-driven professional" opener. Warehouse content very different domain from agency insurance. Real employers, clean formatting. Professional but wrong-domain, no tailoring.'),
    ('Bob Williams', 20, 'Zero SF/insurance tailoring — Amazon delivery + choir teacher + opera transport + pizza chef + Arby''s cook. Multiple typos: "I delivery Amazon packages", "tosser the dough", "FOH amd drive thru". Self-superiority language: "My work was considered superior among my musical colleagues." Music Master''s degrees not aligned with insurance. Recent role is Amazon delivery driver. Low effort, multiple typos, wrong industry entirely.'),
    ('Cheryl Hemphill', 55, 'Some insurance tailoring — current role Insurance Sales Agent at Globe Life-American Income Life, mentions "Licensed General Lines Agent". Real institutions (Globe Life, ExcelPros, Odessa College, UT Austin Full Stack). Skills include CRM and remote sales. BUT mixed with unrelated PT Assistant background (16 years) and QA/Business Analyst at ExcelPros. Formatting has issues (columns broken, hard to read). Moderate effort — insurance tailoring is real but presentation is muddled.'),
    ('Jakirah Goolsby', 68, 'Insurance-industry tailored — current SDR at Trellis (insurance), prior Allstate agent 2020-2023, QuoteWizard Sales Ops Team Lead. Specific quantified claims ($100K+ monthly premium, 95% lead efficiency, 15-20% close rates, 50+ employees coached, 25% bundling rate, 80-90% retention). Real employers, real school (Mercer University BBA). Multi-state P&C license. Clean formatting. Good effort with insurance tailoring and strong quantification.'),
    ('Matthew Carlton', 60, 'Insurance-tailored ("Licensed in Property, Casualty, Life and Health Insurance, I am eager to bring over 20 years..."). Multiple relevant licenses (TX P&C, TX Life/Health, AHIP Medicare 2025-2026, AML, ACA FFM). Current role Health & Life Insurance Broker at 360 Benefit Solutions. Mixed with real estate experience (2012-2024) — real estate not aligned with SF specifically but sales-adjacent. Generic buzzword-heavy skills section. Real employers (Cadwell Banker, REMAX, MarketAmerica). Solid insurance-tailored effort.'),
    ('Priscilla Brito', 50, 'Some SF connection — 4 years as State Farm Customer Service Rep for Andrew Hernandez (2012-2016). Recent role On The Move Inc Business Development Manager. Insurance certifications listed (TX P&C, Life TX/MO/CO). Career highlight claim ("closed the biggest account in company history") is bold but unverifiable. Generic skills list. Basic formatting, simple contact section. Moderate — has real SF experience but light tailoring for this specific role.'),
    ('Randy Castle', 22, 'Zero SF/insurance tailoring — Synergy Refrigeration dispatcher current, prior property porter/groundskeeper, service manager auto dealer, oil field trucking dispatcher. No numbers, no metrics. Generic personal statement. Self-superiority language: "Recognition for being the Top Service Manager in not only Sales Performance but Customer Service." Formatting is broken (weird section splits, contact info sandwiched mid-page). Wrong industry, self-promotion oddities, low effort.'),
    ('Richard Casias', 30, 'Short (1,694 chars) for described career. Zero SF/insurance tailoring — DIRECTV Inbound sales current, prior Cash America pawn shop, Twisted Tattoo, Wingstop. Very short bullet points, minimal detail per role. Generic objective. One specific claim ("Gun Forms 4473 100% to ATF Standards"). Currently studying IT/Cyber Security — different direction from insurance. Low effort, minimal content depth.'),
    ('Vicken Shakarian', 25, 'Short (2,030 chars). Zero SF/insurance tailoring — Remote Purchasing Assistant at Common Hype (streetwear), prior La Costa Glen supervisor, side project VickKicks. San Diego CA — not TX. HS graduate 2016 only (no college). Buzzword-only skills grid ("Team Building, Client Coordination, Professional Communication, Organizational Leadership") — exactly the low-effort pattern the framework flags. Wrong location, wrong industry, low effort.'),
    ('Cassandra Alves', 45, 'Length appropriate. PDF extraction has messy Indeed template artifacts (broken columns) — not the candidate''s fault but shows Indeed-generated. Zero SF/insurance tailoring — retail/customer service background at generic employers. Bilingual (Portuguese native, Spanish basic). Real school (Texas Tech, Media & Communication Studies with Advertising minor). Generic profile. Moderate template resume, no role-specific tailoring.'),
    ('John Kostov', 55, 'Very long (6,095 chars) — appropriate for 15+ year career. Zero SF/insurance tailoring — customer relationship management, property management, cleaning services. Indeed Assessments included at bottom (Planning & Execution: Proficient) — took extra step to include validated skills tests. Real employers (Royal ReFresh vending, SBM Management). Detailed bullets per job with genuine specifics. Good effort but not tailored to SF specifically.'),
    ('Stephanie Rogers', 42, 'Length 2,028 chars. PDF/Indeed template artifacts (| for I). Zero SF/insurance tailoring — child care and developmentally appropriate activities background. Generic "people-focused professional" opener. Skills adjacent to teaching/coordination not insurance. Real employers. Basic formatting. Moderate, no tailoring, template-heavy.'),
    ('Thomas Lynch', 62, 'Insurance-tailored objective ("seeking a challenging position in insurance"). Insurance-adjacent experience (Accident Investigation, LEAMS/FR300, Accident Reconstruction training). Merchant Marine background — unique detail. Real institutions. Generic "Areas of Strength" list with buzzword items. Length appropriate. Good insurance tailoring in objective, some adjacent skills. Solid effort.')
  ) AS t(name, score, reason)
)
UPDATE public.hiring_candidates hc
SET resume_analysis =
  hc.resume_analysis
  || jsonb_build_object(
       'signals',
       hc.resume_analysis->'signals' || jsonb_build_object(
         'effort',
         jsonb_build_object('score', es.score::numeric, 'reason', es.reason)
       )
     )
  || jsonb_build_object(
       'avg',
       round(
         ((SELECT COALESCE(SUM((v->>'score')::numeric), 0)
           FROM jsonb_each(hc.resume_analysis->'signals') AS sig(k,v)
           WHERE sig.k != 'effort'
         ) + es.score) / 12.0,
         0
       )
     )
  || jsonb_build_object('effort_backfilled_at', to_jsonb(NOW()::text))
FROM effort_scores es
WHERE hc.agency_id='126794dd-25ff-47d2-a436-724499733365'
  AND hc.candidate_name = es.name;
