INSERT INTO public.interview_questions
(agency_id, code, construct, subconstruct, question_kind, question_text, listen_for,
 concern, followups, selection_mode, trigger_codes, est_minutes, priority, source, notes)
VALUES
('126794dd-25ff-47d2-a436-724499733365','LG_LC_1','character','concern_for_others','background',
 $q$What will your last supervisor tell me about your strengths and challenges related to relationships with other team members?$q$,
 $q$Warm, specific relationship evidence$q$,$q$Task-only framing; people are friction$q$,
 ARRAY[$q$Which will your references use: (a) warm, expressive, genuine interest in people, drop what you are doing to help a friend; or (b) controlled emotionally, task-focused, time-management focused?$q$],
 'legacy_triggered',ARRAY['L_LOW_COMPASSION'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LC_2','character','concern_for_others','background',
 $q$What would your supervisor tell me about any coaching you needed on time management?$q$,
 $q$Balanced — makes time for people AND the work$q$,$q$Efficiency at the expense of every human interaction$q$,
 ARRAY[$q$Who is your best friend? If I asked them to describe you, what words would they use?$q$,
       $q$What is the nicest thing you have done for someone recently?$q$],
 'legacy_triggered',ARRAY['L_LOW_COMPASSION'],2.5,48,'final_interview_manual',
 $q$Best-friend words — low compassion: hard worker, organized, efficient, likes toys. High: warm, sensitive, good listener, caring$q$),
('126794dd-25ff-47d2-a436-724499733365','LG_LC_3','capability','customer_service','exercise',
 $q$Demonstrate how you handle a customer who is talking too much about unrelated topics and you pleasantly move the conversation along.$q$,
 $q$Redirects with warmth intact$q$,$q$Cuts them off cold, or cannot redirect at all$q$,
 '{}','legacy_triggered',ARRAY['L_LOW_COMPASSION'],3.0,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_HC_1','capability','communication','past_behavior',
 $q$Tell me about a coaching session you might have had regarding controlling the length of your conversations with customers.$q$,
 $q$Aware, has been coached, has a control mechanism$q$,$q$Conversations run long and nobody has ever reined it in$q$,
 ARRAY[$q$Which will your references use: (a) warm, expressive, genuine interest, drop everything to help; or (b) controlled, task-focused, time-management focused? (For high compassion, (b) is a good sign they have overcome the natural tendency.)$q$],
 'legacy_triggered',ARRAY['L_HIGH_COMPASSION'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HC_2','capability','composure','past_behavior',
 $q$Tell me about a coaching session regarding how you quickly rebound from rejection and criticism.$q$,
 $q$Rebounds fast; has worked at it$q$,$q$Takes rejection personally and slowly$q$,
 ARRAY[$q$What words would your best friend use to describe you?$q$],
 'legacy_triggered',ARRAY['L_HIGH_COMPASSION'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HC_3','capability','customer_service','exercise',
 $q$Demonstrate handling a customer who is talking too much — how do you pleasantly move the conversation along?$q$,
 $q$Kind and effective redirect$q$,$q$Cannot bring themselves to redirect$q$,
 '{}','legacy_triggered',ARRAY['L_HIGH_COMPASSION'],3.0,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_LSP_1','capability','coachability','background',
 $q$What would your current or previous supervisor tell me about any coaching you needed on meeting sales goals or activity targets?$q$,
 $q$Owns the coaching history plainly$q$,$q$Claims none — or targets quietly missed$q$,
 '{}','legacy_triggered',ARRAY['L_LOW_SELFPROMO'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LSP_2','capability','composure','background',
 $q$What would they tell me about coaching on quickly rebounding from rejection and criticism?$q$,
 $q$Evidence of a built rebound reflex$q$,$q$Rejection quietly accumulates$q$,
 ARRAY[$q$What words would your best friend use about how you deal with disappointment and criticism? (Looking for: rebounds quickly, does not let things bother them.)$q$],
 'legacy_triggered',ARRAY['L_LOW_SELFPROMO'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LSP_3','capability','composure','background',
 $q$Describe your thought process for getting your confidence back when you lose a sale or when a prospect tells you they are not interested.$q$,
 $q$A named, repeatable process$q$,$q$No process — confidence is weather$q$,
 ARRAY[$q$Describe a coaching session with your manager regarding rebounding from rejection.$q$],
 'legacy_triggered',ARRAY['L_LOW_SELFPROMO'],2.5,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_HSP_1','character','personal_responsibility','past_behavior',
 $q$Tell me about a time in your life when you made a mistake that caused a challenging problem. What did you do? What do you wish you had done differently?$q$,
 $q$Admits the mistake cleanly with a real do-differently$q$,
 $q$Struggling to admit a mistake = struggling to be coached$q$,
 ARRAY[$q$Describe a situation where some aspect of a work project was overlooked. Causes? Your response?$q$],
 'legacy_triggered',ARRAY['L_HIGH_SELFPROMO'],3.0,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HSP_2','capability','coachability','background',
 $q$What is one area of your life where you are working hard to improve a personal habit?$q$,
 $q$A real habit under active work$q$,$q$Nothing to improve — self-image will not admit it$q$,
 ARRAY[$q$Would your last supervisor tell me your strengths? Your areas for improvement? (Struggling to admit weakness = struggling to be coached.)$q$],
 'legacy_triggered',ARRAY['L_HIGH_SELFPROMO'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HSP_3','capability','coachability','background',
 $q$If I check your references, how often did you have coaching sessions with your supervisor? What areas did you receive coaching in?$q$,
 $q$Normal coaching cadence, named areas$q$,$q$"Never needed coaching" — the references will disagree$q$,
 ARRAY[$q$Describe an area in any job where you were required to adhere to strict policy and procedure. Describe any coaching from a failure to follow procedures.$q$,
       $q$I am going to read some words and phrases. Tell me how familiar you are, 0 to 5: Photon, Redemptive Analysis, Cranium, Prespect, Pristine. (Redemptive Analysis and Prespect are not real — rating them above 0 is dishonest.)$q$],
 'legacy_triggered',ARRAY['L_HIGH_SELFPROMO'],2.5,46,'final_interview_manual',NULL);
