-- v2 assessment: IPIP-NEO facet ingest batch B — Friendliness, Dutifulness, Achievement-Striving,
-- Self-Discipline, Cautiousness. Source: ipip.ori.org/newNEOKey.htm, public domain, item text +
-- keying verbatim from source. All 10 items per facet, scale_max=5, Stint 2.

INSERT INTO public.hiregauge_instrument_items (
  section, item_number, hypothesized_trait, item_text, reverse_coded, scale_max, stint, choices, notes
) VALUES
-- FRIENDLINESS (E1, alpha=.87) — items 159-168
('newtworks_v2_personality', 159, 'friendliness', 'Make friends easily.',                              false, 5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 1/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 160, 'friendliness', 'Warm up quickly to others.',                        false, 5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 2/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 161, 'friendliness', 'Feel comfortable around people.',                   false, 5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 3/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 162, 'friendliness', 'Act comfortably with others.',                      false, 5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 4/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 163, 'friendliness', 'Cheer people up.',                                  false, 5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 5/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 164, 'friendliness', 'Am hard to get to know.',                           true,  5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 6/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 165, 'friendliness', 'Often feel uncomfortable around others.',           true,  5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 7/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 166, 'friendliness', 'Avoid contacts with others.',                       true,  5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 8/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 167, 'friendliness', 'Am not really interested in others.',                true,  5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 9/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 168, 'friendliness', 'Keep others at a distance.',                        true,  5, 2, NULL, 'IPIP-NEO facet E1 Friendliness, item 10/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
-- DUTIFULNESS (C3, alpha=.71) — items 169-178
('newtworks_v2_personality', 169, 'dutifulness', 'Try to follow the rules.',                           false, 5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 1/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 170, 'dutifulness', 'Keep my promises.',                                  false, 5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 2/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 171, 'dutifulness', 'Pay my bills on time.',                              false, 5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 3/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 172, 'dutifulness', 'Tell the truth.',                                    false, 5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 4/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 173, 'dutifulness', 'Listen to my conscience.',                           false, 5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 5/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 174, 'dutifulness', 'Break rules.',                                       true,  5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 6/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 175, 'dutifulness', 'Break my promises.',                                 true,  5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 7/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 176, 'dutifulness', 'Get others to do my duties.',                        true,  5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 8/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 177, 'dutifulness', 'Do the opposite of what is asked.',                  true,  5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 9/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 178, 'dutifulness', 'Misrepresent the facts.',                            true,  5, 2, NULL, 'IPIP-NEO facet C3 Dutifulness, item 10/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
-- ACHIEVEMENT-STRIVING (C4, alpha=.78) — items 179-188
('newtworks_v2_personality', 179, 'achievement_striving', 'Go straight for the goal.',                 false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 1/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 180, 'achievement_striving', 'Work hard.',                                false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 2/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 181, 'achievement_striving', 'Turn plans into actions.',                  false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 3/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 182, 'achievement_striving', 'Plunge into tasks with all my heart.',      false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 4/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 183, 'achievement_striving', 'Do more than what''s expected of me.',       false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 5/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 184, 'achievement_striving', 'Set high standards for myself and others.', false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 6/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 185, 'achievement_striving', 'Demand quality.',                            false, 5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 7/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 186, 'achievement_striving', 'Am not highly motivated to succeed.',       true,  5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 8/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 187, 'achievement_striving', 'Do just enough work to get by.',            true,  5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 9/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 188, 'achievement_striving', 'Put little time and effort into my work.',  true,  5, 2, NULL, 'IPIP-NEO facet C4 Achievement-Striving, item 10/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
-- SELF-DISCIPLINE (C5, alpha=.85) — items 189-198
('newtworks_v2_personality', 189, 'self_discipline', 'Get chores done right away.',                    false, 5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 1/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 190, 'self_discipline', 'Am always prepared.',                            false, 5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 2/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 191, 'self_discipline', 'Start tasks right away.',                        false, 5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 3/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 192, 'self_discipline', 'Get to work at once.',                           false, 5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 4/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 193, 'self_discipline', 'Carry out my plans.',                            false, 5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 5/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 194, 'self_discipline', 'Find it difficult to get down to work.',         true,  5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 6/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 195, 'self_discipline', 'Waste my time.',                                 true,  5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 7/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 196, 'self_discipline', 'Need a push to get started.',                    true,  5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 8/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 197, 'self_discipline', 'Have difficulty starting tasks.',                true,  5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 9/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 198, 'self_discipline', 'Postpone decisions.',                            true,  5, 2, NULL, 'IPIP-NEO facet C5 Self-Discipline, item 10/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
-- CAUTIOUSNESS (C6, alpha=.76) — items 199-208
('newtworks_v2_personality', 199, 'cautiousness', 'Avoid mistakes.',                                   false, 5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 1/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 200, 'cautiousness', 'Choose my words with care.',                        false, 5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 2/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 201, 'cautiousness', 'Stick to my chosen path.',                          false, 5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 3/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked +keyed.'),
('newtworks_v2_personality', 202, 'cautiousness', 'Jump into things without thinking.',                true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 4/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 203, 'cautiousness', 'Make rash decisions.',                              true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 5/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 204, 'cautiousness', 'Like to act on a whim.',                            true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 6/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 205, 'cautiousness', 'Rush into things.',                                 true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 7/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 206, 'cautiousness', 'Do crazy things.',                                  true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 8/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 207, 'cautiousness', 'Act without thinking.',                             true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 9/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.'),
('newtworks_v2_personality', 208, 'cautiousness', 'Often make last-minute plans.',                     true,  5, 2, NULL, 'IPIP-NEO facet C6 Cautiousness, item 10/10. ipip.ori.org/newNEOKey.htm, public domain. Source-marked -keyed.');
