INSERT INTO public.interview_questions
(agency_id, code, construct, subconstruct, question_kind, question_text, listen_for,
 concern, followups, selection_mode, trigger_codes, est_minutes, priority, source, notes)
VALUES
('126794dd-25ff-47d2-a436-724499733365','LG_LB_1','capability','teamwork','background',
 $q$Describe your most recent supervisor.$q$,
 $q$Balanced portrait — good and bad both present$q$,$q$Only faults — belief in others confirmed low$q$,
 ARRAY[$q$What would your supervisor tell me about coaching you received on getting along with team members?$q$],
 'legacy_triggered',ARRAY['L_LOW_BELIEF'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LB_2','capability','teamwork','past_behavior',
 $q$Describe the person at your most recent job with whom it was hardest to get along.$q$,
 $q$Fair to the difficult person; owns their half$q$,$q$The other person is a cartoon villain$q$,
 ARRAY[$q$Give me an example of a conflict with a team member and how you resolved it. (Responsibility, or blame?)$q$],
 'legacy_triggered',ARRAY['L_LOW_BELIEF'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LB_3','capability','customer_service','past_behavior',
 $q$Describe a time when a customer was not satisfied and became mad and irate. How did you respond?$q$,
 $q$Stayed generous toward the customer under fire$q$,$q$Contempt for the customer leaks through$q$,
 ARRAY[$q$Think about a time you began a new job with a new team. How did you transition, and how long to become effective?$q$],
 'legacy_triggered',ARRAY['L_LOW_BELIEF'],2.5,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_HB_1','capability','communication','background',
 $q$Describe your most recent supervisor.$q$,
 $q$Balances good and bad points$q$,$q$Only sees good and ignores challenges — naivety risk$q$,
 ARRAY[$q$Describe the person at your most recent job with whom it was hardest to get along. (Balanced view, or unrealistic "everyone was so nice"?)$q$],
 'legacy_triggered',ARRAY['L_HIGH_BELIEF'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HB_2','capability','composure','past_behavior',
 $q$Describe a time in your life when someone took advantage of your generosity. How often does this happen?$q$,
 $q$Aware of the pattern; has boundaries now$q$,$q$Happens often and they have not adjusted$q$,
 ARRAY[$q$Any coaching you received on being too trusting or naive?$q$],
 'legacy_triggered',ARRAY['L_HIGH_BELIEF'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HB_3','capability','sales_skill','exercise',
 $q$Demonstrate how you handle the price objection. When a prospect says "you are too expensive" — what do you say?$q$,
 $q$Holds the price with value, not apology$q$,$q$Caves immediately — too trusting of the pushback$q$,
 ARRAY[$q$Time when a customer was mad and irate — how did you respond?$q$],
 'legacy_triggered',ARRAY['L_HIGH_BELIEF'],3.0,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_LO_1','character','concern_for_others','background',
 $q$Who has encouraged you the most in life, helped you feel good about yourself, and helped you believe you can accomplish anything?$q$,
 $q$Names someone real with warmth$q$,$q$Struggles to name anyone$q$,
 '{}','legacy_triggered',ARRAY['L_LOW_OPTIMISM'],2.5,50,'final_interview_manual',
 $q$Manual note: low optimism rarely names a parent; usually a teacher, coach, or grandparent$q$),
('126794dd-25ff-47d2-a436-724499733365','LG_LO_2','capability','composure','background',
 $q$Do you believe most people control their own destiny, or that most people's lives are controlled by random events?$q$,
 $q$Control own destiny$q$,$q$Random events — pessimistic frame$q$,
 ARRAY[$q$Do you believe nearly all bad things result in something positive, or that bad things mostly stay bad?$q$,
       $q$Do you believe nearly anyone can succeed even in difficult circumstances, or that most people need lucky breaks?$q$],
 'legacy_triggered',ARRAY['L_LOW_OPTIMISM'],2.0,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LO_3','commitment','motivation_level','background',
 $q$What do you think has the greatest impact on a person's success?$q$,
 $q$Own hard work, effort, decisions$q$,$q$Luck, the stars$q$,
 '{}','legacy_triggered',ARRAY['L_LOW_OPTIMISM'],2.0,46,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LO_4','commitment','role_attitude','background',
 $q$Describe where you see yourself in 5 years and the plan for getting there.$q$,
 $q$Concrete plans$q$,$q$Vague, floating$q$,
 '{}','legacy_triggered',ARRAY['L_LOW_OPTIMISM'],2.5,44,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_HO_1','capability','organization_detail','background',
 $q$Describe the community activities you are currently involved in.$q$,
 $q$Involved but bounded$q$,$q$Overcommitted — cannot say no$q$,
 '{}','legacy_triggered',ARRAY['L_HIGH_OPTIMISM'],2.0,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HO_2','capability','composure','background',
 $q$Do you have anything going on in your life right now that causes you to come to work tired and stressed?$q$,
 $q$Honest, managed load$q$,$q$Overload denied or unmanaged$q$,
 ARRAY[$q$Describe a recent challenge at your job. What did you do? How long to realize the challenge, and how long to solve it?$q$],
 'legacy_triggered',ARRAY['L_HIGH_OPTIMISM'],2.0,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HO_3','capability','organization_detail','background',
 $q$In your last sales job, aside from sales, describe any other job duties.$q$,
 $q$Kept the selling job the job$q$,$q$Could not say no to non-sales asks — selling time eroded$q$,
 ARRAY[$q$Describe a time you over-promised services to a customer. What did you do to satisfy them, and what would your previous manager say about coaching on impossible commitments?$q$],
 'legacy_triggered',ARRAY['L_HIGH_OPTIMISM'],2.5,46,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HO_4','capability','communication','exercise',
 $q$Describe how you say no to someone who asks you to do something outside your responsibility.$q$,
 $q$Can actually produce the no, kindly$q$,$q$Cannot say no — over-promising confirmed$q$,
 '{}','legacy_triggered',ARRAY['L_HIGH_OPTIMISM'],2.0,44,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_LSS_1','capability','learning_cognition','background',
 $q$What is the most complex task you have had to learn in a previous job? Have you ever had a job as complex as this one?$q$,
 $q$Has learned genuinely complex work before$q$,$q$Nothing comparable — licensing and product complexity are a real risk$q$,
 '{}','legacy_triggered',ARRAY['L_LSS_SPEED'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_LSS_2','capability','learning_cognition','background',
 $q$What is 10% of $492.50? If you are traveling 50 miles per hour, how far do you travel in 60 minutes?$q$,
 $q$$49.25 and 50 miles, answered without visible strain$q$,$q$Wrong or slow on basic arithmetic$q$,
 ARRAY[$q$What was your ACT score? (Average is 21.) What was your SAT score? (Average is 1059.)$q$,
       $q$What grades were on your high school transcript? What were your grades in math?$q$],
 'legacy_triggered',ARRAY['L_LSS_SPEED'],2.5,48,'final_interview_manual',
 $q$Math correlates with reasoning, which correlates with explaining complex info to customers$q$),
('126794dd-25ff-47d2-a436-724499733365','LG_LSS_3','capability','learning_cognition','background',
 $q$What are the last two books you have read? What did you learn? How do you keep up with current events?$q$,
 $q$Real recent reading with retained content$q$,$q$Cannot name a recent book or a current event$q$,
 '{}','legacy_triggered',ARRAY['L_LSS_SPEED'],2.0,46,'final_interview_manual',NULL);
