-- Migration: morning_recap_departed_sp_silent_in_total
-- Version: 20260702135837
-- Applied via Supabase MCP apply_migration
-- NOTE: History stub. Final body in functions_2026-07-02.sql.
-- Change: Departed SP added silently to team total (no per-line entry);
--         active-only line items in morning recap block.
