-- Migration: extract_render_team_status_block_and_dry_callers
-- Version: 20260702145327
-- Applied via Supabase MCP apply_migration
-- NOTE: History stub. Full CREATE OR REPLACE bodies in functions_2026-07-02.sql.
-- Change: Extracted shared render_team_status_block() function (4 args:
--         agency_id, as_of_date, fresh_type, header_label); returns
--         block_text + totals + counts. Rewired team_checkin_send_reminder
--         and team_checkin_compile_results to call it. Single source of truth
--         for team status display.
