INSERT INTO public.interview_questions
(agency_id, code, construct, subconstruct, question_kind, question_text, listen_for,
 concern, followups, selection_mode, trigger_codes, est_minutes, priority, source, notes)
VALUES
('126794dd-25ff-47d2-a436-724499733365','BANK_VERIFY_PROUDEST','character','honesty','past_behavior',
 $q$Pick the accomplishment on your resume you are most proud of. Walk me through it in detail — dates, numbers, who else was involved, and who could confirm it.$q$,
 $q$Immediate concrete detail; volunteers a name we can call$q$,
 $q$Vague, shifting details, reluctance to name a verifier$q$,
 ARRAY[$q$If I call that person, what will they say your exact contribution was?$q$],
 'triggered',ARRAY['T_IM_ELEVATED','T_RES_HONESTY_LOW'],4.0,55,'authored_2026_08',
 $q$Verification-demand format constrains interview faking (Levashina and Campion 2007)$q$),

('126794dd-25ff-47d2-a436-724499733365','BANK_WEAKNESS_REAL','character','honesty','background',
 $q$Tell me something you are genuinely not good at yet that matters for this job, and what you are doing about it.$q$,
 $q$Real weakness plus concrete current work on it$q$,
 $q$Humble-brag or claims none$q$,
 '{}','triggered',ARRAY['T_IM_ELEVATED'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_TRUTH_COST','character','honesty','past_behavior',
 $q$Tell me about a time telling the truth cost you something.$q$,
 $q$Real cost, told it anyway, no regret about the honesty itself$q$,
 $q$Cannot produce one, or the story shows the truth was optional$q$,
 '{}','triggered',ARRAY['T_INTEGRITY_FLAG'],3.5,55,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_PRESSURE_BEND','character','honesty','past_behavior',
 $q$Tell me about a time you were pressured to cut a corner or bend a rule at work. What did you do?$q$,
 $q$Named the pressure, held the line, accepted the consequence$q$,
 $q$Went along with it, or reframes the bend as harmless$q$,
 '{}','triggered',ARRAY['T_INTEGRITY_FLAG'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_STAY_THREE_YEARS','commitment','motivation_level','background',
 $q$Looking at your last three roles — what made each one end? And what would need to be true here for you to still be here in three years?$q$,
 $q$Clean, ownable exit reasons; realistic stay conditions we can actually meet$q$,
 $q$A pattern of blame or boredom exits; stay conditions we cannot meet$q$,
 '{}','triggered',ARRAY['T_CHURN_RISK'],4.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_GATED_AREA','capability','coachability','past_behavior',
 $q$The assessment flagged one area for us to talk through together — it is on my sheet. Walk me through a recent, real example of you handling exactly that kind of situation.$q$,
 $q$Engages the flag directly with a specific recent example$q$,
 $q$Deflects the flag or argues with the assessment instead of answering$q$,
 '{}','triggered',ARRAY['T_COMPETENCY_GATE'],4.0,50,'authored_2026_08',
 $q$The fired gate name is in the evidence line on the plan sheet — read it to the candidate$q$),

('126794dd-25ff-47d2-a436-724499733365','BANK_GAP_COMMIT','commitment','motivation_level','past_behavior',
 $q$What is a commitment you made in the last two years that nobody was checking on — and what happened to it?$q$,
 $q$Unmonitored commitment, kept$q$,
 $q$Only externally-enforced commitments, or it quietly died$q$,
 '{}','triggered',ARRAY['T_GAP_COMMITMENT'],3.5,50,'authored_2026_08',
 $q$Fired because resume and assessment disagree on commitment$q$),

('126794dd-25ff-47d2-a436-724499733365','BANK_GAP_CHAR','character','honesty','background',
 $q$When we call your references, where will their description of you differ most from how you have described yourself today?$q$,
 $q$Names a real difference before we find it$q$,
 $q$"No differences" — nobody's self-report matches their references perfectly$q$,
 '{}','triggered',ARRAY['T_GAP_CHARACTER'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_SALES_NUMBERS','capability','sales_skill','background',
 $q$Take your best sales result on the resume. Rebuild the math for me: the quota, your number, the timeframe, how it was measured, and who can confirm it.$q$,
 $q$The math holds together and a verifier is named$q$,
 $q$Numbers wobble under arithmetic, measurement is fuzzy, no verifier$q$,
 '{}','triggered',ARRAY['T_SALES_CLAIM_UNSUPPORTED'],4.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_HARD_TEST','capability','learning_cognition','past_behavior',
 $q$This seat requires passing a state licensing exam in the first weeks — closed book, timed. Tell me about the last time you had to study for and pass a hard test. How did you prepare, and how did it go?$q$,
 $q$Real study system, passed, can describe the method$q$,
 $q$No recent example, or failed without a changed approach$q$,
 '{}','triggered',ARRAY['T_GMA_LOW'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_JUDGMENT_SCENARIO','capability','customer_service','situational',
 $q$A customer calls upset mid-claim. They want you to promise the claim will be approved, and they say they will leave the agency if you cannot. What exactly do you say?$q$,
 $q$Empathy plus honesty: no promised outcome, explains the adjuster's role, offers to advocate and escalate$q$,
 $q$Promises or implies an outcome, or gets defensive$q$,
 '{}','triggered',ARRAY['T_SJT_LOW'],3.5,50,'authored_2026_08',
 $q$Correct answer: we can advocate, escalate, translate — never decide or promise a claim outcome$q$),

('126794dd-25ff-47d2-a436-724499733365','BANK_ROUTINE','capability','organization_detail','background',
 $q$Walk me through how you organized your last full workweek. What did you do when nobody set your schedule for you?$q$,
 $q$A real self-built system, kept without supervision$q$,
 $q$Waits to be scheduled; the week just happens to them$q$,
 '{}','triggered',ARRAY['T_LOW_SELF_DISCIPLINE'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_RAISED_BAR','commitment','motivation_level','past_behavior',
 $q$Tell me about a time you hit a target and then raised your own bar. If nothing comes to mind — what target are you working toward right now?$q$,
 $q$Self-raised targets, current one exists and is specific$q$,
 $q$Targets only ever set by others; no current one$q$,
 '{}','triggered',ARRAY['T_LOW_ACHIEVEMENT'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_PROMISE_KEPT','character','personal_responsibility','past_behavior',
 $q$Tell me about a commitment you kept when it stopped being convenient.$q$,
 $q$Real inconvenience, kept anyway, no self-congratulation$q$,
 $q$Cannot produce one, or renegotiated the moment it got hard$q$,
 '{}','triggered',ARRAY['T_LOW_DUTIFULNESS'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_UNDER_FIRE','capability','composure','past_behavior',
 $q$Describe your worst day at work in the last year. What did the people around you see?$q$,
 $q$Honest about the internal storm, composed on the outside, recovered$q$,
 $q$Leaked it onto customers or teammates, or claims no bad days$q$,
 '{}','triggered',ARRAY['T_LOW_EMOTIONAL_STABILITY'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_ASKED_HARD','capability','sales_skill','past_behavior',
 $q$Tell me about the last time you asked someone for something they were likely to say no to. How did you ask, and what happened?$q$,
 $q$Asked directly, recently, handled the no$q$,
 $q$Avoids asking; the example is old or soft$q$,
 '{}','triggered',ARRAY['T_LOW_ASSERTIVENESS_V2'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_READ_THE_ROOM','character','concern_for_others','past_behavior',
 $q$Tell me about a time you realized mid-conversation that the other person needed something different than what you were giving. What did you notice, and what did you change?$q$,
 $q$Noticed a real cue, adjusted for the other person's need$q$,
 $q$Cannot produce one — conversations are broadcast, not listening$q$,
 '{}','triggered',ARRAY['T_LOW_COMPASSION_V2'],3.5,50,'authored_2026_08',
 $q$Concern for Others is a character floor trait — a red here is hire-blocking$q$),

('126794dd-25ff-47d2-a436-724499733365','BANK_CONFLICT_RESOLVE','capability','teamwork','past_behavior',
 $q$Give me a conflict with a teammate that you handled badly at first. What turned it around?$q$,
 $q$Owns the bad first move; a real repair happened$q$,
 $q$No conflict ever, or the repair was the other person apologizing$q$,
 '{}','triggered',ARRAY['T_LOW_COOPERATION'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_CUSTOMER_EXTRA','capability','customer_service','past_behavior',
 $q$Tell me about the last time you did something for a customer you did not have to do. What made you do it?$q$,
 $q$Recent, specific, motivated by the customer not the metric$q$,
 $q$Cannot recall one, or it was really about hitting a number$q$,
 '{}','triggered',ARRAY['T_LOW_CUSTOMER_ORIENTATION'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_UNASKED','capability','initiative_autonomy','past_behavior',
 $q$Tell me about something you built, fixed, or started that nobody asked you to.$q$,
 $q$Self-initiated, finished, mattered$q$,
 $q$Everything on the resume was assigned$q$,
 '{}','triggered',ARRAY['T_LOW_PROACTIVE'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_WHY_SELLING','commitment','role_attitude','motivation',
 $q$Selling means hearing no most of the day and getting paid on results. What about that life appeals to you — honestly?$q$,
 $q$Eyes-open appeal to the real trade: autonomy, upside, scoreboard$q$,
 $q$Wants the paycheck shape but not the work shape$q$,
 '{}','triggered',ARRAY['T_LOW_ENTERPRISING'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_COACHING_TAKEN','capability','coachability','past_behavior',
 $q$Tell me about the most useful criticism you have ever received. What did you do with it?$q$,
 $q$Specific criticism, visible behavior change after$q$,
 $q$Cannot name one, or reframes all criticism as unfair$q$,
 '{}','triggered',ARRAY['T_AVOID_GOAL_HIGH'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_DOUBT_DID_IT','capability','initiative_autonomy','past_behavior',
 $q$Tell me about a time you took something on that you were not sure you could do. How did it go?$q$,
 $q$Stepped in despite doubt, found a way$q$,
 $q$Only takes on sure things$q$,
 '{}','triggered',ARRAY['T_LOW_SELF_EFFICACY'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_SHIP_IT','capability','initiative_autonomy','past_behavior',
 $q$Tell me about a decision you made with incomplete information because waiting was worse. How did you decide that enough was enough?$q$,
 $q$Can articulate the cutoff and lives with the call$q$,
 $q$Would still be gathering information today$q$,
 '{}','triggered',ARRAY['T_HIGH_CAUTIOUSNESS'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_FINISHED_IT','commitment','motivation_level','past_behavior',
 $q$Pick something on your resume you started and finished completely. Walk me through the last ten percent.$q$,
 $q$Knows the boring finishing details$q$,
 $q$Vague on the ending; things get started but not landed$q$,
 '{}','triggered',ARRAY['T_RES_FOLLOW_THROUGH_LOW'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_DIRECTION','commitment','role_attitude','background',
 $q$Where is your career pointed? If this seat is a step, a step toward what?$q$,
 $q$A direction this seat genuinely serves, stated plainly$q$,
 $q$No direction, or a direction this seat clearly does not serve$q$,
 '{}','triggered',ARRAY['T_RES_TRAJECTORY_LOW'],3.0,50,'authored_2026_08',
 $q$Direction uncertainty is a framework decline reason$q$),

('126794dd-25ff-47d2-a436-724499733365','BANK_WHY_THIS_SEAT','commitment','role_attitude','background',
 $q$Of everything you could apply to, why this seat at this agency? And what else are you interviewing for right now?$q$,
 $q$A specific reason for us; honest about the field$q$,
 $q$We are one of forty applications and it shows$q$,
 '{}','triggered',ARRAY['T_RES_COHERENT_PURSUIT_LOW'],3.0,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_EXITS','character','personal_responsibility','background',
 $q$Walk me through why each of your last three roles ended, one by one.$q$,
 $q$Clean, consistent, ownable reasons$q$,
 $q$Blame in every exit, or the stories shift under mild pressure$q$,
 '{}','triggered',ARRAY['T_RES_RESPONSIBILITY_LOW'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_TRANSFER','capability','sales_skill','past_behavior',
 $q$You have not sold for a living. What is the closest you have come to persuading someone to a yes with something real at stake — and what makes you think it transfers?$q$,
 $q$A genuine persuasion event with stakes, plus a realistic transfer theory$q$,
 $q$No persuasion history at all, or "I am a people person" as the whole theory$q$,
 '{}','triggered',ARRAY['T_RES_NO_SALES_HISTORY'],3.5,50,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_LEADERSHIP_PROOF','capability','teamwork','past_behavior',
 $q$Your resume shows leadership. Give me the hardest people decision you were part of, and your exact role in it.$q$,
 $q$Real weight-bearing role in a hard call$q$,
 $q$Leadership turns out to mean seniority or a title$q$,
 '{}','triggered',ARRAY['T_RES_LEADERSHIP_CLAIM'],3.0,45,'authored_2026_08',NULL),

('126794dd-25ff-47d2-a436-724499733365','BANK_VALIDITY_SELFREAD','character','honesty','background',
 $q$On the assessment, some of your answers pulled in different directions. Where do you think that came from?$q$,
 $q$Curious, non-defensive self-read; a plausible honest account$q$,
 $q$Defensive, or blames the test$q$,
 '{}','triggered',ARRAY['L_VALIDITY'],3.0,55,'authored_2026_08',NULL);
