INSERT INTO public.interview_questions
(agency_id, code, construct, subconstruct, question_kind, question_text, listen_for,
 concern, followups, selection_mode, trigger_codes, est_minutes, priority, source, notes)
VALUES
('126794dd-25ff-47d2-a436-724499733365','U_COMM_ATTITUDE','commitment','role_attitude','motivation',
 $q$What do you like about insurance sales and the way we go about finding new customers?$q$,
 $q$Specific, informed appeal to the actual work — outreach, rejection, relationships$q$,
 $q$Generic "I like helping people" with no grasp of what the seat actually is$q$,
 ARRAY[$q$What are some things that bother you about the insurance industry?$q$,$q$Why do you want to be a salesperson?$q$],
 'universal_core','{}',3.0,100,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','U_CHAR_GRIT_HARDEST','character','hard_work_ethic','past_behavior',
 $q$Tell me about the hardest thing you have ever accomplished. Walk me through it start to finish — including the point where you almost quit.$q$,
 $q$Genuinely hard thing, honest near-quit moment, finished it$q$,
 $q$No near-quit moment: either nothing genuinely hard attempted, or cannot be honest about struggle$q$,
 ARRAY[$q$What is your definition of hard work ethic, and who taught you it?$q$],
 'universal_core','{}',4.0,98,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','U_COMM_GRIT_LONGARC','commitment','motivation_level','past_behavior',
 $q$Tell me about a goal you set for yourself that took more than a year of consistent effort. What kept you going through the boring middle?$q$,
 $q$Self-imposed multi-year goal with no external accountability$q$,
 $q$Only jobs or degrees with a boss or school watching — weak evidence$q$,
 '{}','universal_core','{}',4.0,96,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','U_COMM_GRIT_REJECTION','commitment','motivation_level','past_behavior',
 $q$Tell me about the worst rejection you have ever handled. What did you do the next day?$q$,
 $q$Concrete rejection, fast concrete recovery action next day$q$,
 $q$Vague answer or "took a few days off" — no rejection-recovery reflex built yet$q$,
 '{}','universal_core','{}',3.5,94,'final_interview_manual',
 $q$Manual note: single most predictive question for insurance-sales survival$q$),

('126794dd-25ff-47d2-a436-724499733365','U_CHAR_HONESTY','character','honesty','situational',
 $q$Describe an unethical sales behavior. Are there times it might be OK if it helps close the sale?$q$,
 $q$Clear no, never — stated without hedging$q$,
 $q$Any hedging, any "depends on the situation"$q$,
 ARRAY[$q$Is it OK to exaggerate what a product does in order to sell it? As long as it helps the customer, what does it matter?$q$],
 'universal_core','{}',3.0,92,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','U_CHAR_CONCERN','character','concern_for_others','past_behavior',
 $q$Tell me about the last time you sat and listened to someone who needed advice on a real problem. Why was it important?$q$,
 $q$Real recent instance, listening first, the other person at the center$q$,
 $q$Cannot recall one, or the story is really about themselves$q$,
 ARRAY[$q$What is the nicest thing you have done for someone recently?$q$,$q$What is one thing you enjoy doing for other people?$q$],
 'universal_core','{}',3.0,90,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','U_CHAR_GRIT_FAIL','character','personal_responsibility','past_behavior',
 $q$Describe a time you failed at something that really mattered to you. What did you do after?$q$,
 $q$Owns the failure, names their part, concrete corrective action after$q$,
 $q$Immediate blame on others or circumstance — fails the Personal Responsibility floor, no override$q$,
 ARRAY[$q$Tell me about a time you were given an important task and did not meet expectations. What should you have done differently?$q$],
 'universal_core','{}',4.0,88,'final_interview_manual',
 $q$If "nothing comes to mind" on the follow-up — that IS the answer$q$),

('126794dd-25ff-47d2-a436-724499733365','U_COMM_OWN_PRODUCTS','commitment','product_buy_in','motivation',
 $q$If you take this role, are you willing to move all your insurance products to our agency? And what do you like about our products or company that made you apply here instead of a competitor?$q$,
 $q$Unhesitating yes, plus something specific about this agency$q$,
 $q$Hesitation on moving products; on a parent's policy is a red flag on its own$q$,
 ARRAY[$q$Are you in a situation in life where you can purchase your own auto policy and a renters or homeowners policy?$q$],
 'universal_core','{}',3.0,86,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','U_COMM_MOTIVATION_TYPE','commitment','motivation_type','motivation',
 $q$Which is more important to you: money, competition, recognition, or duty and mission? Talk me through your top and your bottom pick.$q$,
 $q$Self-aware, specific ranking with real examples behind it$q$,
 $q$"All of them equally" — no self-knowledge of what actually drives them$q$,
 ARRAY[$q$Describe a competition you were in and where you finished. Do you compete regularly?$q$,
       $q$What recognition have you received in the past? Where did you put the trophy or plaque?$q$],
 'universal_core','{}',4.0,84,'final_interview_manual',
 $q$Grade ALL FOUR types from this answer per the locked Commitment definition$q$),

('126794dd-25ff-47d2-a436-724499733365','U_CAP_ROLEPLAY','capability','sales_skill','exercise',
 $q$Where is your favorite vacation spot? Sell me on going there. (After they present, ask price. Object to the price. Watch how they handle it.)$q$,
 $q$Asks questions first, presents to the answers, holds up under the price objection, asks for the yes$q$,
 $q$Feature dump with no discovery; folds or freezes at the objection$q$,
 '{}','universal_core','{}',4.0,82,'final_interview_manual',
 $q$Rate on the scorecard: needs discovery, presentation, closing, objection handling$q$),

('126794dd-25ff-47d2-a436-724499733365','S_CAP_TYPICAL_DAY','capability','organization_detail','background',
 $q$Describe what a typical day would look like if you come to work for us. Which tasks would stress you the most? Which the least?$q$,
 $q$Realistic picture of the seat; honest about a real stressor$q$,
 $q$No idea what the job is, or claims nothing would stress them$q$,
 '{}','universal_stretch','{}',3.0,60,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','S_CAP_LAST_JOB','capability','communication','background',
 $q$What did you like about your last job? What did you not like?$q$,
 $q$Balanced, specific, no trashing of the previous employer$q$,
 $q$All grievance, or all gloss — either way not a straight read$q$,
 '{}','universal_stretch','{}',3.0,58,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','S_COMM_INCOME_GOAL','commitment','motivation_level','motivation',
 $q$What amount do you desire to earn? Is it different from what you told me last time? Why? What current and long-term needs will be satisfied if you do this job well?$q$,
 $q$Specific number, consistent across conversations, tied to real needs$q$,
 $q$Number moves between conversations, or no number at all$q$,
 ARRAY[$q$What is your income goal for this year and how do you track progress?$q$,
       $q$What is the most challenging personal habit keeping you from reaching your potential income goal?$q$],
 'universal_stretch','{}',3.0,56,'final_interview_manual',
 $q$On the habit follow-up: make sure they name a personal habit, not an outside force like the economy$q$),

('126794dd-25ff-47d2-a436-724499733365','S_CAP_RISK_ON_YOU','capability','sales_skill','situational',
 $q$If you were in my position, about to invest thousands in your salary and training, would you risk it on you? Why or why not?$q$,
 $q$Closes on themselves with evidence, not just enthusiasm$q$,
 $q$Cannot make their own case — will not make ours$q$,
 ARRAY[$q$Why do you think I am asking you these questions?$q$],
 'universal_stretch','{}',2.5,54,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','S_CAP_CULTURE_GETALONG','capability','teamwork','past_behavior',
 $q$Give me an example of a time in a previous job when you had trouble getting along with someone. What would you do differently now?$q$,
 $q$Owns their half, concrete lesson$q$,
 $q$The other person was entirely the problem$q$,
 ARRAY[$q$What kind of people do you get along with best? Hardest?$q$],
 'universal_stretch','{}',3.0,52,'final_interview_manual',NULL);
