INSERT INTO public.interview_questions
(agency_id, code, construct, subconstruct, question_kind, question_text, listen_for,
 concern, followups, selection_mode, trigger_codes, est_minutes, priority, source, notes)
VALUES
('126794dd-25ff-47d2-a436-724499733365','LG_DM_1','capability','organization_detail','background',
 $q$Would your last supervisor describe your pace of work as (a) plow horse — slower, longer hours to meet deadlines; (b) trotter — average speed, eventually completes; (c) race horse — fast and efficient; or (d) slow and unproductive?$q$,
 $q$Race horse or trotter, consistent with the reference story$q$,
 $q$Plow horse or slow — confirms the low deadline motivation read$q$,
 ARRAY[$q$Does working long hours put you ahead in productivity, or does it mean you are slower and methodical? Do you prefer work over leisure?$q$],
 'legacy_triggered',ARRAY['L_LOW_DEADLINE'],3.0,50,'final_interview_manual',
 $q$Off-setting behaviors that overcome low deadline motivation: verifiable 10-12 hour days or 60+ hr/wk; early move to management; hs-to-college-to-job in 4-5 yrs; living independently$q$),
('126794dd-25ff-47d2-a436-724499733365','LG_DM_2','capability','organization_detail','background',
 $q$What will your references tell me about how many hours a week you work? Why so many hours?$q$,
 $q$High verifiable hours with a reason$q$,$q$Hedged hours, or hours without output$q$,
 '{}','legacy_triggered',ARRAY['L_LOW_DEADLINE'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_DM_3','capability','organization_detail','past_behavior',
 $q$Describe a recent goal you set. What was the goal, your steps, the original deadline, and when did you achieve it?$q$,
 $q$Goal hit on or near the original deadline$q$,$q$No deadline set, or it slid repeatedly$q$,
 ARRAY[$q$What challenges did you face pursuing that goal?$q$,$q$What is your income goal for this year and how do you track progress?$q$,
       $q$What is the most challenging personal habit keeping you from reaching your potential income goal? (Personal habit, not an outside force.)$q$],
 'legacy_triggered',ARRAY['L_LOW_DEADLINE'],3.0,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_RD_1','commitment','motivation_type','past_behavior',
 $q$Describe the last time you competed for an award. What did you do with the trophy or award — hang it on the wall or put it away?$q$,
 $q$Competes; displays or clearly values the win$q$,$q$Rarely competes; indifferent to recognition$q$,
 ARRAY[$q$How often do you compete?$q$,$q$Do you prefer praise from your manager in private or public?$q$],
 'legacy_triggered',ARRAY['L_LOW_RECOGNITION'],3.0,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_RD_2','commitment','role_attitude','situational',
 $q$In this job, you will speak to 30-40 new people a day. When you think about that: excitement (strangers become relationships) or stress (interacting with strangers all day)?$q$,
 $q$Genuine energy at the volume of new contact$q$,$q$Visible dread of stranger contact at that volume$q$,
 ARRAY[$q$Off work, do you (a) enjoy social media to keep friends informed, (b) get energized meeting new friends, or (c) prefer being alone or with a few close people?$q$],
 'legacy_triggered',ARRAY['L_LOW_RECOGNITION'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_RD_3','capability','communication','background',
 $q$If I called your last supervisor, would they describe you as (a) life of the party, (b) reserved and prefers to watch, or (c) participates when comfortable with the subject?$q$,
 $q$(a) or (c) with self-awareness$q$,$q$(b) without any compensating behavior$q$,
 ARRAY[$q$In a group setting, do you (a) jump in with expressive, energetic people, (b) sit back and pick 1-2 similar people to connect with, or (c) find expressive people annoying?$q$],
 'legacy_triggered',ARRAY['L_LOW_RECOGNITION'],2.5,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_AS_1','capability','sales_skill','background',
 $q$Would your current or previous supervisor tell me you can confidently, without hesitation, assert yourself in making decisions and telling people no when necessary?$q$,
 $q$Unhesitating yes with an example$q$,$q$Hedge — confirms low assertiveness$q$,
 ARRAY[$q$Which would your last supervisor use for you: (a) stressed when needing to speak difficult truths, (b) confident voicing opinions and hard truths, (c) participates when comfortable with the subject?$q$],
 'legacy_triggered',ARRAY['L_LOW_ASSERT'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_AS_2','capability','sales_skill','situational',
 $q$If I were a customer, what would you tell me about our company to convince me to buy? What would you tell me about YOU?$q$,
 $q$Makes a confident case for both$q$,$q$Cannot advocate for themselves$q$,
 ARRAY[$q$Making a presentation about our auto or fire insurance, what 2-3 features and benefits would you stress?$q$,
       $q$Role-play: sell me a vacation to your favorite spot; then handle my price objection.$q$],
 'legacy_triggered',ARRAY['L_LOW_ASSERT'],3.0,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_AS_3','capability','composure','past_behavior',
 $q$When you get rejected or disappoint someone, what do you do to get your confidence back?$q$,
 $q$A concrete, fast recovery routine$q$,$q$No routine; rejection lingers$q$,
 ARRAY[$q$In a group setting, do you (a) jump in with the expressive and energetic, (b) sit back and connect with 1-2 similar people, or (c) get stressed and timid if asked to lead?$q$],
 'legacy_triggered',ARRAY['L_LOW_ASSERT'],2.5,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_IS_1','capability','initiative_autonomy','past_behavior',
 $q$Give me an example of when you started something entrepreneurial from scratch. What was your level of success?$q$,
 $q$Real from-scratch initiative with an honest outcome$q$,$q$Nothing self-started, ever$q$,
 ARRAY[$q$Describe a calculated risk you took to achieve a goal. Result?$q$],
 'legacy_triggered',ARRAY['L_LOW_IND'],3.0,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_IS_2','commitment','motivation_type','motivation',
 $q$Which compensation structure do you want: lower base with higher upside for results, or higher base with a lower ceiling but predictable?$q$,
 $q$Lower base plus more upside — the manual's best answer$q$,$q$Wants the guarantee — pay-for-performance seat will grind them$q$,
 ARRAY[$q$Would your last supervisor say (a) you need close supervision when learning new or complex tasks, or (b) you prefer instructions then being left alone to complete tasks?$q$],
 'legacy_triggered',ARRAY['L_LOW_IND'],2.5,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_IS_3','capability','initiative_autonomy','background',
 $q$Which jobs in your career were pay-for-performance? How well did you perform?$q$,
 $q$Has lived on performance pay and produced$q$,$q$Never worked without a guarantee$q$,
 ARRAY[$q$What example would your supervisor give me about your ability to work independently without close supervision?$q$,
       $q$In a group at school, volunteer, or work, are you (a) agreeable and cooperative — let others lead; (b) team player with shared leadership; (c) confidently take control as primary leader; or (d) impatient with slow group decisions, prefer to just do it yourself?$q$],
 'legacy_triggered',ARRAY['L_LOW_IND'],2.5,46,'final_interview_manual',NULL),

('126794dd-25ff-47d2-a436-724499733365','LG_HA_1','capability','organization_detail','background',
 $q$What will your last supervisor tell me about your strengths and challenges related to spending too much time focused on details?$q$,
 $q$Aware of the tendency, manages it$q$,$q$Detail time is unmanaged — analysis over action$q$,
 ARRAY[$q$Describe a coaching session you might have had with your manager regarding time management.$q$],
 'legacy_triggered',ARRAY['L_HIGH_ANALYTICAL'],2.5,50,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HA_2','capability','organization_detail','background',
 $q$Which of these will your supervisor use to describe you: (a) stressed with time management, spends too much time on proposals; (b) understands the balance between prep and presentation; (c) adequately handles details with moderate coaching?$q$,
 $q$(b), with an example$q$,$q$(a) — over-preparation eats selling time$q$,
 '{}','legacy_triggered',ARRAY['L_HIGH_ANALYTICAL'],2.0,48,'final_interview_manual',NULL),
('126794dd-25ff-47d2-a436-724499733365','LG_HA_3','capability','sales_skill','background',
 $q$Describe your sales metrics: closing ratio, monthly income goal, sales per month needed, daily and weekly quotes needed, daily phone calls needed.$q$,
 $q$Knows their own funnel math cold$q$,$q$Tracks nothing — analytical everywhere except their own pipeline$q$,
 ARRAY[$q$Describe a recent goal, its challenges, original deadline, and achievement.$q$,
       $q$What is your income goal this year, how do you track progress, and what personal habit is keeping you from reaching it?$q$],
 'legacy_triggered',ARRAY['L_HIGH_ANALYTICAL'],3.0,46,'final_interview_manual',NULL);
