-- Migration: morning_recap_include_departed_and_split_quotes_vs_sp
-- Version: 20260702135506
-- Applied via Supabase MCP apply_migration
-- NOTE: History stub. Final body in functions_2026-07-02.sql.
-- Change: Include departed teammates' SP in total (quotes dashed);
--         split quotes (week-scoped) vs SP (cycle-scoped) totals.
