-- Peter correction 2026-08-27, replacing the wording written earlier the same day.
-- Two things were wrong in that version and both are corrected here.
--
-- 1. THE EXEMPTION WAS MISREAD. It is not "one short job among many is free."
-- It is: a candidate at the START of a career, holding ONLY ONE job so far and
-- that job is short, has no track record yet and must not be marked down for
-- having none. Once there are several jobs, a short one DOES count slightly
-- against them, weighed proportionally against the long ones — not waved off by
-- a three-stint threshold. Scoring is proportional, not a cliff.
--
-- 2. THIS IS A COMMITMENT SIGNAL, NOT MERELY TURNOVER RISK. The earlier wording
-- told the scorer to treat it as turnover risk only and explicitly not as
-- character. That was wrong for this agency. Peter's stated construct: the same
-- thing that makes a person leave also makes them coast — work in bursts when
-- income pressure bites, settle once the money is adequate, stop pushing for the
-- production that takes sustained effort. Turnover AND flat production are the
-- two failure modes being guarded against and they share one root. Score it as
-- commitment.
UPDATE public.hiregauge_rules
SET description = replace(description,
  E'\n\nSUSTAINED EFFORT / PEAK REVERSION (added 2026-08-27). Read the work history as a shape, not a direction. Find the highest level of responsibility the candidate ever reached, then ask what happened after it.\n\nTRAJECTORY DIRECTION — score the END STATE RELATIVE TO THE PEAK, not the general slope. Reached a level and held or exceeded it = high. Still climbing, no peak yet = score the slope as before. Reached a level, then stepped back down to a level already held earlier and stayed there = LOW (0-40) regardless of how impressive the climb was, because the climb already happened and did not hold. A step down taken for a stated reason that is not about performance — relocation, employer closure, a deliberate industry change, going back to school, taking a lower title at a much larger organisation — is NOT a reversion; score it neutral.\n\nFOLLOW-THROUGH — a PATTERN is required before any markdown. One short stint in an otherwise sustained record is not evidence of anything and must NOT be penalised; people get laid off, companies fold, one job turns out wrong. Mark down only for three or more short stints, or for short stints that all come AFTER the peak while earlier roles were long. The second shape is the strong one: it says the person could sustain once and stopped.\n\nDo not read either of these as work ethic or character. They are turnover risk and they are interview questions. The right output is a flag and a question to ask, not a decline.',
  E'\n\nSUSTAINED EFFORT / PEAK REVERSION (added 2026-08-27, wording corrected same day). Read the work history as a shape, not a direction. Find the highest level of responsibility the candidate ever reached, then ask what happened after it.\n\nTRAJECTORY DIRECTION — score the END STATE RELATIVE TO THE PEAK, not the general slope. Reached a level and held or exceeded it = high. Still climbing, no peak yet = score the slope as before. Reached a level, then stepped back down to a level already held earlier and stayed there = LOW (0-40) regardless of how impressive the climb was, because the climb already happened and did not hold. A step down taken for a stated reason that is not about performance — relocation, employer closure, a deliberate industry change, going back to school, taking a lower title at a much larger organisation — is NOT a reversion; score it neutral.\n\nFOLLOW-THROUGH — score PROPORTIONALLY, weighing short roles against long ones across the whole history. There is no free pass and no threshold. A single short role sitting among several long ones is a SLIGHT markdown, not a clean record and not a heavy hit: weigh it against the sustained roles around it and let the balance of the record decide. As short roles accumulate relative to long ones, the markdown grows with them. The heaviest markdown belongs to the shape where the long roles come EARLY and the short ones all come AFTER the peak — that says the person could sustain once and stopped, which is worse than never having sustained at all.\n\nTHE ONE EXEMPTION, and it is narrow: a candidate at the start of a working life who has held only ONE job so far and it is short has no track record yet. Score follow-through neutral for them and say so. Absence of evidence is not evidence. This exemption ends the moment there is a second job to compare against.\n\nREAD THIS AS COMMITMENT, and it is a character signal, not merely a turnover statistic. The same disposition that makes someone leave a role also makes them coast inside one: effort in bursts when income pressure bites, then settling once the money is adequate rather than pushing for production that takes sustained work. Leaving and flat production are two expressions of one root, and both are what this agency is guarding against. Weigh it accordingly.\n\nIt still produces an interview question, not an automatic decline. Ask what changed at the point the record turns.')
WHERE id = '14c87199-d835-4f90-8f34-e704c2ed073d';
