INSERT INTO public.hiregauge_instrument_items
  (section, item_number, stint, item_text, scale_max, hypothesized_trait,
   reverse_coded, is_nonsense, is_active, notes)
VALUES
  ('newtworks_v2_personality', 7, 1, 'Don''t pretend to be more than I am.', 5, 'sincerity', false, false, true, 'IPIP-HEXACO Sincerity item 1. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 8, 1, 'Use flattery to get ahead.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 2. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 9, 1, 'Tell other people what they want to hear so that they will do what I want them to do.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 3. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 10, 1, 'Put on a show to impress people.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 4. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 11, 1, 'Switch my loyalties when I feel like it.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 5. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 12, 1, 'Play a role in order to impress people.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 6. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 13, 1, 'Pretend to be concerned for others.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 7. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 14, 1, 'Act like different people in different situations.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 8. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 15, 1, 'Find it necessary to please the people who have power.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 9. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 16, 1, 'Let people push me around to help them feel important.', 5, 'sincerity', true, false, true, 'IPIP-HEXACO Sincerity item 10. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 17, 1, 'Would never take things that aren''t mine.', 5, 'fairness', false, false, true, 'IPIP-HEXACO Fairness item 1. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 18, 1, 'Would never cheat on my taxes.', 5, 'fairness', false, false, true, 'IPIP-HEXACO Fairness item 2. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 19, 1, 'Return extra change when a cashier makes a mistake.', 5, 'fairness', false, false, true, 'IPIP-HEXACO Fairness item 3. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 20, 1, 'Would feel very badly for a long time if I were to steal from someone.', 5, 'fairness', false, false, true, 'IPIP-HEXACO Fairness item 4. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 21, 1, 'Try to follow the rules.', 5, 'fairness', false, false, true, 'IPIP-HEXACO Fairness item 5. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 22, 1, 'Admire a really clever scam.', 5, 'fairness', true, false, true, 'IPIP-HEXACO Fairness item 6. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 23, 1, 'Cheat to get ahead.', 5, 'fairness', true, false, true, 'IPIP-HEXACO Fairness item 7. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 24, 1, 'Steal things.', 5, 'fairness', true, false, true, 'IPIP-HEXACO Fairness item 8. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 25, 1, 'Cheat on people who have trusted me.', 5, 'fairness', true, false, true, 'IPIP-HEXACO Fairness item 9. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 26, 1, 'Would not regret my behavior if I were to take advantage of someone impulsively.', 5, 'fairness', true, false, true, 'IPIP-HEXACO Fairness item 10. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 27, 1, 'Would not enjoy being a famous celebrity.', 5, 'greed_avoidance', false, false, true, 'IPIP-HEXACO Greed-Avoidance item 1. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 28, 1, 'Don''t strive for elegance in my appearance.', 5, 'greed_avoidance', false, false, true, 'IPIP-HEXACO Greed-Avoidance item 2. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Positive-keyed.'),
  ('newtworks_v2_personality', 29, 1, 'Love luxury.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 3. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 30, 1, 'Have a strong need for power.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 4. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 31, 1, 'Seek status.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 5. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 32, 1, 'Am mainly interested in money.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 6. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 33, 1, 'Wish to stay young forever.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 7. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 34, 1, 'Try to impress others.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 8. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 35, 1, 'Prefer to eat at expensive restaurants.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 9. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.'),
  ('newtworks_v2_personality', 36, 1, 'Am out for my own personal gain.', 5, 'greed_avoidance', true, false, true, 'IPIP-HEXACO Greed-Avoidance item 10. Ashton, Lee & Goldberg 2007 PAID 42:1515-1526. Reverse-scored.');
